In [164]:
import pandas as pd
import numpy as np
import seaborn as sns
from functools import reduce
from collections import Counter
import os
import re
import warnings
warnings.filterwarnings('ignore')
pd.options.display.max_columns = None
from IPython.display import display

In [165]:
file_path = "../data/processed/batch2019_first_year_data.csv"

# Read the CSV file, treating the first column as index and skipping it
first_year_data = pd.read_csv(file_path)
# Drop any 'Unnamed' columns
first_year_data = first_year_data.loc[:, ~first_year_data.columns.str.contains('^Unnamed')]
first_year_data

,STUDENT_NUM,STUDY_PROGRAM,ACADEMIC_YEAR,START_DATE,END_DATE,ENROLLMENT_TYPE,EXAM_TYPE,FULL_TIME_PART,PROGRAM_ACTIVE_CODE,DATE_ACTIVE_CODE_MODIFIED,HIGHER_EDU_REGISTER,DATE_REGIS_PROOF,ESTABLISHMENT_LOCATION,REGISTRATION_STATUS,PRIOR_EDU_STATUS,LANGUAGE_TEST_RESULTS,UPPER_YEAR_STUDENT_REQUEST,DATE_ENROLLMENT_REQUEST,FINANCING,STUDY_CHECK_PARTICIPATION,FLEXIBLE_STUDY_PARTICIPATION,EXAM_ADMINISTERED,DATE_EXAM_STARTED,EXAM_PROG_DETAILS,DATE_EXAM_CONDUCTED,EXAM_FINAL_RESULT,FIRST_DEGREE_CLASSIFICATION,EXAM_REGISTRATION_DATE,DATE_EXAM_DETAILS_MODIFIED,EXAM_DETAILS_SENT_DUO,FROZEN_STUDENT_STATUS,HONORS_PROG_PARTICIPATION,PRIOR_EDUCATION,PRIOR_FINAL_EXAM_DATE,SCHOOL_DESCRIPTION,PRIOR_DIMPLOMA_OBTAINTION,PRIOR_VERIFICATION_STATUS,PRIOR_VERIFICATION_DATE,PRIOR_EDUCATION_DESCRIPTION,BIRTH_DATE,GENDER,NATIONALITY,YEAR_STARTED_HU,PREFERRED_EDUCATION,PRIOR_QUALIFICATION_TYPE,INFO_CURRENT,PRIOR_EDUCATION_IBG,STUDENT_AGE,ENROLLMENT_WINDOW,PRIOR_EXAM_YEAR,EXAM_BEFORE_ENROLLMENT_STATUS,DROPOUT_RISK,YEAR
0,274166,BAPE,2020,2020-09-01,2021-08-31,S,B,V,4.0,2020-08-18,35158.0,2020-08-18,AMERSFOORT,I,S,N,N,2020-08-16,J,NVT,N,D,2017-09-01,APE-PROPV-17,2019-04-12,passed,N,2019-06-12,2019-05-23,J,J,N,611,2015-03-19,25DW00,J,GD,2015-03-19,N,1994-07-11,V,NL,2013.0,J,HBO,J,611,26,2,2015,pending,0,2020
1,442999,BJCB,2020,2020-09-01,2021-06-27,S,D,V,4.0,2020-06-19,35516.0,2020-07-30,UTRECHT,U,S,N,N,2020-05-15,J,J,N,D,2020-09-01,JCB-DV-20,2021-06-27,passed,N,2021-09-13,2021-07-08,J,J,N,591,2019-06-12,25DW00,N,GV,2020-06-19,N,2001-03-11,V,DUI,2020.0,J,HBO,J,591,19,16,2019,done,0,2020
2,417169,BOGTNGTTOL,2020,2020-09-01,2021-07-06,S,D,V,4.0,2020-08-06,34104.0,2020-08-11,UTRECHT,U,S,N,N,2020-07-01,J,NVT,N,D,2019-09-01,OGTD-PTLK-19,2021-07-06,passed,N,2021-09-16,2021-08-27,J,J,N,611,2018-07-17,23AH02,J,GD,2018-07-17,N,2000-06-29,V,NL,2019.0,J,HBO,J,611,20,9,2018,done,0,2020
3,339184,BAPE,2020,2020-09-01,2021-08-31,S,B,V,4.0,2020-08-17,35158.0,2020-08-18,AMERSFOORT,I,S,N,N,2020-07-24,J,NVT,N,B,2018-09-01,APE-BACHV-18,2024-06-28,absent,J,2015-05-29,2024-07-01,N,N,N,372,2016-06-16,06SU00,J,GD,2016-06-16,J,1998-07-06,V,NL,2017.0,J,HAVO,J,372,22,6,2016,done,1,2020
4,407420,BGHBFY,2020,2020-09-01,2021-08-31,S,D,V,0.0,2020-01-15,34570.0,2021-07-29,UTRECHT,G,N,N,N,2020-01-15,J,NVT,N,D,2021-09-01,GIBS-PROP.VT-21,2024-06-28,absent,J,2015-05-29,2024-07-01,N,N,N,371,2020-08-28,30PK,J,GD,2020-08-28,N,1999-10-31,M,NL,2021.0,J,HAVO,J,371,20,33,2020,done,1,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2775,338658,BTICIC,2020,2020-09-01,2021-03-22,S,D,V,4.0,2020-08-20,30020.0,2020-08-20,UTRECHT,U,S,N,N,2020-08-17,J,NVT,N,B,2020-09-01,TICT-VBACSD-20,2024-04-03,passed,J,2015-05-29,2024-04-11,N,J,N,374,2016-07-01,00PS08,J,GD,2016-07-01,J,1998-10-06,V,NL,2019.0,N,HAVO,J,374,21,2,2016,done,0,2020
2776,336634,BOEVSCH2,2020,2020-09-01,2021-08-31,S,D,V,4.0,2020-07-21,35199.0,2020-07-23,UTRECHT,I,S,N,N,2020-01-16,J,J,N,D,2020-09-01,OASCH-PRVT-20,2024-06-28,absent,J,2015-05-29,2024-07-01,N,N,N,374,2016-06-16,02TG00,J,GD,2016-06-16,N,1998-08-12,M,NL,2016.0,N,HAVO,J,374,21,33,2016,pending,1,2020
2777,415602,BGHBLO,2020,2020-09-01,2021-07-13,S,D,V,4.0,2020-08-17,34578.0,2020-08-18,UTRECHT,U,S,N,N,2020-06-30,J,NVT,N,D,2019-09-01,GLO-PROP-19,2021-07-13,passed,N,2021-09-09,2021-08-25,J,J,N,591,2019-06-12,25DW00,N,GV,2013-03-21,N,2001-09-13,V,NL,2019.0,J,HBO,J,591,18,9,2019,pending,0,2020
2778,440118,BMLM,2020,2020-09-01,2020-12-31,S,D,V,4.0,2020-08-31,35522.0,2020-09-01,UTRECHT,U,S,N,N,2020-04-22,J,J,N,D,2020-09-01,MBLM-DV-20,2024-06-28,absent,J,2015-05-29,2024-07-01,N,J,N,591,2019-06-12,25DW00,N,N,2013-03-21,N,2001-06-17,M,NL,2020.0,J,HBO,J,591,18,19,2019,done,1,2020
2779,445282,BJJO,2020,2020-09-01,2021-08-31,S,D,V,4.0,2020-08-21,34686.0,2020-08-25,UTRECHT,I,S,N,N,2020-05-29,J,NVT,N,HN,2023-09-01,J-HONOURS,2024-06-28,absent,J,2015-05-29,2024-07-01,N,N,N,2,2019-06-28,25PZ00,J,N,2013-03-21,J,2000-11-18,V,NL,2020.0,J,HAVO,N,2,19,14,2019,done,1,2020

# More feature Engineering

In [166]:
# create a new column called EXAM_REGIS_WINDOW in the first_year_data DataFrame, where the values are the 
# difference between the columns DATE_EXAM_CONDUCTED and EXAM_REGISTRATION_DATE in weeks


# Ensure both columns are in datetime format
first_year_data['DATE_EXAM_CONDUCTED'] = pd.to_datetime(first_year_data['DATE_EXAM_CONDUCTED'], errors='coerce')
first_year_data['EXAM_REGISTRATION_DATE'] = pd.to_datetime(first_year_data['EXAM_REGISTRATION_DATE'], errors='coerce')

# Calculate the difference between START_DATE and DATE_ENROLLMENT_REQUEST in weeks
first_year_data['EXAM_REGIS_WINDOW'] = (first_year_data['DATE_EXAM_CONDUCTED'] - first_year_data['EXAM_REGISTRATION_DATE']).dt.total_seconds() / (7 * 24 * 60 * 60)

# Round the values to the nearest integer
first_year_data['EXAM_REGIS_WINDOW'] = first_year_data['EXAM_REGIS_WINDOW'].round().astype(int)

# Delete rows with negative ENROLLMENT_WINDOW
first_year_data = first_year_data[first_year_data['EXAM_REGIS_WINDOW'] >= 0]

# Display the cleaned DataFrame
first_year_data[['DATE_EXAM_CONDUCTED', 'EXAM_REGISTRATION_DATE', 'EXAM_REGIS_WINDOW']]

     DATE_EXAM_CONDUCTED EXAM_REGISTRATION_DATE  EXAM_REGIS_WINDOW
3             2024-06-28             2015-05-29                474
4             2024-06-28             2015-05-29                474
5             2024-06-28             2015-05-29                474
6             2024-06-28             2015-05-29                474
7             2024-06-28             2015-05-29                474
...                  ...                    ...                ...
2774          2024-06-28             2015-05-29                474
2775          2024-04-03             2015-05-29                462
2776          2024-06-28             2015-05-29                474
2778          2024-06-28             2015-05-29                474
2779          2024-06-28             2015-05-29                474

[1872 rows x 3 columns]

In [167]:
first_year_data['EXAM_REGIS_WINDOW'].value_counts()

EXAM_REGIS_WINDOW
474    1652
470      26
473      26
455      21
456      16
462      16
471      14
472      13
475      12
452      12
460      12
450       9
476       9
446       9
453       6
441       6
442       5
481       4
209       4
Name: count, dtype: int64

In [168]:
first_year_data.head(3)

,STUDENT_NUM,STUDY_PROGRAM,ACADEMIC_YEAR,START_DATE,END_DATE,ENROLLMENT_TYPE,EXAM_TYPE,FULL_TIME_PART,PROGRAM_ACTIVE_CODE,DATE_ACTIVE_CODE_MODIFIED,HIGHER_EDU_REGISTER,DATE_REGIS_PROOF,ESTABLISHMENT_LOCATION,REGISTRATION_STATUS,PRIOR_EDU_STATUS,LANGUAGE_TEST_RESULTS,UPPER_YEAR_STUDENT_REQUEST,DATE_ENROLLMENT_REQUEST,FINANCING,STUDY_CHECK_PARTICIPATION,FLEXIBLE_STUDY_PARTICIPATION,EXAM_ADMINISTERED,DATE_EXAM_STARTED,EXAM_PROG_DETAILS,DATE_EXAM_CONDUCTED,EXAM_FINAL_RESULT,FIRST_DEGREE_CLASSIFICATION,EXAM_REGISTRATION_DATE,DATE_EXAM_DETAILS_MODIFIED,EXAM_DETAILS_SENT_DUO,FROZEN_STUDENT_STATUS,HONORS_PROG_PARTICIPATION,PRIOR_EDUCATION,PRIOR_FINAL_EXAM_DATE,SCHOOL_DESCRIPTION,PRIOR_DIMPLOMA_OBTAINTION,PRIOR_VERIFICATION_STATUS,PRIOR_VERIFICATION_DATE,PRIOR_EDUCATION_DESCRIPTION,BIRTH_DATE,GENDER,NATIONALITY,YEAR_STARTED_HU,PREFERRED_EDUCATION,PRIOR_QUALIFICATION_TYPE,INFO_CURRENT,PRIOR_EDUCATION_IBG,STUDENT_AGE,ENROLLMENT_WINDOW,PRIOR_EXAM_YEAR,EXAM_BEFORE_ENROLLMENT_STATUS,DROPOUT_RISK,YEAR,EXAM_REGIS_WINDOW
3,339184,BAPE,2020,2020-09-01,2021-08-31,S,B,V,4.0,2020-08-17,35158.0,2020-08-18,AMERSFOORT,I,S,N,N,2020-07-24,J,NVT,N,B,2018-09-01,APE-BACHV-18,2024-06-28,absent,J,2015-05-29,2024-07-01,N,N,N,372,2016-06-16,06SU00,J,GD,2016-06-16,J,1998-07-06,V,NL,2017.0,J,HAVO,J,372,22,6,2016,done,1,2020,474
4,407420,BGHBFY,2020,2020-09-01,2021-08-31,S,D,V,0.0,2020-01-15,34570.0,2021-07-29,UTRECHT,G,N,N,N,2020-01-15,J,NVT,N,D,2021-09-01,GIBS-PROP.VT-21,2024-06-28,absent,J,2015-05-29,2024-07-01,N,N,N,371,2020-08-28,30PK,J,GD,2020-08-28,N,1999-10-31,M,NL,2021.0,J,HAVO,J,371,20,33,2020,done,1,2020,474
5,421050,BARE,2020,2020-09-01,2021-08-31,S,D,V,4.0,2020-07-27,39205.0,2020-07-28,UTRECHT,I,S,N,N,2020-06-11,J,NVT,N,B,2020-09-01,ADR-HBRV-B-20,2024-06-28,absent,J,2015-05-29,2024-07-01,N,N,N,591,2019-06-12,21RI00,N,N,2013-03-21,N,1999-11-27,V,NL,2019.0,J,HBO,J,591,20,12,2019,pending,1,2020,474

# Delete irrelevant columns for each year data eg a radom code

In [169]:
# List of columns to delete
columns_to_delete = ['ACADEMIC_YEAR',
                     'START_DATE', 
                     'END_DATE', 
                     'PROGRAM_ACTIVE_CODE', 
                     'DATE_ACTIVE_CODE_MODIFIED', 
                     'HIGHER_EDU_REGISTER', 
                     'DATE_REGIS_PROOF',
                     'DATE_ENROLLMENT_REQUEST',
                     'DATE_EXAM_STARTED',
                     'EXAM_PROG_DETAILS',
                     'DATE_EXAM_CONDUCTED',
                     'EXAM_REGISTRATION_DATE',
                     'DATE_EXAM_DETAILS_MODIFIED',
                     'DATE_ACTIVE_CODE_MODIFIED', 
                     'PRIOR_EDUCATION', 
                     'SCHOOL_DESCRIPTION', 
                     'PRIOR_FINAL_EXAM_DATE', 
                     'PRIOR_VERIFICATION_DATE',
                     'BIRTH_DATE',
                     'YEAR_STARTED_HU',
                     'YEAR',
                     'EXAM_REGIS_WINDOW'] 

# Delete these columns from the DataFrame
first_year_data = first_year_data.drop(columns=columns_to_delete)

# Display the DataFrame after deleting the columns
first_year_data

,STUDENT_NUM,STUDY_PROGRAM,ENROLLMENT_TYPE,EXAM_TYPE,FULL_TIME_PART,ESTABLISHMENT_LOCATION,REGISTRATION_STATUS,PRIOR_EDU_STATUS,LANGUAGE_TEST_RESULTS,UPPER_YEAR_STUDENT_REQUEST,FINANCING,STUDY_CHECK_PARTICIPATION,FLEXIBLE_STUDY_PARTICIPATION,EXAM_ADMINISTERED,EXAM_FINAL_RESULT,FIRST_DEGREE_CLASSIFICATION,EXAM_DETAILS_SENT_DUO,FROZEN_STUDENT_STATUS,HONORS_PROG_PARTICIPATION,PRIOR_DIMPLOMA_OBTAINTION,PRIOR_VERIFICATION_STATUS,PRIOR_EDUCATION_DESCRIPTION,GENDER,NATIONALITY,PREFERRED_EDUCATION,PRIOR_QUALIFICATION_TYPE,INFO_CURRENT,PRIOR_EDUCATION_IBG,STUDENT_AGE,ENROLLMENT_WINDOW,PRIOR_EXAM_YEAR,EXAM_BEFORE_ENROLLMENT_STATUS,DROPOUT_RISK
3,339184,BAPE,S,B,V,AMERSFOORT,I,S,N,N,J,NVT,N,B,absent,J,N,N,N,J,GD,J,V,NL,J,HAVO,J,372,22,6,2016,done,1
4,407420,BGHBFY,S,D,V,UTRECHT,G,N,N,N,J,NVT,N,D,absent,J,N,N,N,J,GD,N,M,NL,J,HAVO,J,371,20,33,2020,done,1
5,421050,BARE,S,D,V,UTRECHT,I,S,N,N,J,NVT,N,B,absent,J,N,N,N,N,N,N,V,NL,J,HBO,J,591,20,12,2019,pending,1
6,301838,BMBDK,S,D,V,UTRECHT,I,S,N,N,J,NVT,N,D,absent,J,N,N,N,J,GD,J,M,NL,N,HAVO,J,372,24,1,2013,done,1
7,261147,BOEVWIS2,S,D,V,UTRECHT,U,S,N,N,J,NVT,N,D,absent,J,N,N,N,J,GD,N,M,NL,N,HAVO,J,374,25,1,2012,done,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2774,358305,BMIBU,S,B,V,UTRECHT,I,S,N,N,J,NVT,N,B,absent,J,N,N,N,N,N,N,V,NL,N,HBO,J,591,20,11,2019,pending,1
2775,338658,BTICIC,S,D,V,UTRECHT,U,S,N,N,J,NVT,N,B,passed,J,N,J,N,J,GD,J,V,NL,N,HAVO,J,374,21,2,2016,done,0
2776,336634,BOEVSCH2,S,D,V,UTRECHT,I,S,N,N,J,J,N,D,absent,J,N,N,N,J,GD,N,M,NL,N,HAVO,J,374,21,33,2016,pending,1
2778,440118,BMLM,S,D,V,UTRECHT,U,S,N,N,J,J,N,D,absent,J,N,J,N,N,N,N,M,NL,J,HBO,J,591,18,19,2019,done,1
2779,445282,BJJO,S,D,V,UTRECHT,I,S,N,N,J,NVT,N,HN,absent,J,N,N,N,J,N,J,V,NL,J,HAVO,N,2,19,14,2019,done,1

In [170]:
first_year_data['DROPOUT_RISK'].value_counts()

DROPOUT_RISK
1    1621
0     251
Name: count, dtype: int64

# Group

In [171]:
first_year_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1872 entries, 3 to 2779
Data columns (total 33 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   STUDENT_NUM                    1872 non-null   int64
 1   STUDY_PROGRAM                  1872 non-null   object
 2   ENROLLMENT_TYPE                1872 non-null   object
 3   EXAM_TYPE                      1872 non-null   object
 4   FULL_TIME_PART                 1872 non-null   object
 5   ESTABLISHMENT_LOCATION         1872 non-null   object
 6   REGISTRATION_STATUS            1872 non-null   object
 7   PRIOR_EDU_STATUS               1872 non-null   object
 8   LANGUAGE_TEST_RESULTS          1872 non-null   object
 9   UPPER_YEAR_STUDENT_REQUEST     1872 non-null   object
 10  FINANCING                      1872 non-null   object
 11  STUDY_CHECK_PARTICIPATION      1872 non-null   object
 12  FLEXIBLE_STUDY_PARTICIPATION   1872 non-null   object
 13  EXAM_ADMINISTERED              1872 non-null   object
 14  EXAM_FINAL_RESULT              1872 non-null   object
 15  FIRST_DEGREE_CLASSIFICATION    1872 non-null   object
 16  EXAM_DETAILS_SENT_DUO          1872 non-null   object
 17  FROZEN_STUDENT_STATUS          1872 non-null   object
 18  HONORS_PROG_PARTICIPATION      1872 non-null   object
 19  PRIOR_DIMPLOMA_OBTAINTION      1872 non-null   object
 20  PRIOR_VERIFICATION_STATUS      1872 non-null   object
 21  PRIOR_EDUCATION_DESCRIPTION    1872 non-null   object
 22  GENDER                         1872 non-null   object
 23  NATIONALITY                    1872 non-null   object
 24  PREFERRED_EDUCATION            1872 non-null   object
 25  PRIOR_QUALIFICATION_TYPE       1872 non-null   object
 26  INFO_CURRENT                   1872 non-null   object
 27  PRIOR_EDUCATION_IBG            1872 non-null   object
 28  STUDENT_AGE                    1872 non-null   int64
 29  ENROLLMENT_WINDOW              1872 non-null   int64
 30  PRIOR_EXAM_YEAR                1872 non-null   int64
 31  EXAM_BEFORE_ENROLLMENT_STATUS  1872 non-null   object
 32  DROPOUT_RISK                   1872 non-null   int64
dtypes: int64(5), object(28)
memory usage: 497.2+ KB

In [172]:
first_year_data['PRIOR_EXAM_YEAR'] = first_year_data['PRIOR_EXAM_YEAR'].astype(str)
first_year_data['DROPOUT_RISK'] = first_year_data['DROPOUT_RISK'].astype(str)

In [173]:
#Group by STUDENT_NUM and handle both object columns (like strings) with ' '.join and 
# numeric columns (like integers or floats) by calculating their average

In [174]:
# Define the aggregation functions: ' '.join for object columns and 'mean' for numeric columns
aggregation_functions = {
    col: (' '.join if first_year_data[col].dtype == 'O' else 'mean') 
    for col in first_year_data.columns if col != 'STUDENT_NUM'
}

# Ensure 'STUDENT_NUM' is treated as a string
first_year_data['STUDENT_NUM'] = first_year_data['STUDENT_NUM'].astype(str)

# Apply groupby and aggregation using the defined functions
grouped_first_year_data = first_year_data.groupby('STUDENT_NUM').agg(aggregation_functions).reset_index()

grouped_first_year_data

,STUDENT_NUM,STUDY_PROGRAM,ENROLLMENT_TYPE,EXAM_TYPE,FULL_TIME_PART,ESTABLISHMENT_LOCATION,REGISTRATION_STATUS,PRIOR_EDU_STATUS,LANGUAGE_TEST_RESULTS,UPPER_YEAR_STUDENT_REQUEST,FINANCING,STUDY_CHECK_PARTICIPATION,FLEXIBLE_STUDY_PARTICIPATION,EXAM_ADMINISTERED,EXAM_FINAL_RESULT,FIRST_DEGREE_CLASSIFICATION,EXAM_DETAILS_SENT_DUO,FROZEN_STUDENT_STATUS,HONORS_PROG_PARTICIPATION,PRIOR_DIMPLOMA_OBTAINTION,PRIOR_VERIFICATION_STATUS,PRIOR_EDUCATION_DESCRIPTION,GENDER,NATIONALITY,PREFERRED_EDUCATION,PRIOR_QUALIFICATION_TYPE,INFO_CURRENT,PRIOR_EDUCATION_IBG,STUDENT_AGE,ENROLLMENT_WINDOW,PRIOR_EXAM_YEAR,EXAM_BEFORE_ENROLLMENT_STATUS,DROPOUT_RISK
0,185667,BAPA BAPA BAPA BAPA BAPA BAPA BAPA BAPA BAPA B...,S S S S S S S S S S S S,D D D D D D D D D D D D,D D D D D D D D D D D D,UTRECHT UTRECHT UTRECHT UTRECHT UTRECHT UTRECH...,I I I I I I I I I I I I,S S S S S S S S S S S S,N N N N N N N N N N N N,N N N N N N N N N N N N,J J J J J J J J J J J J,NVT NVT NVT NVT NVT NVT NVT NVT NVT NVT NVT NVT,N N N N N N N N N N N N,B D B B B B B D D B D B,absent absent absent absent absent absent abse...,J J J J J J J J J J J J,N N N N N N N N N N N N,N N N J J J J N N N N N,N N N N N N N N N N N N,J J J J N J J J N J J N,A GD GD GD GV GD A A GV GD GD GV,J N N N N N J J N N N N,M M M M M M M M M M M M,NL NL NL NL NL NL NL NL NL NL NL NL,N J J J J J N N J J J J,HBO MBO MBO MBO HBO HBO HBO HBO HBO HBO HBO HBO,J J J J J J J J J J J J,610 10039 10039 10039 591 611 610 610 591 611 ...,33.0,2.0,2007 2005 2005 2005 2019 2007 2007 2007 2019 2...,pending done done done pending pending pending...,1 1 1 1 1 1 1 1 1 1 1 1
1,226491,BMFC BMFC BMFC BMFC BMFC BMFC BMFC BMFC,S S S S S S S S,B B B B B B B B,V V V V V V V V,UTRECHT UTRECHT UTRECHT UTRECHT UTRECHT UTRECH...,I I I I I I I I,S S S S S S S S,N N N N N N N N,N N N N N N N N,J J J J J J J J,NVT NVT NVT NVT NVT NVT NVT NVT,N N N N N N N N,B B B B B B B B,absent absent absent absent absent absent abse...,J J J J J J J J,N N N N N N N N,N N N N N N N N,N N N N N N N N,J J J J N J J N,GD GD GD GD GV GD GD GV,J J N N N J J N,V V V V V V V V,NL NL NL NL NL NL NL NL,N J J J J N J J,HAVO HAVO HBO HBO HBO HAVO HAVO HBO,J J J J J J J J,372 372 611 611 591 372 372 591,30.0,1.0,2009 2009 2012 2012 2019 2009 2009 2019,pending pending pending pending pending pendin...,1 1 1 1 1 1 1 1
2,255477,BAMW BASW BASW BAMW BAMW BASW BASW BASW BASW B...,S S S S S S S S S S S S S S S S S S S S S S S ...,B D D B B D D D D B B B D B D D B D D D B B B ...,V V V V V V V V V V V V V V V V V V V V V V V ...,UTRECHT UTRECHT UTRECHT UTRECHT UTRECHT UTRECH...,I G G I I G G G G I I I G I G G I G G G I I I ...,S S S S S S S S S S S S S S S S S S S S S S S ...,N N N N N N N N N N N N N N N N N N N N N N N ...,J J J J J J J J J J J J J J J J J J J J J J J ...,J J J J J J J J J J J J J J J J J J J J J J J ...,J J J J J J J J J J J J J J J J J J J J J J J ...,N N N N N N N N N N N N N N N N N N N N N N N ...,B B D B D B B D B D B B B D B B B B B D B B D ...,absent absent absent absent absent absent abse...,J J J J J J J J J J J J J J J J J J J J J J J ...,N N N N N N N N N N N N N N N N N N N N N N N ...,N J N J N J J N N N N N N N J N J J N N J J N ...,N N N N N N N N N N N N N N N N N N N N N N N ...,N N N N N N N J N N J J N J N J N N N N N N J ...,GV GV N GV N GV N GD N N GD GD N GD N GD N N G...,N N N N N N N J N N J J N J N J N N N N N N J ...,V V V V V V V V V V V V V V V V V V V V V V V ...,NL NL NL NL NL NL NL NL NL NL NL NL NL NL NL N...,N N J N N N N N J J N N N N J N N J N J J N N ...,HBO HBO HBO HBO HBO HBO HBO MBO HBO HBO MBO MB...,J J J J J J J J J J J J J J J J J J J J J J J ...,591 591 591 591 591 591 591 10710 591 591 1071...,31.0,4.0,2019 2019 2019 2019 2019 2019 2019 2009 2019 2...,pending pending pending pending pending pendin...,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 ...
3,258433,BOTAENG2 BOTAENG2 BOTAENG2 BOTAENG2,S S S S,B B B B,V V V V,UTRECHT UTRECHT UTRECHT UTRECHT,U U U U,S S S S,N N N N,N N N N,J J J J,NVT NVT NVT NVT,N N N N,B B B B,absent absent absent absent,J J J J,N N N N,N N N N,N N N N,J J N J,GD GD GV GD,N J N J,V V V V,NL NL NL NL,J N J J,HBO HAVO HBO HAVO,J J J J,611 371 591 371,26.0,6.0,2018 2012 2019 2012,pending done pending done,1 1 1 1
4,258831,BOTAENG2 BOTAENG2 BOTAENG2 BOTAENG2 BOTAENG2 B...,S S S S S S S S S S S S S S S,B B B B B B B B B B B B B B B,D D D D D D D D D D D D D D D,UTRECHT UTRECHT UTRECHT UTRECHT UTRECHT UTRECH...,I I I I I I I I I I I I I I I,S S S S S S S S S S S S S S S,N N N N N N N N N N N N N N N,N N N N N N N N N N N N N N N,J J J J J J J J J J J J J J J,NVT NVT NVT NVT NVT NVT NVT NVT NVT NVT NVT NV...,N N N N N N N N N N N N N N N,B B B B B B B B B B B B B B B,absent absent absent absent absent absent abse...,J J J J J J J J J J J J J J J,N N N N N N N N N N N N N N N,N N N N N N N N N N N N N N N,N N N N N N N N N N N N N N N,J N N J N N J N J N J J J J J,GD N GV GD GV N GD N GD GV GD GD GD GD GD,J N N N N N N N J N N N N J N,V V V V V V V V V V V V V V V,NIG NIG NIG NIG NIG NIG NIG NIG NIG NIG NIG NI...,J N J N J N N N J J N N N J N,HBO HBO HBO MBO HBO HBO HBO HBO HBO HBO HBO HB...,J J J J J J J J J J J J J J J,611 591 591 10849 591 591 611 591 611 591 611 ...,36.0,5.0,2014 2019 2019 2005 2019 2019 2014 2019 2014 2...,pending pending pending done pending pending p...,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,445479,BOEVWIS2 BOEVWIS2 BOEVWIS2 BOEVWIS2 BOEVWIS2 B...,S S S S S S S S S S S S S S S S S S,D D D D D D D D D D D D D D D D D D,D D D D D D D D D D D D D D D D D D,UTRECHT UTRECHT UTRECHT UTRECHT UTRECHT UTRECH...,U U U U U U U U U U U U U U U U U U,S S S S S S S S S S S S S S S S S S,N N N N N N N N N N N N N N N N N N,N N N N N N N N N N N N N N N N N N,J J J J J J J J J J J J J J J J J J,J J J J J J J J J J J J J J J J J J,N N N N N N N N N N N N N N N N N N,B B B B B B B B B B B B B B B B B B,absent absent absent absent absent absent abse...,J J J J J J J J J J J J J J J J J J,N N N N N N N N N N N N N N N N N N,N N J N N N N J N J J N J N N J N N,N N N N N N N N N N N N N N N N N N,J N N J J N J J J J J J J N J N J N,GD GV GV GD GD GV GD GD GD GD GD GD GD GV GD G...,N N N N N N J J J N N N J N J N J N,V V V V V V V V V V V V V V V V V V,NL NL NL NL NL NL NL NL NL NL NL NL NL NL NL N...,J J J J J J J J J J J J J J J J J J,HBO HBO HBO HBO HBO HBO WO WO WO HBO HBO HBO W...,J J J J J J J J J J J J J J J J J J,611 591 591 611 611 591 740 740 740 611 611 61...,47.0,13.0,2021 2019 2019 2021 2021 2019 1998 1998 1998 2...,pending done done pending pending done done do...,1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
107,446276,BTLCLS BTLCLS BTLCLS BTLCLS BTLCLS,S S S S S,D D D D D,V V V V V,UTRECHT UTRECHT UTRECHT UTRECHT UTRECHT,I I I I I,S S S S S,N N N N N,N N N N N,J J J J J,J J J J J,N N N N N,B B B B B,absent absent absent absent absent,J J J J J,N N N N N,N N N N N,N N N N N,N J N J J,GV GD N GD GD,N N J N N,V V V V V,NL NL NL NL NL,N J J J N,HBO HBO HBO HAVO HAVO,J J J J J,591 611 591 371 371,20.0,13.0,2019 2023 2019 2018 2018,done pending done done done,1 1 1 1 1
108,450361,BGHBZO BGHBZO BGHBZO BGHBZO BGHBZO BGHBZO BGHB...,S S S S S S S S S S S S,D D D D D D D D D D D D,D D D D D D D D D D D D,AMERSFOORT AMERSFOORT AMERSFOORT AMERSFOORT AM...,I I I I I I I I I I I I,S S S S S S S S S S S S,N N N N N N N N N N N N,N N N N N N N N N N N N,J J J J J J J J J J J J,J J J J J J J J J J J J,N N N N N N N N N N N N,B B B B B B B B B B B B,absent MG absent MG absent MG absent MG MG abs...,J J J J J J J J J J J J,N N N N N N N N N N N N,N J N J N J N J J N J N,N N N N N N N N N N N N,N J J J J N J J J J J J,GV GD GD GD GD GV GD GD GD GD GD GD,N J N N N N J N J N N J,V V V V V V V V V V V V,NL NL NL NL NL NL NL NL NL NL NL NL,J J J J J J J J J N N J,HBO MBO HBO HBO HBO HBO MBO HBO MBO HBO HBO MBO,J J J J J J J J J J J J,591 93510 611 611 611 591 93510 611 93510 591 ...,26.0,19.0,2019 2014 2022 2022 2022 2019 2014 2022 2014 2...,done done pending pending pending done done pe...,1 0 1 0 1 0 1 0 0 1 0 1
109,450549,BMBDK BMBDK BMBDK BMBDK BMBDK BMBDK,S S S S S S,D D D D D D,D D D D D D,UTRECHT UTRECHT UTRECHT UTRECHT UTRECHT UTRECHT,I I I I I I,S S S S S S,N N N N N N,N N N N N N,J J J J J J,J J J J J J,N N N N N N,B B B B B B,absent absent absent absent absent absent,J J J J J J,N N N N N N,N N N N N N,N N N N N N,J N J J J J,N GV DD N DD GD,N N J N J N,V V V V V V,NL NL NL NL NL NL,J J N N N N,HBO HBO HAVO HAVO VWO HBO,J J J J J J,611 591 154 161 355 611,36.0,5.0,2003 2019 2001 2001 2001 2021,done done done done done pending,1 1 1 1 1 1
110,52971,BOEVWIS2 BOEVWIS2 BOEVWIS2 BOEVWIS2,S S S S,B B B B,D D D D,UTRECHT UTRECHT UTRECHT UTRECHT,I I I I,S S S S,N N N N,N N N N,J J J J,NVT NVT NVT NVT,N N N N,B B B B,absent absent absent absent,J J J J,N N N N,N N N N,N N N N,J J N J,DD DD GV GD,J J N N,V V V V,NL NL NL NL,N N J J,HAVO VWO HBO HBO,J J J J,151 350 591 611,41.0,4.0,1999 1999 2019 2012,done done pending pending,1 1 1 1

In [175]:
# Function to return the most frequent string in a list or the unique one
def get_most_frequent_or_unique(strings):
    # Check if all strings are the same
    if len(set(strings)) == 1:
        return strings[0]  # Return the single unique string
    else:
        # If there are different strings, return the most common one
        return Counter(strings).most_common(1)[0][0]

# Iterate through columns in the DataFrame
for col in grouped_first_year_data.select_dtypes(include='object').columns:
    # Apply the function across each row to find most frequent or unique string
    grouped_first_year_data[col] = grouped_first_year_data[col].apply(lambda x: get_most_frequent_or_unique(x.split()) if isinstance(x, str) else x)

grouped_first_year_data

,STUDENT_NUM,STUDY_PROGRAM,ENROLLMENT_TYPE,EXAM_TYPE,FULL_TIME_PART,ESTABLISHMENT_LOCATION,REGISTRATION_STATUS,PRIOR_EDU_STATUS,LANGUAGE_TEST_RESULTS,UPPER_YEAR_STUDENT_REQUEST,FINANCING,STUDY_CHECK_PARTICIPATION,FLEXIBLE_STUDY_PARTICIPATION,EXAM_ADMINISTERED,EXAM_FINAL_RESULT,FIRST_DEGREE_CLASSIFICATION,EXAM_DETAILS_SENT_DUO,FROZEN_STUDENT_STATUS,HONORS_PROG_PARTICIPATION,PRIOR_DIMPLOMA_OBTAINTION,PRIOR_VERIFICATION_STATUS,PRIOR_EDUCATION_DESCRIPTION,GENDER,NATIONALITY,PREFERRED_EDUCATION,PRIOR_QUALIFICATION_TYPE,INFO_CURRENT,PRIOR_EDUCATION_IBG,STUDENT_AGE,ENROLLMENT_WINDOW,PRIOR_EXAM_YEAR,EXAM_BEFORE_ENROLLMENT_STATUS,DROPOUT_RISK
0,185667,BAPA,S,D,D,UTRECHT,I,S,N,N,J,NVT,N,B,absent,J,N,N,N,J,GD,N,M,NL,J,HBO,J,610,33.0,2.0,2007,pending,1
1,226491,BMFC,S,B,V,UTRECHT,I,S,N,N,J,NVT,N,B,absent,J,N,N,N,J,GD,J,V,NL,J,HAVO,J,372,30.0,1.0,2009,pending,1
2,255477,BAMW,S,B,V,UTRECHT,I,S,N,J,J,J,N,B,absent,J,N,N,N,N,N,N,V,NL,N,HBO,J,591,31.0,4.0,2019,pending,1
3,258433,BOTAENG2,S,B,V,UTRECHT,U,S,N,N,J,NVT,N,B,absent,J,N,N,N,J,GD,N,V,NL,J,HBO,J,371,26.0,6.0,2012,pending,1
4,258831,BOTAENG2,S,B,D,UTRECHT,I,S,N,N,J,NVT,N,B,absent,J,N,N,N,J,GD,N,V,NIG,N,HBO,J,611,36.0,5.0,2014,pending,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,445479,BOEVWIS2,S,D,D,UTRECHT,U,S,N,N,J,J,N,B,absent,J,N,N,N,J,GD,N,V,NL,J,HBO,J,611,47.0,13.0,2021,done,1
107,446276,BTLCLS,S,D,V,UTRECHT,I,S,N,N,J,J,N,B,absent,J,N,N,N,J,GD,N,V,NL,J,HBO,J,591,20.0,13.0,2019,done,1
108,450361,BGHBZO,S,D,D,AMERSFOORT,I,S,N,N,J,J,N,B,absent,J,N,N,N,J,GD,N,V,NL,J,HBO,J,591,26.0,19.0,2014,done,1
109,450549,BMBDK,S,D,D,UTRECHT,I,S,N,N,J,J,N,B,absent,J,N,N,N,J,N,N,V,NL,N,HBO,J,611,36.0,5.0,2001,done,1
110,52971,BOEVWIS2,S,B,D,UTRECHT,I,S,N,N,J,NVT,N,B,absent,J,N,N,N,J,DD,J,V,NL,N,HBO,J,151,41.0,4.0,1999,done,1

In [176]:
grouped_first_year_data['DROPOUT_RISK'].value_counts()

DROPOUT_RISK
1    108
0      3
Name: count, dtype: int64

In [177]:
# Print value counts for all columns
for col in grouped_first_year_data.columns:
    print(f"Value counts for column: {col}")
    print(grouped_first_year_data[col].value_counts(dropna=False))  # include NaN values in the count
    print("\n" + "="*50 + "\n")

Value counts for column: STUDENT_NUM
STUDENT_NUM
185667    1
226491    1
255477    1
258433    1
258831    1
         ..
445479    1
446276    1
450361    1
450549    1
52971     1
Name: count, Length: 111, dtype: int64

==================================================

Value counts for column: STUDY_PROGRAM
STUDY_PROGRAM
BTICIC          7
BMBDK           6
BOTAENG2        6
BJCB            6
BASW            6
BJJO            5
BGHBLO          5
BAPE            5
BMFC            4
BTLCCY          4
BGHBFY          4
BOEVWIS2        4
BAPA            3
BMCE            3
BAIV            3
BTIBTB          3
BGHBFA          3
BGHBHB          3
BTLCLS          2
BGHBZO          2
BJDE            2
BMFTA           2
BOGTNGTTOL      2
BOEVSCH2        2
BJCM            2
BARE            2
BAMW            1
BOTANED2        1
BASJ            1
MOEVBIO         1
BGHBMH          1
BMIBU           1
BACTMU          1
BOTAENG2EN      1
BOEVBIO2        1
EOETGTD-NGTC    1
BGHBCE          1
BTETET          1
BMLM            1
BTLCCE          1
BMORM           1
Name: count, dtype: int64

==================================================

Value counts for column: ENROLLMENT_TYPE
ENROLLMENT_TYPE
S    110
C      1
Name: count, dtype: int64

==================================================

Value counts for column: EXAM_TYPE
EXAM_TYPE
D    77
B    32
M     1
C     1
Name: count, dtype: int64

==================================================

Value counts for column: FULL_TIME_PART
FULL_TIME_PART
V    94
D    15
L     2
Name: count, dtype: int64

==================================================

Value counts for column: ESTABLISHMENT_LOCATION
ESTABLISHMENT_LOCATION
UTRECHT       101
AMERSFOORT      9
ONBEKEND        1
Name: count, dtype: int64

==================================================

Value counts for column: REGISTRATION_STATUS
REGISTRATION_STATUS
I    75
U    31
G     5
Name: count, dtype: int64

==================================================

Value counts for column: PRIOR_EDU_STATUS
PRIOR_EDU_STATUS
S    106
N      5
Name: count, dtype: int64

==================================================

Value counts for column: LANGUAGE_TEST_RESULTS
LANGUAGE_TEST_RESULTS
N    111
Name: count, dtype: int64

==================================================

Value counts for column: UPPER_YEAR_STUDENT_REQUEST
UPPER_YEAR_STUDENT_REQUEST
N    108
J      3
Name: count, dtype: int64

==================================================

Value counts for column: FINANCING
FINANCING
J    110
N      1
Name: count, dtype: int64

==================================================

Value counts for column: STUDY_CHECK_PARTICIPATION
STUDY_CHECK_PARTICIPATION
NVT    67
J      44
Name: count, dtype: int64

==================================================

Value counts for column: FLEXIBLE_STUDY_PARTICIPATION
FLEXIBLE_STUDY_PARTICIPATION
N    110
J      1
Name: count, dtype: int64

==================================================

Value counts for column: EXAM_ADMINISTERED
EXAM_ADMINISTERED
B     83
D     19
HN     7
M      2
Name: count, dtype: int64

==================================================

Value counts for column: EXAM_FINAL_RESULT
EXAM_FINAL_RESULT
absent    108
passed      2
MG          1
Name: count, dtype: int64

==================================================

Value counts for column: FIRST_DEGREE_CLASSIFICATION
FIRST_DEGREE_CLASSIFICATION
J    111
Name: count, dtype: int64

==================================================

Value counts for column: EXAM_DETAILS_SENT_DUO
EXAM_DETAILS_SENT_DUO
N    111
Name: count, dtype: int64

==================================================

Value counts for column: FROZEN_STUDENT_STATUS
FROZEN_STUDENT_STATUS
N    94
J    17
Name: count, dtype: int64

==================================================

Value counts for column: HONORS_PROG_PARTICIPATION
HONORS_PROG_PARTICIPATION
N    111
Name: count, dtype: int64

==================================================

Value counts for column: PRIOR_DIMPLOMA_OBTAINTION
PRIOR_DIMPLOMA_OBTAINTION
J    87
N    24
Name: count, dtype: int64

==================================================

Value counts for column: PRIOR_VERIFICATION_STATUS
PRIOR_VERIFICATION_STATUS
GD    81
N     19
GV     6
DD     5
Name: count, dtype: int64

==================================================

Value counts for column: PRIOR_EDUCATION_DESCRIPTION
PRIOR_EDUCATION_DESCRIPTION
N    94
J    17
Name: count, dtype: int64

==================================================

Value counts for column: GENDER
GENDER
V    68
M    43
Name: count, dtype: int64

==================================================

Value counts for column: NATIONALITY
NATIONALITY
NL     105
TUR      2
NIG      1
CHI      1
SPA      1
DUI      1
Name: count, dtype: int64

==================================================

Value counts for column: PREFERRED_EDUCATION
PREFERRED_EDUCATION
J    88
N    23
Name: count, dtype: int64

==================================================

Value counts for column: PRIOR_QUALIFICATION_TYPE
PRIOR_QUALIFICATION_TYPE
HBO     82
HAVO    24
VWO      5
Name: count, dtype: int64

==================================================

Value counts for column: INFO_CURRENT
INFO_CURRENT
J    111
Name: count, dtype: int64

==================================================

Value counts for column: PRIOR_EDUCATION_IBG
PRIOR_EDUCATION_IBG
591      42
372      15
371      13
611      10
373      10
601       3
172       2
370       2
94523     1
610       1
741       1
374       1
171       1
25132     1
94130     1
3         1
10040     1
173       1
801       1
25412     1
25779     1
151       1
Name: count, dtype: int64

==================================================

Value counts for column: STUDENT_AGE
STUDENT_AGE
21.0    14
20.0    14
19.0    13
18.0    13
22.0     8
17.0     7
16.0     7
26.0     6
25.0     6
23.0     5
36.0     2
32.0     2
27.0     2
24.0     2
29.0     2
30.0     1
33.0     1
31.0     1
50.0     1
20.5     1
17.6     1
47.0     1
41.0     1
Name: count, dtype: int64

==================================================

Value counts for column: ENROLLMENT_WINDOW
ENROLLMENT_WINDOW
2.0     13
1.0      8
8.0      7
4.0      5
6.0      5
3.0      5
14.0     5
11.0     4
7.0      4
20.0     4
25.0     4
5.0      4
21.0     4
9.0      3
12.0     3
33.0     3
19.0     3
16.0     3
34.0     3
24.0     2
13.0     2
32.0     2
10.0     2
23.0     2
31.0     2
17.0     2
18.0     2
0.0      1
35.0     1
23.8     1
22.0     1
15.0     1
Name: count, dtype: int64

==================================================

Value counts for column: PRIOR_EXAM_YEAR
PRIOR_EXAM_YEAR
2019    61
2020    16
2018    13
2016     4
2017     4
2014     3
2021     2
2015     2
2007     1
2009     1
2012     1
2022     1
2001     1
1999     1
Name: count, dtype: int64

==================================================

Value counts for column: EXAM_BEFORE_ENROLLMENT_STATUS
EXAM_BEFORE_ENROLLMENT_STATUS
pending    80
done       31
Name: count, dtype: int64

==================================================

Value counts for column: DROPOUT_RISK
DROPOUT_RISK
1    108
0      3
Name: count, dtype: int64

==================================================

In [178]:
# Function to convert object columns with two unique values into binary
def convert_to_binary(col):
    unique_vals = col.unique()
    
    # Check if the column has exactly two unique values
    if len(unique_vals) == 2:
        # Check if one of the values is 'J' and assign 1 to 'J', 0 to the other
        if 'J' in unique_vals:
            col = col.map({unique_vals[0]: 1, unique_vals[1]: 0}) if unique_vals[0] == 'J' else col.map({unique_vals[1]: 1, unique_vals[0]: 0})
        else:
            # Assign 1 to one of the values and 0 to the other
            col = col.map({unique_vals[0]: 1, unique_vals[1]: 0})
    
    return col

# Apply the conversion to all object-type columns in grouped_first_year_data
for col in grouped_first_year_data.select_dtypes(include='object').columns:
    grouped_first_year_data[col] = convert_to_binary(grouped_first_year_data[col])

# Display the modified DataFrame 
grouped_first_year_data

,STUDENT_NUM,STUDY_PROGRAM,ENROLLMENT_TYPE,EXAM_TYPE,FULL_TIME_PART,ESTABLISHMENT_LOCATION,REGISTRATION_STATUS,PRIOR_EDU_STATUS,LANGUAGE_TEST_RESULTS,UPPER_YEAR_STUDENT_REQUEST,FINANCING,STUDY_CHECK_PARTICIPATION,FLEXIBLE_STUDY_PARTICIPATION,EXAM_ADMINISTERED,EXAM_FINAL_RESULT,FIRST_DEGREE_CLASSIFICATION,EXAM_DETAILS_SENT_DUO,FROZEN_STUDENT_STATUS,HONORS_PROG_PARTICIPATION,PRIOR_DIMPLOMA_OBTAINTION,PRIOR_VERIFICATION_STATUS,PRIOR_EDUCATION_DESCRIPTION,GENDER,NATIONALITY,PREFERRED_EDUCATION,PRIOR_QUALIFICATION_TYPE,INFO_CURRENT,PRIOR_EDUCATION_IBG,STUDENT_AGE,ENROLLMENT_WINDOW,PRIOR_EXAM_YEAR,EXAM_BEFORE_ENROLLMENT_STATUS,DROPOUT_RISK
0,185667,BAPA,1,D,D,UTRECHT,I,1,N,0,1,0,0,B,absent,J,N,0,N,1,GD,0,1,NL,1,HBO,J,610,33.0,2.0,2007,1,1
1,226491,BMFC,1,B,V,UTRECHT,I,1,N,0,1,0,0,B,absent,J,N,0,N,1,GD,1,0,NL,1,HAVO,J,372,30.0,1.0,2009,1,1
2,255477,BAMW,1,B,V,UTRECHT,I,1,N,1,1,1,0,B,absent,J,N,0,N,0,N,0,0,NL,0,HBO,J,591,31.0,4.0,2019,1,1
3,258433,BOTAENG2,1,B,V,UTRECHT,U,1,N,0,1,0,0,B,absent,J,N,0,N,1,GD,0,0,NL,1,HBO,J,371,26.0,6.0,2012,1,1
4,258831,BOTAENG2,1,B,D,UTRECHT,I,1,N,0,1,0,0,B,absent,J,N,0,N,1,GD,0,0,NIG,0,HBO,J,611,36.0,5.0,2014,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,445479,BOEVWIS2,1,D,D,UTRECHT,U,1,N,0,1,1,0,B,absent,J,N,0,N,1,GD,0,0,NL,1,HBO,J,611,47.0,13.0,2021,0,1
107,446276,BTLCLS,1,D,V,UTRECHT,I,1,N,0,1,1,0,B,absent,J,N,0,N,1,GD,0,0,NL,1,HBO,J,591,20.0,13.0,2019,0,1
108,450361,BGHBZO,1,D,D,AMERSFOORT,I,1,N,0,1,1,0,B,absent,J,N,0,N,1,GD,0,0,NL,1,HBO,J,591,26.0,19.0,2014,0,1
109,450549,BMBDK,1,D,D,UTRECHT,I,1,N,0,1,1,0,B,absent,J,N,0,N,1,N,0,0,NL,0,HBO,J,611,36.0,5.0,2001,0,1
110,52971,BOEVWIS2,1,B,D,UTRECHT,I,1,N,0,1,0,0,B,absent,J,N,0,N,1,DD,1,0,NL,0,HBO,J,151,41.0,4.0,1999,0,1

In [179]:
# Find and delete columns where all values are the same
columns_to_delete = [col for col in grouped_first_year_data.columns if grouped_first_year_data[col].nunique() == 1]

# Drop these columns from the DataFrame
grouped_first_year_data = grouped_first_year_data.drop(columns=columns_to_delete)

# Display the updated DataFrame and the removed columns
print(f"Deleted columns: {columns_to_delete}")
grouped_first_year_data

Deleted columns: ['LANGUAGE_TEST_RESULTS', 'FIRST_DEGREE_CLASSIFICATION', 'EXAM_DETAILS_SENT_DUO', 'HONORS_PROG_PARTICIPATION', 'INFO_CURRENT']

,STUDENT_NUM,STUDY_PROGRAM,ENROLLMENT_TYPE,EXAM_TYPE,FULL_TIME_PART,ESTABLISHMENT_LOCATION,REGISTRATION_STATUS,PRIOR_EDU_STATUS,UPPER_YEAR_STUDENT_REQUEST,FINANCING,STUDY_CHECK_PARTICIPATION,FLEXIBLE_STUDY_PARTICIPATION,EXAM_ADMINISTERED,EXAM_FINAL_RESULT,FROZEN_STUDENT_STATUS,PRIOR_DIMPLOMA_OBTAINTION,PRIOR_VERIFICATION_STATUS,PRIOR_EDUCATION_DESCRIPTION,GENDER,NATIONALITY,PREFERRED_EDUCATION,PRIOR_QUALIFICATION_TYPE,PRIOR_EDUCATION_IBG,STUDENT_AGE,ENROLLMENT_WINDOW,PRIOR_EXAM_YEAR,EXAM_BEFORE_ENROLLMENT_STATUS,DROPOUT_RISK
0,185667,BAPA,1,D,D,UTRECHT,I,1,0,1,0,0,B,absent,0,1,GD,0,1,NL,1,HBO,610,33.0,2.0,2007,1,1
1,226491,BMFC,1,B,V,UTRECHT,I,1,0,1,0,0,B,absent,0,1,GD,1,0,NL,1,HAVO,372,30.0,1.0,2009,1,1
2,255477,BAMW,1,B,V,UTRECHT,I,1,1,1,1,0,B,absent,0,0,N,0,0,NL,0,HBO,591,31.0,4.0,2019,1,1
3,258433,BOTAENG2,1,B,V,UTRECHT,U,1,0,1,0,0,B,absent,0,1,GD,0,0,NL,1,HBO,371,26.0,6.0,2012,1,1
4,258831,BOTAENG2,1,B,D,UTRECHT,I,1,0,1,0,0,B,absent,0,1,GD,0,0,NIG,0,HBO,611,36.0,5.0,2014,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,445479,BOEVWIS2,1,D,D,UTRECHT,U,1,0,1,1,0,B,absent,0,1,GD,0,0,NL,1,HBO,611,47.0,13.0,2021,0,1
107,446276,BTLCLS,1,D,V,UTRECHT,I,1,0,1,1,0,B,absent,0,1,GD,0,0,NL,1,HBO,591,20.0,13.0,2019,0,1
108,450361,BGHBZO,1,D,D,AMERSFOORT,I,1,0,1,1,0,B,absent,0,1,GD,0,0,NL,1,HBO,591,26.0,19.0,2014,0,1
109,450549,BMBDK,1,D,D,UTRECHT,I,1,0,1,1,0,B,absent,0,1,N,0,0,NL,0,HBO,611,36.0,5.0,2001,0,1
110,52971,BOEVWIS2,1,B,D,UTRECHT,I,1,0,1,0,0,B,absent,0,1,DD,1,0,NL,0,HBO,151,41.0,4.0,1999,0,1

In [180]:
grouped_first_year_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 28 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   STUDENT_NUM                    111 non-null    object
 1   STUDY_PROGRAM                  111 non-null    object
 2   ENROLLMENT_TYPE                111 non-null    int64
 3   EXAM_TYPE                      111 non-null    object
 4   FULL_TIME_PART                 111 non-null    object
 5   ESTABLISHMENT_LOCATION         111 non-null    object
 6   REGISTRATION_STATUS            111 non-null    object
 7   PRIOR_EDU_STATUS               111 non-null    int64
 8   UPPER_YEAR_STUDENT_REQUEST     111 non-null    int64
 9   FINANCING                      111 non-null    int64
 10  STUDY_CHECK_PARTICIPATION      111 non-null    int64
 11  FLEXIBLE_STUDY_PARTICIPATION   111 non-null    int64
 12  EXAM_ADMINISTERED              111 non-null    object
 13  EXAM_FINAL_RESULT              111 non-null    object
 14  FROZEN_STUDENT_STATUS          111 non-null    int64
 15  PRIOR_DIMPLOMA_OBTAINTION      111 non-null    int64
 16  PRIOR_VERIFICATION_STATUS      111 non-null    object
 17  PRIOR_EDUCATION_DESCRIPTION    111 non-null    int64
 18  GENDER                         111 non-null    int64
 19  NATIONALITY                    111 non-null    object
 20  PREFERRED_EDUCATION            111 non-null    int64
 21  PRIOR_QUALIFICATION_TYPE       111 non-null    object
 22  PRIOR_EDUCATION_IBG            111 non-null    object
 23  STUDENT_AGE                    111 non-null    float64
 24  ENROLLMENT_WINDOW              111 non-null    float64
 25  PRIOR_EXAM_YEAR                111 non-null    object
 26  EXAM_BEFORE_ENROLLMENT_STATUS  111 non-null    int64
 27  DROPOUT_RISK                   111 non-null    int64
dtypes: float64(2), int64(13), object(13)
memory usage: 24.4+ KB

In [181]:
grouped_first_year_data['STUDENT_NUM'] = grouped_first_year_data['STUDENT_NUM'].astype(int)

In [ ]:
encoded_data = grouped_first_year_data

In [183]:
# Identify object-type columns
object_columns = encoded_data.select_dtypes(include='object').columns

# Perform one-hot encoding
encoded_data = pd.get_dummies(encoded_data, columns=object_columns, prefix=object_columns, drop_first=False)

# Loop through columns and check for True/False values and convert them to 1/0
for col in encoded_data.columns:
    if encoded_data[col].dtype == 'bool':
        encoded_data[col] = encoded_data[col].astype(int)

# Display the updated DataFrame with 1s and 0s
encoded_data

,STUDENT_NUM,ENROLLMENT_TYPE,PRIOR_EDU_STATUS,UPPER_YEAR_STUDENT_REQUEST,FINANCING,STUDY_CHECK_PARTICIPATION,FLEXIBLE_STUDY_PARTICIPATION,FROZEN_STUDENT_STATUS,PRIOR_DIMPLOMA_OBTAINTION,PRIOR_EDUCATION_DESCRIPTION,GENDER,PREFERRED_EDUCATION,STUDENT_AGE,ENROLLMENT_WINDOW,EXAM_BEFORE_ENROLLMENT_STATUS,DROPOUT_RISK,STUDY_PROGRAM_BACTMU,STUDY_PROGRAM_BAIV,STUDY_PROGRAM_BAMW,STUDY_PROGRAM_BAPA,STUDY_PROGRAM_BAPE,STUDY_PROGRAM_BARE,STUDY_PROGRAM_BASJ,STUDY_PROGRAM_BASW,STUDY_PROGRAM_BGHBCE,STUDY_PROGRAM_BGHBFA,STUDY_PROGRAM_BGHBFY,STUDY_PROGRAM_BGHBHB,STUDY_PROGRAM_BGHBLO,STUDY_PROGRAM_BGHBMH,STUDY_PROGRAM_BGHBZO,STUDY_PROGRAM_BJCB,STUDY_PROGRAM_BJCM,STUDY_PROGRAM_BJDE,STUDY_PROGRAM_BJJO,STUDY_PROGRAM_BMBDK,STUDY_PROGRAM_BMCE,STUDY_PROGRAM_BMFC,STUDY_PROGRAM_BMFTA,STUDY_PROGRAM_BMIBU,STUDY_PROGRAM_BMLM,STUDY_PROGRAM_BMORM,STUDY_PROGRAM_BOEVBIO2,STUDY_PROGRAM_BOEVSCH2,STUDY_PROGRAM_BOEVWIS2,STUDY_PROGRAM_BOGTNGTTOL,STUDY_PROGRAM_BOTAENG2,STUDY_PROGRAM_BOTAENG2EN,STUDY_PROGRAM_BOTANED2,STUDY_PROGRAM_BTETET,STUDY_PROGRAM_BTIBTB,STUDY_PROGRAM_BTICIC,STUDY_PROGRAM_BTLCCE,STUDY_PROGRAM_BTLCCY,STUDY_PROGRAM_BTLCLS,STUDY_PROGRAM_EOETGTD-NGTC,STUDY_PROGRAM_MOEVBIO,EXAM_TYPE_B,EXAM_TYPE_C,EXAM_TYPE_D,EXAM_TYPE_M,FULL_TIME_PART_D,FULL_TIME_PART_L,FULL_TIME_PART_V,ESTABLISHMENT_LOCATION_AMERSFOORT,ESTABLISHMENT_LOCATION_ONBEKEND,ESTABLISHMENT_LOCATION_UTRECHT,REGISTRATION_STATUS_G,REGISTRATION_STATUS_I,REGISTRATION_STATUS_U,EXAM_ADMINISTERED_B,EXAM_ADMINISTERED_D,EXAM_ADMINISTERED_HN,EXAM_ADMINISTERED_M,EXAM_FINAL_RESULT_MG,EXAM_FINAL_RESULT_absent,EXAM_FINAL_RESULT_passed,PRIOR_VERIFICATION_STATUS_DD,PRIOR_VERIFICATION_STATUS_GD,PRIOR_VERIFICATION_STATUS_GV,PRIOR_VERIFICATION_STATUS_N,NATIONALITY_CHI,NATIONALITY_DUI,NATIONALITY_NIG,NATIONALITY_NL,NATIONALITY_SPA,NATIONALITY_TUR,PRIOR_QUALIFICATION_TYPE_HAVO,PRIOR_QUALIFICATION_TYPE_HBO,PRIOR_QUALIFICATION_TYPE_VWO,PRIOR_EDUCATION_IBG_10040,PRIOR_EDUCATION_IBG_151,PRIOR_EDUCATION_IBG_171,PRIOR_EDUCATION_IBG_172,PRIOR_EDUCATION_IBG_173,PRIOR_EDUCATION_IBG_25132,PRIOR_EDUCATION_IBG_25412,PRIOR_EDUCATION_IBG_25779,PRIOR_EDUCATION_IBG_3,PRIOR_EDUCATION_IBG_370,PRIOR_EDUCATION_IBG_371,PRIOR_EDUCATION_IBG_372,PRIOR_EDUCATION_IBG_373,PRIOR_EDUCATION_IBG_374,PRIOR_EDUCATION_IBG_591,PRIOR_EDUCATION_IBG_601,PRIOR_EDUCATION_IBG_610,PRIOR_EDUCATION_IBG_611,PRIOR_EDUCATION_IBG_741,PRIOR_EDUCATION_IBG_801,PRIOR_EDUCATION_IBG_94130,PRIOR_EDUCATION_IBG_94523,PRIOR_EXAM_YEAR_1999,PRIOR_EXAM_YEAR_2001,PRIOR_EXAM_YEAR_2007,PRIOR_EXAM_YEAR_2009,PRIOR_EXAM_YEAR_2012,PRIOR_EXAM_YEAR_2014,PRIOR_EXAM_YEAR_2015,PRIOR_EXAM_YEAR_2016,PRIOR_EXAM_YEAR_2017,PRIOR_EXAM_YEAR_2018,PRIOR_EXAM_YEAR_2019,PRIOR_EXAM_YEAR_2020,PRIOR_EXAM_YEAR_2021,PRIOR_EXAM_YEAR_2022
0,185667,1,1,0,1,0,0,0,1,0,1,1,33.0,2.0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
1,226491,1,1,0,1,0,0,0,1,1,0,1,30.0,1.0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,255477,1,1,1,1,1,0,0,0,0,0,0,31.0,4.0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,258433,1,1,0,1,0,0,0,1,0,0,1,26.0,6.0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
4,258831,1,1,0,1,0,0,0,1,0,0,0,36.0,5.0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,445479,1,1,0,1,1,0,0,1,0,0,1,47.0,13.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
107,446276,1,1,0,1,1,0,0,1,0,0,1,20.0,13.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,1,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
108,450361,1,1,0,1,1,0,0,1,0,0,1,26.0,19.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
109,450549,1,1,0,1,1,0,0,1,0,0,0,36.0,5.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
110,52971,1,1,0,1,0,0,0,1,1,0,0,41.0,4.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [184]:
# Move the DROPOUT_RISK column to the rightmost position
dropout_risk_col = encoded_data.pop('DROPOUT_RISK')

# Add it back as the last column
encoded_data['DROPOUT_RISK'] = dropout_risk_col

encoded_data

,STUDENT_NUM,ENROLLMENT_TYPE,PRIOR_EDU_STATUS,UPPER_YEAR_STUDENT_REQUEST,FINANCING,STUDY_CHECK_PARTICIPATION,FLEXIBLE_STUDY_PARTICIPATION,FROZEN_STUDENT_STATUS,PRIOR_DIMPLOMA_OBTAINTION,PRIOR_EDUCATION_DESCRIPTION,GENDER,PREFERRED_EDUCATION,STUDENT_AGE,ENROLLMENT_WINDOW,EXAM_BEFORE_ENROLLMENT_STATUS,STUDY_PROGRAM_BACTMU,STUDY_PROGRAM_BAIV,STUDY_PROGRAM_BAMW,STUDY_PROGRAM_BAPA,STUDY_PROGRAM_BAPE,STUDY_PROGRAM_BARE,STUDY_PROGRAM_BASJ,STUDY_PROGRAM_BASW,STUDY_PROGRAM_BGHBCE,STUDY_PROGRAM_BGHBFA,STUDY_PROGRAM_BGHBFY,STUDY_PROGRAM_BGHBHB,STUDY_PROGRAM_BGHBLO,STUDY_PROGRAM_BGHBMH,STUDY_PROGRAM_BGHBZO,STUDY_PROGRAM_BJCB,STUDY_PROGRAM_BJCM,STUDY_PROGRAM_BJDE,STUDY_PROGRAM_BJJO,STUDY_PROGRAM_BMBDK,STUDY_PROGRAM_BMCE,STUDY_PROGRAM_BMFC,STUDY_PROGRAM_BMFTA,STUDY_PROGRAM_BMIBU,STUDY_PROGRAM_BMLM,STUDY_PROGRAM_BMORM,STUDY_PROGRAM_BOEVBIO2,STUDY_PROGRAM_BOEVSCH2,STUDY_PROGRAM_BOEVWIS2,STUDY_PROGRAM_BOGTNGTTOL,STUDY_PROGRAM_BOTAENG2,STUDY_PROGRAM_BOTAENG2EN,STUDY_PROGRAM_BOTANED2,STUDY_PROGRAM_BTETET,STUDY_PROGRAM_BTIBTB,STUDY_PROGRAM_BTICIC,STUDY_PROGRAM_BTLCCE,STUDY_PROGRAM_BTLCCY,STUDY_PROGRAM_BTLCLS,STUDY_PROGRAM_EOETGTD-NGTC,STUDY_PROGRAM_MOEVBIO,EXAM_TYPE_B,EXAM_TYPE_C,EXAM_TYPE_D,EXAM_TYPE_M,FULL_TIME_PART_D,FULL_TIME_PART_L,FULL_TIME_PART_V,ESTABLISHMENT_LOCATION_AMERSFOORT,ESTABLISHMENT_LOCATION_ONBEKEND,ESTABLISHMENT_LOCATION_UTRECHT,REGISTRATION_STATUS_G,REGISTRATION_STATUS_I,REGISTRATION_STATUS_U,EXAM_ADMINISTERED_B,EXAM_ADMINISTERED_D,EXAM_ADMINISTERED_HN,EXAM_ADMINISTERED_M,EXAM_FINAL_RESULT_MG,EXAM_FINAL_RESULT_absent,EXAM_FINAL_RESULT_passed,PRIOR_VERIFICATION_STATUS_DD,PRIOR_VERIFICATION_STATUS_GD,PRIOR_VERIFICATION_STATUS_GV,PRIOR_VERIFICATION_STATUS_N,NATIONALITY_CHI,NATIONALITY_DUI,NATIONALITY_NIG,NATIONALITY_NL,NATIONALITY_SPA,NATIONALITY_TUR,PRIOR_QUALIFICATION_TYPE_HAVO,PRIOR_QUALIFICATION_TYPE_HBO,PRIOR_QUALIFICATION_TYPE_VWO,PRIOR_EDUCATION_IBG_10040,PRIOR_EDUCATION_IBG_151,PRIOR_EDUCATION_IBG_171,PRIOR_EDUCATION_IBG_172,PRIOR_EDUCATION_IBG_173,PRIOR_EDUCATION_IBG_25132,PRIOR_EDUCATION_IBG_25412,PRIOR_EDUCATION_IBG_25779,PRIOR_EDUCATION_IBG_3,PRIOR_EDUCATION_IBG_370,PRIOR_EDUCATION_IBG_371,PRIOR_EDUCATION_IBG_372,PRIOR_EDUCATION_IBG_373,PRIOR_EDUCATION_IBG_374,PRIOR_EDUCATION_IBG_591,PRIOR_EDUCATION_IBG_601,PRIOR_EDUCATION_IBG_610,PRIOR_EDUCATION_IBG_611,PRIOR_EDUCATION_IBG_741,PRIOR_EDUCATION_IBG_801,PRIOR_EDUCATION_IBG_94130,PRIOR_EDUCATION_IBG_94523,PRIOR_EXAM_YEAR_1999,PRIOR_EXAM_YEAR_2001,PRIOR_EXAM_YEAR_2007,PRIOR_EXAM_YEAR_2009,PRIOR_EXAM_YEAR_2012,PRIOR_EXAM_YEAR_2014,PRIOR_EXAM_YEAR_2015,PRIOR_EXAM_YEAR_2016,PRIOR_EXAM_YEAR_2017,PRIOR_EXAM_YEAR_2018,PRIOR_EXAM_YEAR_2019,PRIOR_EXAM_YEAR_2020,PRIOR_EXAM_YEAR_2021,PRIOR_EXAM_YEAR_2022,DROPOUT_RISK
0,185667,1,1,0,1,0,0,0,1,0,1,1,33.0,2.0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
1,226491,1,1,0,1,0,0,0,1,1,0,1,30.0,1.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
2,255477,1,1,1,1,1,0,0,0,0,0,0,31.0,4.0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
3,258433,1,1,0,1,0,0,0,1,0,0,1,26.0,6.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
4,258831,1,1,0,1,0,0,0,1,0,0,0,36.0,5.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,445479,1,1,0,1,1,0,0,1,0,0,1,47.0,13.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
107,446276,1,1,0,1,1,0,0,1,0,0,1,20.0,13.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,1,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
108,450361,1,1,0,1,1,0,0,1,0,0,1,26.0,19.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
109,450549,1,1,0,1,1,0,0,1,0,0,0,36.0,5.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
110,52971,1,1,0,1,0,0,0,1,1,0,0,41.0,4.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1