In [232]:
import pandas as pd
import numpy as np
import seaborn as sns
from functools import reduce
import os
import warnings
warnings.filterwarnings('ignore')
pd.options.display.max_columns = None
from IPython.display import display

In [233]:
# Load the Excel file
file_path = '../data/raw/ODS Osiris basistabellen Inschrijving etc.xlsx'
data = pd.read_excel(file_path, sheet_name=None)

# Print the names of all sheets
print("Sheet names:", data.keys())

# Display the first few rows of each sheet
for sheet_name, sheet_data in data.items():
    print(f"---{sheet_name}---")
    print(sheet_data.head())

Sheet names: dict_keys(['vooraf', 'ODS.OSS_STUDENT_INSCHRIJFHIST', 'ODS.OSS_STUDENT_EXAMEN', 'ODS.OSS_STUDENT_VOOROPLEIDING', 'ODS.OSS_VOOROPLEIDING', 'ODS.OSS_STUDENT'])
---vooraf---
                                          Unnamed: 0
0  In de feit-tabel (op basis van stroom- en stat...
1  beperkt tot alleen maar bachelor-studenten (ge...
2           Wel/geen P, geslaagd/gestaakt/nog actief
3  geen dubbele inschrijvingen voor meer dan één ...
4                                                NaN
---ODS.OSS_STUDENT_INSCHRIJFHIST---
   STUDENTNUMMER OPLEIDING HOOFD_OPLEIDING  COLLEGEJAAR  \
0        1699140      BJDE            BJDE         2016
1        1699140      BJDE            BJDE         2017
2        1699140      BJDE            BJDE         2017
3        1699140      BJDE            BJDE         2018
4        1699140      BJDE            BJDE         2019

                  INGANGSDATUM                  AFLOOPDATUM  \
0  2016-09-01 00:00:00.0000000  2017-08-31 00:00:00.0000000
1  2017-09-01 00:00:00.0000000  2017-12-20 00:00:00.0000000
2  2017-12-21 00:00:00.0000000  2018-08-31 00:00:00.0000000
3  2018-09-01 00:00:00.0000000  2019-08-31 00:00:00.0000000
4  2019-09-01 00:00:00.0000000  2020-08-31 00:00:00.0000000

  SOORT_INSCHRIJVING_FAC EXAMENTYPE_CSA VOLTIJD_DEELTIJD  \
0                      S              D                V
1                      S              D                V
2                      S              B                V
3                      S              B                V
4                      S              B                V

   ACTIEFCODE_OPLEIDING_CSA      MUTATIEDATUM_ACTIEFCODE  \
0                         4  2016-08-27 00:00:00.0000000
1                         4  2017-08-10 12:17:45.0000000
2                         4  2018-02-08 10:05:39.0000000
3                         4  2018-08-20 14:08:44.0000000
4                         4  2019-07-31 12:41:10.0000000

  INTREKKING_VOORAANMELDING BEEINDIGINGSREDEN  CROHO  \
0                       NaN               NaN  34092
1                       NaN         PROP_EXAM  34092
2                       NaN               NaN  34092
3                       NaN               NaN  34092
4                       NaN               NaN  34092

     DATUM_BEWIJS_INSCHRIJVING         DATUM_VERZOEK_INSCHR LOTINGVORM  \
0  2016-08-29 00:00:00.0000000  2016-03-01 00:00:00.0000000          C
1  2017-08-14 00:00:00.0000000  2017-07-29 00:00:00.0000000          N
2  2017-08-14 00:00:00.0000000  2018-02-08 10:05:39.0000000        NaN
3  2018-08-23 00:00:00.0000000  2018-08-05 00:00:00.0000000          N
4  2019-08-06 00:00:00.0000000  2019-06-10 00:00:00.0000000          N

  DECENTRALE_SELECTIE_RESULTAAT  DECENTRALE_SELECTIE_VOLGNUMMER  \
0                             S                           295.0
1                           NaN                             NaN
2                           NaN                             NaN
3                           NaN                             NaN
4                           NaN                             NaN

  LOTINGRESULTAAT  LOTING_REDEN_VOORBEHOUD LOTING_IBG_STATUS  \
0               I                      NaN                 V
1             NaN                      NaN               NaN
2             NaN                      NaN               NaN
3             NaN                      NaN               NaN
4             NaN                      NaN               NaN

   LOTING_REDEN_AFKEUR DATUM_VERZOEK_STOPPEN BEKOSTIGING  \
0                  NaN                   NaN           J
1                  NaN                   NaN           J
2                  NaN                   NaN           J
3                  NaN                   NaN           J
4                  NaN                   NaN           J

   DATUM_EERSTE_INSCHR_VERZ_HO DEELNAME_STUDIEKEUZECHECK  \
0  2016-03-01 00:00:00.0000000                       NVT
1                          NaN                       NVT
2                          NaN                       NVT
3                          NaN                       NVT
4                          NaN                       NVT

  DATUM_STUDIEKEUZECHECK RESULT_STUDIEKEUZECHECK TOELAATB_STUDIEKEUZECHECK
0                    NaN                     NaN                       NaN
1                    NaN                     NaN                       NaN
2                    NaN                     NaN                       NaN
3                    NaN                     NaN                       NaN
4                    NaN                     NaN                       NaN
---ODS.OSS_STUDENT_EXAMEN---
   STUDENTNUMMER  OPLEIDING EXAMENTYPE AANVANGSDATUM EXAMENPROGRAMMA  \
0        1699140       BJDE          D    2016-09-01       JDE-DV-16
1        1699140       BJDE          B    2017-09-01       JDE-BV-17
2        1764427  BOPAPABOV          D    2019-09-01      OTVP-DT-19
3        1765243     BGHBFY          B    2020-02-01     G-EXTERN-17
4        1766090       BMLM          D    2019-09-01      MBLM-DV-19

  EXAMENDATUM JUDICIUM EERSTE_GRAAD DEELNAME_HONOURS
0  2017-12-20      ---            N                N
1  2022-02-01      ---            J                N
2         NaT      NaN            J                N
3         NaT      NaN            J                N
4  2020-06-30      ---            N                N
---ODS.OSS_STUDENT_VOOROPLEIDING---
   STUDENTNUMMER VOOROPLEIDING  \
0        1699140           379
1        1699140           591
2        1699140           611
3        1724686         93212
4        1764427           361

                                         SCHOOL_NAAM EINDEXAMENDATUM  \
0  Gereformeerde Scholengemeenschap Randstad Gymn...      2016-06-16
1                                 Hogeschool Utrecht      2022-02-01
2                                 Hogeschool Utrecht      2017-12-20
3                     Stichting ROC Midden Nederland      2013-09-30
4  Scholengemeenschap voor Voortgezet Vrije Schoo...      1988-06-10

  DIPLOMA_BEHAALD  EXTENSIE_CODE                          EXTENSIE_NAAM  \
0               J            NaN                                    NaN
1               J        34092.0  B Communication and Multimedia Design
2               J        34092.0  B Communication and Multimedia Design
3               J            NaN                                    NaN
4               J            NaN                                    NaN

  STATUS_VERIFICATIE DATUM_VERIFICATIE
0                 GD        2016-06-16
1                 GD        2022-02-01
2                 GD        2017-12-20
3                 GD        2013-09-30
4                 DD        2019-05-10
---ODS.OSS_VOOROPLEIDING---
  VOOROPLEIDING                     NAAM TYPE_VOOROPLEIDING  \
0             3          VWO certificaat             OVERIG
1           179   VWO NIEUW (E+M EN C+M)                VWO
2           361                      VWO                VWO
3           371         HAVO NIEUW (N+G)               HAVO
4           379  HAVO NIEUW (E+M EN C+M)               HAVO

     TYPV_OMSCHRIJVING_NLS ACTUEEL
0  Overige vooropleidingen       N
1                VWO + gym       J
2                VWO + gym       J
3                     HAVO       J
4                     HAVO       J
---ODS.OSS_STUDENT---
   STUDENTNUMMER GEBOORTEDATUM GESLACHT NATIONALITEIT  AANVANGSJAAR_UU_STUDENT
0        1699140    1999-10-08        V            NL                     2016
1        1724686    1990-12-17        V            NL                     2017
2        1764427    1968-07-30        V            NL                     2019
3        1765243    1999-02-23        V            NL                     2019
4        1766090    2000-03-08        M            NL                     2019

In [234]:
# Path to your Excel file
file_path = '../data/raw/ODS Osiris basistabellen Inschrijving etc.xlsx'

# Load the Excel file, excluding the 'vooraf' sheet
excel_data = pd.ExcelFile(file_path)
sheet_names = excel_data.sheet_names

# Remove 'vooraf' from the list of sheet names
if 'vooraf' in sheet_names:
    sheet_names.remove('vooraf')

# Load each sheet into a DataFrame, using the sheet name as the key
dataframes = {}
for sheet_name in sheet_names:
    dataframes[sheet_name] = pd.read_excel(file_path, sheet_name=sheet_name)
    print(f"Loaded {sheet_name} with {len(dataframes[sheet_name])} rows.")
    # Display the DataFrame using IPython's display function
    print(f"Displaying first few rows of {sheet_name}:")
    display(dataframes[sheet_name].head())

# Optionally, you can display a specific DataFrame in a nicer format whenever needed
# Example: Accessing and displaying the 'ODS.OSS_STUDENT_INSCHRIJFHIST' DataFrame
print("Detailed view of 'ODS.OSS_STUDENT_INSCHRIJFHIST':")
display(dataframes['ODS.OSS_STUDENT_INSCHRIJFHIST'].head())

Loaded ODS.OSS_STUDENT_INSCHRIJFHIST with 37 rows.
Displaying first few rows of ODS.OSS_STUDENT_INSCHRIJFHIST:

,STUDENTNUMMER,OPLEIDING,HOOFD_OPLEIDING,COLLEGEJAAR,INGANGSDATUM,AFLOOPDATUM,SOORT_INSCHRIJVING_FAC,EXAMENTYPE_CSA,VOLTIJD_DEELTIJD,ACTIEFCODE_OPLEIDING_CSA,MUTATIEDATUM_ACTIEFCODE,INTREKKING_VOORAANMELDING,BEEINDIGINGSREDEN,CROHO,DATUM_BEWIJS_INSCHRIJVING,DATUM_VERZOEK_INSCHR,LOTINGVORM,DECENTRALE_SELECTIE_RESULTAAT,DECENTRALE_SELECTIE_VOLGNUMMER,LOTINGRESULTAAT,LOTING_REDEN_VOORBEHOUD,LOTING_IBG_STATUS,LOTING_REDEN_AFKEUR,DATUM_VERZOEK_STOPPEN,BEKOSTIGING,DATUM_EERSTE_INSCHR_VERZ_HO,DEELNAME_STUDIEKEUZECHECK,DATUM_STUDIEKEUZECHECK,RESULT_STUDIEKEUZECHECK,TOELAATB_STUDIEKEUZECHECK
0,1699140,BJDE,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,4,2016-08-27 00:00:00.0000000,NaN,NaN,34092,2016-08-29 00:00:00.0000000,2016-03-01 00:00:00.0000000,C,S,295.0,I,NaN,V,NaN,NaN,J,2016-03-01 00:00:00.0000000,NVT,NaN,NaN,NaN
1,1699140,BJDE,BJDE,2017,2017-09-01 00:00:00.0000000,2017-12-20 00:00:00.0000000,S,D,V,4,2017-08-10 12:17:45.0000000,NaN,PROP_EXAM,34092,2017-08-14 00:00:00.0000000,2017-07-29 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN
2,1699140,BJDE,BJDE,2017,2017-12-21 00:00:00.0000000,2018-08-31 00:00:00.0000000,S,B,V,4,2018-02-08 10:05:39.0000000,NaN,NaN,34092,2017-08-14 00:00:00.0000000,2018-02-08 10:05:39.0000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN
3,1699140,BJDE,BJDE,2018,2018-09-01 00:00:00.0000000,2019-08-31 00:00:00.0000000,S,B,V,4,2018-08-20 14:08:44.0000000,NaN,NaN,34092,2018-08-23 00:00:00.0000000,2018-08-05 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN
4,1699140,BJDE,BJDE,2019,2019-09-01 00:00:00.0000000,2020-08-31 00:00:00.0000000,S,B,V,4,2019-07-31 12:41:10.0000000,NaN,NaN,34092,2019-08-06 00:00:00.0000000,2019-06-10 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN

Loaded ODS.OSS_STUDENT_EXAMEN with 12 rows.
Displaying first few rows of ODS.OSS_STUDENT_EXAMEN:

,STUDENTNUMMER,OPLEIDING,EXAMENTYPE,AANVANGSDATUM,EXAMENPROGRAMMA,EXAMENDATUM,JUDICIUM,EERSTE_GRAAD,DEELNAME_HONOURS
0,1699140,BJDE,D,2016-09-01,JDE-DV-16,2017-12-20,---,N,N
1,1699140,BJDE,B,2017-09-01,JDE-BV-17,2022-02-01,---,J,N
2,1764427,BOPAPABOV,D,2019-09-01,OTVP-DT-19,NaT,NaN,J,N
3,1765243,BGHBFY,B,2020-02-01,G-EXTERN-17,NaT,NaN,J,N
4,1766090,BMLM,D,2019-09-01,MBLM-DV-19,2020-06-30,---,N,N

Loaded ODS.OSS_STUDENT_VOOROPLEIDING with 25 rows.
Displaying first few rows of ODS.OSS_STUDENT_VOOROPLEIDING:

,STUDENTNUMMER,VOOROPLEIDING,SCHOOL_NAAM,EINDEXAMENDATUM,DIPLOMA_BEHAALD,EXTENSIE_CODE,EXTENSIE_NAAM,STATUS_VERIFICATIE,DATUM_VERIFICATIE
0,1699140,379,Gereformeerde Scholengemeenschap Randstad Gymn...,2016-06-16,J,NaN,NaN,GD,2016-06-16
1,1699140,591,Hogeschool Utrecht,2022-02-01,J,34092.0,B Communication and Multimedia Design,GD,2022-02-01
2,1699140,611,Hogeschool Utrecht,2017-12-20,J,34092.0,B Communication and Multimedia Design,GD,2017-12-20
3,1724686,93212,Stichting ROC Midden Nederland,2013-09-30,J,NaN,NaN,GD,2013-09-30
4,1764427,361,Scholengemeenschap voor Voortgezet Vrije Schoo...,1988-06-10,J,NaN,NaN,DD,2019-05-10

Loaded ODS.OSS_VOOROPLEIDING with 14 rows.
Displaying first few rows of ODS.OSS_VOOROPLEIDING:

,VOOROPLEIDING,NAAM,TYPE_VOOROPLEIDING,TYPV_OMSCHRIJVING_NLS,ACTUEEL
0,3,VWO certificaat,OVERIG,Overige vooropleidingen,N
1,179,VWO NIEUW (E+M EN C+M),VWO,VWO + gym,J
2,361,VWO,VWO,VWO + gym,J
3,371,HAVO NIEUW (N+G),HAVO,HAVO,J
4,379,HAVO NIEUW (E+M EN C+M),HAVO,HAVO,J

Loaded ODS.OSS_STUDENT with 8 rows.
Displaying first few rows of ODS.OSS_STUDENT:

   STUDENTNUMMER GEBOORTEDATUM GESLACHT NATIONALITEIT  AANVANGSJAAR_UU_STUDENT
0        1699140    1999-10-08        V            NL                     2016
1        1724686    1990-12-17        V            NL                     2017
2        1764427    1968-07-30        V            NL                     2019
3        1765243    1999-02-23        V            NL                     2019
4        1766090    2000-03-08        M            NL                     2019

Detailed view of 'ODS.OSS_STUDENT_INSCHRIJFHIST':

,STUDENTNUMMER,OPLEIDING,HOOFD_OPLEIDING,COLLEGEJAAR,INGANGSDATUM,AFLOOPDATUM,SOORT_INSCHRIJVING_FAC,EXAMENTYPE_CSA,VOLTIJD_DEELTIJD,ACTIEFCODE_OPLEIDING_CSA,MUTATIEDATUM_ACTIEFCODE,INTREKKING_VOORAANMELDING,BEEINDIGINGSREDEN,CROHO,DATUM_BEWIJS_INSCHRIJVING,DATUM_VERZOEK_INSCHR,LOTINGVORM,DECENTRALE_SELECTIE_RESULTAAT,DECENTRALE_SELECTIE_VOLGNUMMER,LOTINGRESULTAAT,LOTING_REDEN_VOORBEHOUD,LOTING_IBG_STATUS,LOTING_REDEN_AFKEUR,DATUM_VERZOEK_STOPPEN,BEKOSTIGING,DATUM_EERSTE_INSCHR_VERZ_HO,DEELNAME_STUDIEKEUZECHECK,DATUM_STUDIEKEUZECHECK,RESULT_STUDIEKEUZECHECK,TOELAATB_STUDIEKEUZECHECK
0,1699140,BJDE,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,4,2016-08-27 00:00:00.0000000,NaN,NaN,34092,2016-08-29 00:00:00.0000000,2016-03-01 00:00:00.0000000,C,S,295.0,I,NaN,V,NaN,NaN,J,2016-03-01 00:00:00.0000000,NVT,NaN,NaN,NaN
1,1699140,BJDE,BJDE,2017,2017-09-01 00:00:00.0000000,2017-12-20 00:00:00.0000000,S,D,V,4,2017-08-10 12:17:45.0000000,NaN,PROP_EXAM,34092,2017-08-14 00:00:00.0000000,2017-07-29 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN
2,1699140,BJDE,BJDE,2017,2017-12-21 00:00:00.0000000,2018-08-31 00:00:00.0000000,S,B,V,4,2018-02-08 10:05:39.0000000,NaN,NaN,34092,2017-08-14 00:00:00.0000000,2018-02-08 10:05:39.0000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN
3,1699140,BJDE,BJDE,2018,2018-09-01 00:00:00.0000000,2019-08-31 00:00:00.0000000,S,B,V,4,2018-08-20 14:08:44.0000000,NaN,NaN,34092,2018-08-23 00:00:00.0000000,2018-08-05 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN
4,1699140,BJDE,BJDE,2019,2019-09-01 00:00:00.0000000,2020-08-31 00:00:00.0000000,S,B,V,4,2019-07-31 12:41:10.0000000,NaN,NaN,34092,2019-08-06 00:00:00.0000000,2019-06-10 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN

In [235]:
# Path to your Excel file
file_path = '../data/raw/ODS Osiris basistabellen Inschrijving etc.xlsx'

# Load the Excel file, excluding the 'vooraf' sheet
excel_data = pd.ExcelFile(file_path)
sheet_names = excel_data.sheet_names

# Remove 'vooraf' from the list of sheet names
if 'vooraf' in sheet_names:
    sheet_names.remove('vooraf')

# Loop through sheet names and assign each DataFrame to a variable
for i, sheet_name in enumerate(sheet_names):
    df_name = f'df{i + 1}'  # Create a variable name like df1, df2, etc.
    globals()[df_name] = pd.read_excel(file_path, sheet_name=sheet_name)  # Load each sheet into a DataFrame

# Display the first 5 rows of each DataFrame to verify
for i in range(1, len(sheet_names) + 1):
    df_name = f'df{i}'
    print(f"DataFrame: {df_name}")
    display(globals()[df_name].head(5))

DataFrame: df1

,STUDENTNUMMER,OPLEIDING,HOOFD_OPLEIDING,COLLEGEJAAR,INGANGSDATUM,AFLOOPDATUM,SOORT_INSCHRIJVING_FAC,EXAMENTYPE_CSA,VOLTIJD_DEELTIJD,ACTIEFCODE_OPLEIDING_CSA,MUTATIEDATUM_ACTIEFCODE,INTREKKING_VOORAANMELDING,BEEINDIGINGSREDEN,CROHO,DATUM_BEWIJS_INSCHRIJVING,DATUM_VERZOEK_INSCHR,LOTINGVORM,DECENTRALE_SELECTIE_RESULTAAT,DECENTRALE_SELECTIE_VOLGNUMMER,LOTINGRESULTAAT,LOTING_REDEN_VOORBEHOUD,LOTING_IBG_STATUS,LOTING_REDEN_AFKEUR,DATUM_VERZOEK_STOPPEN,BEKOSTIGING,DATUM_EERSTE_INSCHR_VERZ_HO,DEELNAME_STUDIEKEUZECHECK,DATUM_STUDIEKEUZECHECK,RESULT_STUDIEKEUZECHECK,TOELAATB_STUDIEKEUZECHECK
0,1699140,BJDE,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,4,2016-08-27 00:00:00.0000000,NaN,NaN,34092,2016-08-29 00:00:00.0000000,2016-03-01 00:00:00.0000000,C,S,295.0,I,NaN,V,NaN,NaN,J,2016-03-01 00:00:00.0000000,NVT,NaN,NaN,NaN
1,1699140,BJDE,BJDE,2017,2017-09-01 00:00:00.0000000,2017-12-20 00:00:00.0000000,S,D,V,4,2017-08-10 12:17:45.0000000,NaN,PROP_EXAM,34092,2017-08-14 00:00:00.0000000,2017-07-29 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN
2,1699140,BJDE,BJDE,2017,2017-12-21 00:00:00.0000000,2018-08-31 00:00:00.0000000,S,B,V,4,2018-02-08 10:05:39.0000000,NaN,NaN,34092,2017-08-14 00:00:00.0000000,2018-02-08 10:05:39.0000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN
3,1699140,BJDE,BJDE,2018,2018-09-01 00:00:00.0000000,2019-08-31 00:00:00.0000000,S,B,V,4,2018-08-20 14:08:44.0000000,NaN,NaN,34092,2018-08-23 00:00:00.0000000,2018-08-05 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN
4,1699140,BJDE,BJDE,2019,2019-09-01 00:00:00.0000000,2020-08-31 00:00:00.0000000,S,B,V,4,2019-07-31 12:41:10.0000000,NaN,NaN,34092,2019-08-06 00:00:00.0000000,2019-06-10 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN

DataFrame: df2

,STUDENTNUMMER,OPLEIDING,EXAMENTYPE,AANVANGSDATUM,EXAMENPROGRAMMA,EXAMENDATUM,JUDICIUM,EERSTE_GRAAD,DEELNAME_HONOURS
0,1699140,BJDE,D,2016-09-01,JDE-DV-16,2017-12-20,---,N,N
1,1699140,BJDE,B,2017-09-01,JDE-BV-17,2022-02-01,---,J,N
2,1764427,BOPAPABOV,D,2019-09-01,OTVP-DT-19,NaT,NaN,J,N
3,1765243,BGHBFY,B,2020-02-01,G-EXTERN-17,NaT,NaN,J,N
4,1766090,BMLM,D,2019-09-01,MBLM-DV-19,2020-06-30,---,N,N

DataFrame: df3

,STUDENTNUMMER,VOOROPLEIDING,SCHOOL_NAAM,EINDEXAMENDATUM,DIPLOMA_BEHAALD,EXTENSIE_CODE,EXTENSIE_NAAM,STATUS_VERIFICATIE,DATUM_VERIFICATIE
0,1699140,379,Gereformeerde Scholengemeenschap Randstad Gymn...,2016-06-16,J,NaN,NaN,GD,2016-06-16
1,1699140,591,Hogeschool Utrecht,2022-02-01,J,34092.0,B Communication and Multimedia Design,GD,2022-02-01
2,1699140,611,Hogeschool Utrecht,2017-12-20,J,34092.0,B Communication and Multimedia Design,GD,2017-12-20
3,1724686,93212,Stichting ROC Midden Nederland,2013-09-30,J,NaN,NaN,GD,2013-09-30
4,1764427,361,Scholengemeenschap voor Voortgezet Vrije Schoo...,1988-06-10,J,NaN,NaN,DD,2019-05-10

DataFrame: df4

,VOOROPLEIDING,NAAM,TYPE_VOOROPLEIDING,TYPV_OMSCHRIJVING_NLS,ACTUEEL
0,3,VWO certificaat,OVERIG,Overige vooropleidingen,N
1,179,VWO NIEUW (E+M EN C+M),VWO,VWO + gym,J
2,361,VWO,VWO,VWO + gym,J
3,371,HAVO NIEUW (N+G),HAVO,HAVO,J
4,379,HAVO NIEUW (E+M EN C+M),HAVO,HAVO,J

DataFrame: df5

   STUDENTNUMMER GEBOORTEDATUM GESLACHT NATIONALITEIT  AANVANGSJAAR_UU_STUDENT
0        1699140    1999-10-08        V            NL                     2016
1        1724686    1990-12-17        V            NL                     2017
2        1764427    1968-07-30        V            NL                     2019
3        1765243    1999-02-23        V            NL                     2019
4        1766090    2000-03-08        M            NL                     2019

# Clean each dataframe (df1, df2, df3, df4 and df5) individually and make sure each is correct. Then combine them at the end and check again.

# df1

In [236]:
df1.columns

Index(['STUDENTNUMMER', 'OPLEIDING', 'HOOFD_OPLEIDING', 'COLLEGEJAAR',
       'INGANGSDATUM', 'AFLOOPDATUM', 'SOORT_INSCHRIJVING_FAC',
       'EXAMENTYPE_CSA', 'VOLTIJD_DEELTIJD', 'ACTIEFCODE_OPLEIDING_CSA',
       'MUTATIEDATUM_ACTIEFCODE', 'INTREKKING_VOORAANMELDING',
       'BEEINDIGINGSREDEN', 'CROHO', 'DATUM_BEWIJS_INSCHRIJVING',
       'DATUM_VERZOEK_INSCHR', 'LOTINGVORM', 'DECENTRALE_SELECTIE_RESULTAAT',
       'DECENTRALE_SELECTIE_VOLGNUMMER', 'LOTINGRESULTAAT',
       'LOTING_REDEN_VOORBEHOUD', 'LOTING_IBG_STATUS', 'LOTING_REDEN_AFKEUR',
       'DATUM_VERZOEK_STOPPEN', 'BEKOSTIGING', 'DATUM_EERSTE_INSCHR_VERZ_HO',
       'DEELNAME_STUDIEKEUZECHECK', 'DATUM_STUDIEKEUZECHECK',
       'RESULT_STUDIEKEUZECHECK', 'TOELAATB_STUDIEKEUZECHECK'],
      dtype='object')

In [237]:
# renaming columns for df1
df1_rename_mapping = {
    'STUDENTNUMMER': 'STUDENT_NUM',
    'OPLEIDING': 'STUDY_PROGRAM',
    'HOOFD_OPLEIDING': 'MAIN_STUDY_PROGRAM',
    'COLLEGEJAAR': 'ACADEMIC_YEAR',
    'INGANGSDATUM': 'START_DATE',
    'AFLOOPDATUM': 'END_DATE',
    'SOORT_INSCHRIJVING_FAC': 'ENROLLMENT_TYPE',
    'EXAMENTYPE_CSA': 'EXAM_TYPE',
    'VOLTIJD_DEELTIJD': 'FULL_TIME_PART',
    'ACTIEFCODE_OPLEIDING_CSA': 'PROGRAM_ACTIVE_CODE',
    'MUTATIEDATUM_ACTIEFCODE': 'DATE_ACTIVE_CODE_MODIFIED',
    'INTREKKING_VOORAANMELDING': 'DATE_WITHRAWAL_PRE-REGIS',
    'BEEINDIGINGSREDEN': 'WITHDRAWAL_REASON',
    'CROHO': 'HIGHER_EDU_REGISTER',
    'DATUM_BEWIJS_INSCHRIJVING': 'DATE_REGIS_PROOF',
    'DATUM_VERZOEK_INSCHR': 'DATE_ENROLLMENT_REQUEST',
    'LOTINGVORM': 'LOTTERY_FORM',
    'DECENTRALE_SELECTIE_RESULTAAT': 'DECENTRALIZED_RESULT_SELECTION',
    'DECENTRALE_SELECTIE_VOLGNUMMER': 'DECENTRALIZED_SELECTION_FOLLOWUP',
    'LOTINGRESULTAAT': 'LOTTERY_RESULT',
    'LOTING_REDEN_VOORBEHOUD': 'LOTTERY_RESERVATION_REASON',
    'LOTING_IBG_STATUS': 'LOTTERY_STATUS',
    'LOTING_REDEN_AFKEUR': 'LOTTERY_REJECTION_REASON',
    'DATUM_VERZOEK_STOPPEN': 'DATE_REQUEST_STOP',
    'BEKOSTIGING': 'FINANCING',
    'DATUM_EERSTE_INSCHR_VERZ_HO': 'DATE_FIRST_ENROL_REQUEST',
    'DEELNAME_STUDIEKEUZECHECK': 'STUDY_CHECK_PARTICIPATION',
    'DATUM_STUDIEKEUZECHECK': 'DATE_STUDY_CHECK',
    'RESULT_STUDIEKEUZECHECK': 'STUDY_CHECK_RESULT',
    'TOELAATB_STUDIEKEUZECHECK': 'STUDY_CHECK_ADMISSION'
    }

# Rename columns
df1.rename(columns=df1_rename_mapping, inplace=True)
# Create a list of the new column names
new_columns = list(df1_rename_mapping.values())
# Keep only the renamed columns and drop the rest, this is because we want to avoid the problem of a new column added in the database renders the tool not working. 
# A randomly added column is not cleaned and we should be notified of this to properly clean and add the new column.
df1 = df1[new_columns]

In [238]:
df1.columns

Index(['STUDENT_NUM', 'STUDY_PROGRAM', 'MAIN_STUDY_PROGRAM', 'ACADEMIC_YEAR',
       'START_DATE', 'END_DATE', 'ENROLLMENT_TYPE', 'EXAM_TYPE',
       'FULL_TIME_PART', 'PROGRAM_ACTIVE_CODE', 'DATE_ACTIVE_CODE_MODIFIED',
       'DATE_WITHRAWAL_PRE-REGIS', 'WITHDRAWAL_REASON', 'HIGHER_EDU_REGISTER',
       'DATE_REGIS_PROOF', 'DATE_ENROLLMENT_REQUEST', 'LOTTERY_FORM',
       'DECENTRALIZED_RESULT_SELECTION', 'DECENTRALIZED_SELECTION_FOLLOWUP',
       'LOTTERY_RESULT', 'LOTTERY_RESERVATION_REASON', 'LOTTERY_STATUS',
       'LOTTERY_REJECTION_REASON', 'DATE_REQUEST_STOP', 'FINANCING',
       'DATE_FIRST_ENROL_REQUEST', 'STUDY_CHECK_PARTICIPATION',
       'DATE_STUDY_CHECK', 'STUDY_CHECK_RESULT', 'STUDY_CHECK_ADMISSION'],
      dtype='object')

In [239]:
df1.head(10)

,STUDENT_NUM,STUDY_PROGRAM,MAIN_STUDY_PROGRAM,ACADEMIC_YEAR,START_DATE,END_DATE,ENROLLMENT_TYPE,EXAM_TYPE,FULL_TIME_PART,PROGRAM_ACTIVE_CODE,DATE_ACTIVE_CODE_MODIFIED,DATE_WITHRAWAL_PRE-REGIS,WITHDRAWAL_REASON,HIGHER_EDU_REGISTER,DATE_REGIS_PROOF,DATE_ENROLLMENT_REQUEST,LOTTERY_FORM,DECENTRALIZED_RESULT_SELECTION,DECENTRALIZED_SELECTION_FOLLOWUP,LOTTERY_RESULT,LOTTERY_RESERVATION_REASON,LOTTERY_STATUS,LOTTERY_REJECTION_REASON,DATE_REQUEST_STOP,FINANCING,DATE_FIRST_ENROL_REQUEST,STUDY_CHECK_PARTICIPATION,DATE_STUDY_CHECK,STUDY_CHECK_RESULT,STUDY_CHECK_ADMISSION
0,1699140,BJDE,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,4,2016-08-27 00:00:00.0000000,NaN,NaN,34092,2016-08-29 00:00:00.0000000,2016-03-01 00:00:00.0000000,C,S,295.0,I,NaN,V,NaN,NaN,J,2016-03-01 00:00:00.0000000,NVT,NaN,NaN,NaN
1,1699140,BJDE,BJDE,2017,2017-09-01 00:00:00.0000000,2017-12-20 00:00:00.0000000,S,D,V,4,2017-08-10 12:17:45.0000000,NaN,PROP_EXAM,34092,2017-08-14 00:00:00.0000000,2017-07-29 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN
2,1699140,BJDE,BJDE,2017,2017-12-21 00:00:00.0000000,2018-08-31 00:00:00.0000000,S,B,V,4,2018-02-08 10:05:39.0000000,NaN,NaN,34092,2017-08-14 00:00:00.0000000,2018-02-08 10:05:39.0000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN
3,1699140,BJDE,BJDE,2018,2018-09-01 00:00:00.0000000,2019-08-31 00:00:00.0000000,S,B,V,4,2018-08-20 14:08:44.0000000,NaN,NaN,34092,2018-08-23 00:00:00.0000000,2018-08-05 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN
4,1699140,BJDE,BJDE,2019,2019-09-01 00:00:00.0000000,2020-08-31 00:00:00.0000000,S,B,V,4,2019-07-31 12:41:10.0000000,NaN,NaN,34092,2019-08-06 00:00:00.0000000,2019-06-10 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN
5,1699140,BJDE,BJDE,2020,2020-09-01 00:00:00.0000000,2021-08-31 00:00:00.0000000,S,B,V,4,2020-08-30 17:20:20.0000000,NaN,NaN,34092,2020-09-01 00:00:00.0000000,2020-08-27 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN
6,1699140,BJDE,BJDE,2021,2021-09-01 00:00:00.0000000,2022-08-31 00:00:00.0000000,S,B,V,4,2021-08-12 15:50:56.0000000,NaN,NaN,34092,2021-08-17 00:00:00.0000000,2021-08-12 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN
7,1699140,BJSCICM,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,0,2016-04-28 14:54:22.0000000,2016-06-02 00:00:00.0000000,NaN,34430,NaN,2016-04-28 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,2016-03-01 00:00:00.0000000,J,2016-06-02 00:00:00.0000000,ND,NN
8,1724686,BGHBFA,BGHBFA,2017,2017-09-01 00:00:00.0000000,2018-08-31 00:00:00.0000000,S,D,V,0,2017-04-24 14:58:47.0000000,2017-08-12 00:00:00.0000000,NaN,34090,NaN,2017-04-24 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,2017-04-24 00:00:00.0000000,J,2017-06-27 00:00:00.0000000,N,JN
9,1724686,BJCM,BGHBFA,2017,2017-09-01 00:00:00.0000000,2018-08-31 00:00:00.0000000,S,D,V,0,2017-04-24 15:00:46.0000000,2017-06-26 00:00:00.0000000,NaN,34405,NaN,2017-04-24 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J,2017-04-24 00:00:00.0000000,J,NaN,NaN,NaN

In [240]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 30 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   STUDENT_NUM                       37 non-null     int64
 1   STUDY_PROGRAM                     37 non-null     object
 2   MAIN_STUDY_PROGRAM                37 non-null     object
 3   ACADEMIC_YEAR                     37 non-null     int64
 4   START_DATE                        37 non-null     object
 5   END_DATE                          37 non-null     object
 6   ENROLLMENT_TYPE                   37 non-null     object
 7   EXAM_TYPE                         37 non-null     object
 8   FULL_TIME_PART                    37 non-null     object
 9   PROGRAM_ACTIVE_CODE               37 non-null     int64
 10  DATE_ACTIVE_CODE_MODIFIED         37 non-null     object
 11  DATE_WITHRAWAL_PRE-REGIS          5 non-null      object
 12  WITHDRAWAL_REASON                 10 non-null     object
 13  HIGHER_EDU_REGISTER               37 non-null     int64
 14  DATE_REGIS_PROOF                  25 non-null     object
 15  DATE_ENROLLMENT_REQUEST           37 non-null     object
 16  LOTTERY_FORM                      33 non-null     object
 17  DECENTRALIZED_RESULT_SELECTION    1 non-null      object
 18  DECENTRALIZED_SELECTION_FOLLOWUP  1 non-null      float64
 19  LOTTERY_RESULT                    1 non-null      object
 20  LOTTERY_RESERVATION_REASON        0 non-null      float64
 21  LOTTERY_STATUS                    1 non-null      object
 22  LOTTERY_REJECTION_REASON          0 non-null      float64
 23  DATE_REQUEST_STOP                 5 non-null      object
 24  FINANCING                         37 non-null     object
 25  DATE_FIRST_ENROL_REQUEST          14 non-null     object
 26  STUDY_CHECK_PARTICIPATION         37 non-null     object
 27  DATE_STUDY_CHECK                  7 non-null      object
 28  STUDY_CHECK_RESULT                7 non-null      object
 29  STUDY_CHECK_ADMISSION             7 non-null      object
dtypes: float64(3), int64(4), object(23)
memory usage: 8.8+ KB

In [241]:
df1.isnull().sum()

STUDENT_NUM                          0
STUDY_PROGRAM                        0
MAIN_STUDY_PROGRAM                   0
ACADEMIC_YEAR                        0
START_DATE                           0
END_DATE                             0
ENROLLMENT_TYPE                      0
EXAM_TYPE                            0
FULL_TIME_PART                       0
PROGRAM_ACTIVE_CODE                  0
DATE_ACTIVE_CODE_MODIFIED            0
DATE_WITHRAWAL_PRE-REGIS            32
WITHDRAWAL_REASON                   27
HIGHER_EDU_REGISTER                  0
DATE_REGIS_PROOF                    12
DATE_ENROLLMENT_REQUEST              0
LOTTERY_FORM                         4
DECENTRALIZED_RESULT_SELECTION      36
DECENTRALIZED_SELECTION_FOLLOWUP    36
LOTTERY_RESULT                      36
LOTTERY_RESERVATION_REASON          37
LOTTERY_STATUS                      36
LOTTERY_REJECTION_REASON            37
DATE_REQUEST_STOP                   32
FINANCING                            0
DATE_FIRST_ENROL_REQUEST            23
STUDY_CHECK_PARTICIPATION            0
DATE_STUDY_CHECK                    30
STUDY_CHECK_RESULT                  30
STUDY_CHECK_ADMISSION               30
dtype: int64

df1 has 37 rows, therefore if the sum of the null values for a column is = 37 then it means the whole column is empty and can be deleted. Lets confirm the value counts for those columns

In [242]:
print(df1['LOTTERY_RESERVATION_REASON'].value_counts())

Series([], Name: count, dtype: int64)

In [243]:
print(df1['LOTTERY_REJECTION_REASON'].value_counts())

Series([], Name: count, dtype: int64)

In [244]:
del df1['LOTTERY_RESERVATION_REASON']
del df1['LOTTERY_REJECTION_REASON']

For columns with sum of missing values = 36, it means they only have one row with a non missing value. However, we wont delete them for now, maybe with a bigger dataset the case will be different

In [245]:
print(df1['DECENTRALIZED_RESULT_SELECTION'].value_counts())

DECENTRALIZED_RESULT_SELECTION
S    1
Name: count, dtype: int64

# df2

In [246]:
df2.columns

Index(['STUDENTNUMMER', 'OPLEIDING', 'EXAMENTYPE', 'AANVANGSDATUM',
       'EXAMENPROGRAMMA', 'EXAMENDATUM', 'JUDICIUM', 'EERSTE_GRAAD',
       'DEELNAME_HONOURS'],
      dtype='object')

In [247]:
# renaming columns for df2
df2_rename_mapping = {
    'STUDENTNUMMER': 'STUDENT_NUM',
    'OPLEIDING': 'STUDY_PROGRAM',
    'EXAMENTYPE': 'EXAM_ADMINISTERED',
    'AANVANGSDATUM': 'DATE_EXAM_STARTED',
    'EXAMENPROGRAMMA': 'EXAM_PROG_DETAILS',
    'EXAMENDATUM': 'DATE_EXAM_CONDUCTED',
    'JUDICIUM': 'EXAM_FINAL_RESULT',
    'EERSTE_GRAAD': 'EXAM_GRADE',
    'DEELNAME_HONOURS': 'HONORS_PROG_PARTICIPATION'
    }

# Rename columns
df2.rename(columns=df2_rename_mapping, inplace=True)
# Create a list of the new column names
df2_new_columns = list(df2_rename_mapping.values())
df2 = df2[df2_new_columns]

In [248]:
df2

,STUDENT_NUM,STUDY_PROGRAM,EXAM_ADMINISTERED,DATE_EXAM_STARTED,EXAM_PROG_DETAILS,DATE_EXAM_CONDUCTED,EXAM_FINAL_RESULT,EXAM_GRADE,HONORS_PROG_PARTICIPATION
0,1699140,BJDE,D,2016-09-01,JDE-DV-16,2017-12-20,---,N,N
1,1699140,BJDE,B,2017-09-01,JDE-BV-17,2022-02-01,---,J,N
2,1764427,BOPAPABOV,D,2019-09-01,OTVP-DT-19,NaT,NaN,J,N
3,1765243,BGHBFY,B,2020-02-01,G-EXTERN-17,NaT,NaN,J,N
4,1766090,BMLM,D,2019-09-01,MBLM-DV-19,2020-06-30,---,N,N
5,1766090,BMLM,B,2020-09-01,MBLM-BV-19,NaT,NaN,J,N
6,1768080,BTICIC,D,2019-09-01,TICT-VPOPICT-19,NaT,NaN,J,N
7,1768080,BTICIC,B,2020-09-01,TICT-VBAOPIC-20,NaT,NaN,J,N
8,1769163,BTLCCY,D,2019-09-01,TCHY-PROPD-19,2021-04-20,---,N,N
9,1769163,BTLCCY,B,2020-01-01,TCHY-BASD-19,2023-02-02,MG,J,N
10,1771302,BARE,D,2019-09-01,ADR-HBRV-D-20,2022-11-10,---,N,N
11,1771302,BARE,B,2021-09-01,ADR-HBRV-B-21,NaT,NaN,J,N

In [249]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   STUDENT_NUM                12 non-null     int64
 1   STUDY_PROGRAM              12 non-null     object
 2   EXAM_ADMINISTERED          12 non-null     object
 3   DATE_EXAM_STARTED          12 non-null     datetime64[ns]
 4   EXAM_PROG_DETAILS          12 non-null     object
 5   DATE_EXAM_CONDUCTED        6 non-null      datetime64[ns]
 6   EXAM_FINAL_RESULT          6 non-null      object
 7   EXAM_GRADE                 12 non-null     object
 8   HONORS_PROG_PARTICIPATION  12 non-null     object
dtypes: datetime64[ns](2), int64(1), object(6)
memory usage: 996.0+ bytes

In [250]:
df2.isnull().sum()

STUDENT_NUM                  0
STUDY_PROGRAM                0
EXAM_ADMINISTERED            0
DATE_EXAM_STARTED            0
EXAM_PROG_DETAILS            0
DATE_EXAM_CONDUCTED          6
EXAM_FINAL_RESULT            6
EXAM_GRADE                   0
HONORS_PROG_PARTICIPATION    0
dtype: int64

# df3

In [251]:
df3.columns

Index(['STUDENTNUMMER', 'VOOROPLEIDING', 'SCHOOL_NAAM', 'EINDEXAMENDATUM',
       'DIPLOMA_BEHAALD', 'EXTENSIE_CODE', 'EXTENSIE_NAAM',
       'STATUS_VERIFICATIE', 'DATUM_VERIFICATIE'],
      dtype='object')

In [252]:
# renaming columns for df3
df3_rename_mapping = {
    'STUDENTNUMMER': 'STUDENT_NUM',
    'VOOROPLEIDING': 'PRIOR_EDUCATION',
    'SCHOOL_NAAM': 'PRIOR_SCHOOL_NAME',
    'EINDEXAMENDATUM': 'PRIOR_FINAL_EXAM_DATE',
    'DIPLOMA_BEHAALD': 'PRIOR_DIMPLOMA_OBTAINTION',
    'EXTENSIE_CODE': 'PRIOR_EXTENSION_CODE',
    'EXTENSIE_NAAM': 'PRIOR_EXTENSION_NAME',
    'STATUS_VERIFICATIE': 'PRIOR_VERIFICATION_STATUS',
    'DATUM_VERIFICATIE': 'PRIOR_VERIFICATION_DATE'
    }
# Rename columns
df3.rename(columns=df3_rename_mapping, inplace=True)
# Create a list of the new column names
df3_new_columns = list(df3_rename_mapping.values())
df3 = df3[df3_new_columns]

In [253]:
df3

,STUDENT_NUM,PRIOR_EDUCATION,PRIOR_SCHOOL_NAME,PRIOR_FINAL_EXAM_DATE,PRIOR_DIMPLOMA_OBTAINTION,PRIOR_EXTENSION_CODE,PRIOR_EXTENSION_NAME,PRIOR_VERIFICATION_STATUS,PRIOR_VERIFICATION_DATE
0,1699140,379,Gereformeerde Scholengemeenschap Randstad Gymn...,2016-06-16,J,NaN,NaN,GD,2016-06-16
1,1699140,591,Hogeschool Utrecht,2022-02-01,J,34092.0,B Communication and Multimedia Design,GD,2022-02-01
2,1699140,611,Hogeschool Utrecht,2017-12-20,J,34092.0,B Communication and Multimedia Design,GD,2017-12-20
3,1724686,93212,Stichting ROC Midden Nederland,2013-09-30,J,NaN,NaN,GD,2013-09-30
4,1764427,361,Scholengemeenschap voor Voortgezet Vrije Schoo...,1988-06-10,J,NaN,NaN,DD,2019-05-10
5,1764427,591,Hogeschool Utrecht,NaT,N,34808.0,B Opleiding tot leraar Basisonderwijs,GV,2019-06-17
6,1764427,711,"onbekend, zie diploma",1990-05-18,J,NaN,NaN,N,NaT
7,1765243,371,Martinus College Christelijke Scholengemeensch...,2017-06-15,J,NaN,NaN,GD,2017-06-15
8,1765243,591,Hogeschool van Amsterdam,2022-01-26,J,34572.0,B Opleiding tot Oefentherapeut,GD,2022-01-26
9,1765243,611,Hogeschool van Amsterdam,2018-07-19,J,34572.0,B Opleiding tot Oefentherapeut-Mensendieck,GD,2018-07-19
10,1765243,SL 00591-01,Hogeschool Utrecht,NaT,N,34570.0,B Opleiding tot Fysiotherapeut,N,NaT
11,1766090,179,Het Schoonhovens College,2018-06-13,J,NaN,NaN,GD,2018-06-13
12,1766090,591,Hogeschool Utrecht,NaT,N,35522.0,B Logistics Management,N,NaT
13,1766090,611,Hogeschool Utrecht,2020-06-30,J,35522.0,B Logistics Management,GD,2020-06-30
14,1766090,741,Universiteit Utrecht; Utrecht,NaT,N,50950.0,B Economie en Bedrijfseconomie,N,NaT
15,1768080,3,Stichting ROC Midden Nederland,2015-06-26,J,NaN,NaN,N,NaT
16,1768080,591,Hogeschool Utrecht,NaT,N,30020.0,B HBO-ICT,GV,2021-09-24
17,1768080,601,Hogeschool Utrecht; Utrecht,2019-05-09,J,NaN,NaN,DD,2019-05-21
18,1769163,591,Hogeschool Utrecht,2023-02-02,J,34396.0,B Chemie,GD,2023-02-02
19,1769163,611,Hogeschool Utrecht,2021-04-20,J,34396.0,B Chemie,GD,2021-04-20
20,1769163,91711,ROC West-Brabant,2010-07-06,J,NaN,NaN,GD,2010-07-06
21,1771302,591,De Haagse Hogeschool; Den Haag,NaT,N,35158.0,B Pedagogiek,N,NaT
22,1771302,611,Hogeschool Utrecht,2022-11-10,J,39205.0,B HBO - Rechten,GD,2022-11-10
23,1771302,92632,Regionaal Opleidingen Centrum,2017-09-26,J,NaN,NaN,GD,2017-09-26
24,1771302,SL 00591-01,Hogeschool Utrecht,NaT,N,39205.0,B HBO - Rechten,GV,2022-12-19

In [254]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   STUDENT_NUM                25 non-null     int64
 1   PRIOR_EDUCATION            25 non-null     object
 2   PRIOR_SCHOOL_NAME          25 non-null     object
 3   PRIOR_FINAL_EXAM_DATE      18 non-null     datetime64[ns]
 4   PRIOR_DIMPLOMA_OBTAINTION  25 non-null     object
 5   PRIOR_EXTENSION_CODE       15 non-null     float64
 6   PRIOR_EXTENSION_NAME       15 non-null     object
 7   PRIOR_VERIFICATION_STATUS  25 non-null     object
 8   PRIOR_VERIFICATION_DATE    19 non-null     datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(1), object(5)
memory usage: 1.9+ KB

In [255]:
df3.isnull().sum()

STUDENT_NUM                   0
PRIOR_EDUCATION               0
PRIOR_SCHOOL_NAME             0
PRIOR_FINAL_EXAM_DATE         7
PRIOR_DIMPLOMA_OBTAINTION     0
PRIOR_EXTENSION_CODE         10
PRIOR_EXTENSION_NAME         10
PRIOR_VERIFICATION_STATUS     0
PRIOR_VERIFICATION_DATE       6
dtype: int64

# df4

In [256]:
df4.columns

Index(['VOOROPLEIDING', 'NAAM', 'TYPE_VOOROPLEIDING', 'TYPV_OMSCHRIJVING_NLS',
       'ACTUEEL'],
      dtype='object')

In [257]:
# renaming columns for df4
df4_rename_mapping = {
    'VOOROPLEIDING': 'PRIOR_EDUCATION',
    'NAAM': 'PRIOR_QUALIFICATION',
    'TYPE_VOOROPLEIDING': 'PRIOR_QUALIFICATION_TYPE',
    'ACTUEEL': 'INFO_CURRENT'
    }
# Rename columns
df4.rename(columns=df4_rename_mapping, inplace=True)
# Create a list of the new column names
df4_new_columns = list(df4_rename_mapping.values())
df4 = df4[df4_new_columns]

In [258]:
df4

,PRIOR_EDUCATION,PRIOR_QUALIFICATION,PRIOR_QUALIFICATION_TYPE,INFO_CURRENT
0,3,VWO certificaat,OVERIG,N
1,179,VWO NIEUW (E+M EN C+M),VWO,J
2,361,VWO,VWO,J
3,371,HAVO NIEUW (N+G),HAVO,J
4,379,HAVO NIEUW (E+M EN C+M),HAVO,J
5,591,Bachelor HBO,HBO,J
6,601,COLLOQUIUM DOCTUM + VOOROPL. O,OVERIG,J
7,611,PROPEDEUSE BACHELOR HBO,OVERIG,J
8,711,PROPEDEUSEVERKLARING BACHELOR UNIVERSITE,OVERIG,J
9,741,Bachelor WO,WO,J
10,91711,CFA CHEMISCH ANALIST,MBO,J
11,92632,PEDAGOGISCH WERKER KINDEROPVANG,MBO,J
12,93212,ADM BEDRIJFSADMINISTRATEUR,MBO,J
13,SL 00591-01,Bachelor HBO via SL,HBO,J

In [259]:
# Define the list of valid qualifications
valid_qualifications = ['VWO', 'HAVO', 'HBO', 'MBO', 'VO', 'WO']

# Function to check and replace values
def replace_qualification_type(row):
    if row['PRIOR_QUALIFICATION_TYPE'] == 'OVERIG':
        # Extract the qualification from the PRIOR_QUALIFICATION column
        qualification = row['PRIOR_QUALIFICATION']
        # Check if the qualification contains one of the valid qualifications
        for q in valid_qualifications:
            if q in qualification:
                return q  # Replace with the valid qualification
    return row['PRIOR_QUALIFICATION_TYPE']  # Keep the original value

# Apply the function to each row
df4['PRIOR_QUALIFICATION_TYPE'] = df4.apply(replace_qualification_type, axis=1)

# Remove any other strings that are not in the valid qualifications list
df4['PRIOR_QUALIFICATION_TYPE'] = df4['PRIOR_QUALIFICATION_TYPE'].apply(lambda x: x if x in valid_qualifications else None)

# Display the updated DataFrame
df4

,PRIOR_EDUCATION,PRIOR_QUALIFICATION,PRIOR_QUALIFICATION_TYPE,INFO_CURRENT
0,3,VWO certificaat,VWO,N
1,179,VWO NIEUW (E+M EN C+M),VWO,J
2,361,VWO,VWO,J
3,371,HAVO NIEUW (N+G),HAVO,J
4,379,HAVO NIEUW (E+M EN C+M),HAVO,J
5,591,Bachelor HBO,HBO,J
6,601,COLLOQUIUM DOCTUM + VOOROPL. O,VO,J
7,611,PROPEDEUSE BACHELOR HBO,HBO,J
8,711,PROPEDEUSEVERKLARING BACHELOR UNIVERSITE,None,J
9,741,Bachelor WO,WO,J
10,91711,CFA CHEMISCH ANALIST,MBO,J
11,92632,PEDAGOGISCH WERKER KINDEROPVANG,MBO,J
12,93212,ADM BEDRIJFSADMINISTRATEUR,MBO,J
13,SL 00591-01,Bachelor HBO via SL,HBO,J

In [260]:
del df4['PRIOR_QUALIFICATION']

In [261]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   PRIOR_EDUCATION           14 non-null     object
 1   PRIOR_QUALIFICATION_TYPE  13 non-null     object
 2   INFO_CURRENT              14 non-null     object
dtypes: object(3)
memory usage: 468.0+ bytes

# df5

In [262]:
df5.columns

Index(['STUDENTNUMMER', 'GEBOORTEDATUM', 'GESLACHT', 'NATIONALITEIT',
       'AANVANGSJAAR_UU_STUDENT'],
      dtype='object')

In [263]:
# renaming columns for df1
df5_rename_mapping = {
    'STUDENTNUMMER': 'STUDENT_NUM',
    'GEBOORTEDATUM': 'BIRTH_DATE',
    'GESLACHT': 'GENDER',
    'NATIONALITEIT': 'NATIONALITY',
    'AANVANGSJAAR_UU_STUDENT': 'YEAR_STARTED_HU'
    }
# Rename columns
df5.rename(columns=df5_rename_mapping, inplace=True)
# Create a list of the new column names
df5_new_columns = list(df5_rename_mapping.values())
df5 = df5[df5_new_columns]

In [264]:
df5

   STUDENT_NUM BIRTH_DATE GENDER NATIONALITY  YEAR_STARTED_HU
0      1699140 1999-10-08      V          NL             2016
1      1724686 1990-12-17      V          NL             2017
2      1764427 1968-07-30      V          NL             2019
3      1765243 1999-02-23      V          NL             2019
4      1766090 2000-03-08      M          NL             2019
5      1768080 1994-01-15      M         XXX             2019
6      1769163 1989-12-30      M          NL             2019
7      1771302 1997-03-03      V          NL             2019

In [265]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   STUDENT_NUM      8 non-null      int64
 1   BIRTH_DATE       8 non-null      datetime64[ns]
 2   GENDER           8 non-null      object
 3   NATIONALITY      8 non-null      object
 4   YEAR_STARTED_HU  8 non-null      int64
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 452.0+ bytes

# Combining dataframes: From observation df1, df2, df3, and df5 have STUDENT_NUM as primary key. We start by combining them, then combine the result with df4 using vooropleiding since df3 had PRIOR_EDUCATION

In [266]:
# Confirm primary key for df1, df2, df3, and df5
columns_df1 = set(df1.columns)
columns_df2 = set(df2.columns)
columns_df3 = set(df3.columns)
#columns_df4 = set(df4.columns)
columns_df5 = set(df5.columns)

# Find common columns
common_columns = columns_df1.intersection(columns_df2, columns_df3, columns_df5)

print(common_columns)

{'STUDENT_NUM'}

In [267]:
# List of DataFrames to merge
dfs = [df1, df2, df3, df5]

# Merge all DataFrames on the 'STUDENTNUMBER' column
combined_df = reduce(lambda left, right: pd.merge(left, right, on='STUDENT_NUM'), dfs)

combined_df

,STUDENT_NUM,STUDY_PROGRAM_x,MAIN_STUDY_PROGRAM,ACADEMIC_YEAR,START_DATE,END_DATE,ENROLLMENT_TYPE,EXAM_TYPE,FULL_TIME_PART,PROGRAM_ACTIVE_CODE,DATE_ACTIVE_CODE_MODIFIED,DATE_WITHRAWAL_PRE-REGIS,WITHDRAWAL_REASON,HIGHER_EDU_REGISTER,DATE_REGIS_PROOF,DATE_ENROLLMENT_REQUEST,LOTTERY_FORM,DECENTRALIZED_RESULT_SELECTION,DECENTRALIZED_SELECTION_FOLLOWUP,LOTTERY_RESULT,LOTTERY_STATUS,DATE_REQUEST_STOP,FINANCING,DATE_FIRST_ENROL_REQUEST,STUDY_CHECK_PARTICIPATION,DATE_STUDY_CHECK,STUDY_CHECK_RESULT,STUDY_CHECK_ADMISSION,STUDY_PROGRAM_y,EXAM_ADMINISTERED,DATE_EXAM_STARTED,EXAM_PROG_DETAILS,DATE_EXAM_CONDUCTED,EXAM_FINAL_RESULT,EXAM_GRADE,HONORS_PROG_PARTICIPATION,PRIOR_EDUCATION,PRIOR_SCHOOL_NAME,PRIOR_FINAL_EXAM_DATE,PRIOR_DIMPLOMA_OBTAINTION,PRIOR_EXTENSION_CODE,PRIOR_EXTENSION_NAME,PRIOR_VERIFICATION_STATUS,PRIOR_VERIFICATION_DATE,BIRTH_DATE,GENDER,NATIONALITY,YEAR_STARTED_HU
0,1699140,BJDE,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,4,2016-08-27 00:00:00.0000000,NaN,NaN,34092,2016-08-29 00:00:00.0000000,2016-03-01 00:00:00.0000000,C,S,295.0,I,V,NaN,J,2016-03-01 00:00:00.0000000,NVT,NaN,NaN,NaN,BJDE,D,2016-09-01,JDE-DV-16,2017-12-20,---,N,N,379,Gereformeerde Scholengemeenschap Randstad Gymn...,2016-06-16,J,NaN,NaN,GD,2016-06-16,1999-10-08,V,NL,2016
1,1699140,BJDE,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,4,2016-08-27 00:00:00.0000000,NaN,NaN,34092,2016-08-29 00:00:00.0000000,2016-03-01 00:00:00.0000000,C,S,295.0,I,V,NaN,J,2016-03-01 00:00:00.0000000,NVT,NaN,NaN,NaN,BJDE,D,2016-09-01,JDE-DV-16,2017-12-20,---,N,N,591,Hogeschool Utrecht,2022-02-01,J,34092.0,B Communication and Multimedia Design,GD,2022-02-01,1999-10-08,V,NL,2016
2,1699140,BJDE,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,4,2016-08-27 00:00:00.0000000,NaN,NaN,34092,2016-08-29 00:00:00.0000000,2016-03-01 00:00:00.0000000,C,S,295.0,I,V,NaN,J,2016-03-01 00:00:00.0000000,NVT,NaN,NaN,NaN,BJDE,D,2016-09-01,JDE-DV-16,2017-12-20,---,N,N,611,Hogeschool Utrecht,2017-12-20,J,34092.0,B Communication and Multimedia Design,GD,2017-12-20,1999-10-08,V,NL,2016
3,1699140,BJDE,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,4,2016-08-27 00:00:00.0000000,NaN,NaN,34092,2016-08-29 00:00:00.0000000,2016-03-01 00:00:00.0000000,C,S,295.0,I,V,NaN,J,2016-03-01 00:00:00.0000000,NVT,NaN,NaN,NaN,BJDE,B,2017-09-01,JDE-BV-17,2022-02-01,---,J,N,379,Gereformeerde Scholengemeenschap Randstad Gymn...,2016-06-16,J,NaN,NaN,GD,2016-06-16,1999-10-08,V,NL,2016
4,1699140,BJDE,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,4,2016-08-27 00:00:00.0000000,NaN,NaN,34092,2016-08-29 00:00:00.0000000,2016-03-01 00:00:00.0000000,C,S,295.0,I,V,NaN,J,2016-03-01 00:00:00.0000000,NVT,NaN,NaN,NaN,BJDE,B,2017-09-01,JDE-BV-17,2022-02-01,---,J,N,591,Hogeschool Utrecht,2022-02-01,J,34092.0,B Communication and Multimedia Design,GD,2022-02-01,1999-10-08,V,NL,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,1771302,BARE,BARE,2024,2024-09-01 00:00:00.0000000,2025-08-31 00:00:00.0000000,S,B,V,4,2024-05-13 13:05:24.0000000,NaN,NaN,39205,NaN,2024-05-13 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN,BARE,D,2019-09-01,ADR-HBRV-D-20,2022-11-10,---,N,N,SL 00591-01,Hogeschool Utrecht,NaT,N,39205.0,B HBO - Rechten,GV,2022-12-19,1997-03-03,V,NL,2019
207,1771302,BARE,BARE,2024,2024-09-01 00:00:00.0000000,2025-08-31 00:00:00.0000000,S,B,V,4,2024-05-13 13:05:24.0000000,NaN,NaN,39205,NaN,2024-05-13 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN,BARE,B,2021-09-01,ADR-HBRV-B-21,NaT,NaN,J,N,591,De Haagse Hogeschool; Den Haag,NaT,N,35158.0,B Pedagogiek,N,NaT,1997-03-03,V,NL,2019
208,1771302,BARE,BARE,2024,2024-09-01 00:00:00.0000000,2025-08-31 00:00:00.0000000,S,B,V,4,2024-05-13 13:05:24.0000000,NaN,NaN,39205,NaN,2024-05-13 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN,BARE,B,2021-09-01,ADR-HBRV-B-21,NaT,NaN,J,N,611,Hogeschool Utrecht,2022-11-10,J,39205.0,B HBO - Rechten,GD,2022-11-10,1997-03-03,V,NL,2019
209,1771302,BARE,BARE,2024,2024-09-01 00:00:00.0000000,2025-08-31 00:00:00.0000000,S,B,V,4,2024-05-13 13:05:24.0000000,NaN,NaN,39205,NaN,2024-05-13 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN,BARE,B,2021-09-01,ADR-HBRV-B-21,NaT,NaN,J,N,92632,Regionaal Opleidingen Centrum,2017-09-26,J,NaN,NaN,GD,2017-09-26,1997-03-03,V,NL,2019
210,1771302,BARE,BARE,2024,2024-09-01 00:00:00.0000000,2025-08-31 00:00:00.0000000,S,B,V,4,2024-05-13 13:05:24.0000000,NaN,NaN,39205,NaN,2024-05-13 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN,BARE,B,2021-09-01,ADR-HBRV-B-21,NaT,NaN,J,N,SL 00591-01,Hogeschool Utrecht,NaT,N,39205.0,B HBO - Rechten,GV,2022-12-19,1997-03-03,V,NL,2019

In [268]:
combined_df.columns

Index(['STUDENT_NUM', 'STUDY_PROGRAM_x', 'MAIN_STUDY_PROGRAM', 'ACADEMIC_YEAR',
       'START_DATE', 'END_DATE', 'ENROLLMENT_TYPE', 'EXAM_TYPE',
       'FULL_TIME_PART', 'PROGRAM_ACTIVE_CODE', 'DATE_ACTIVE_CODE_MODIFIED',
       'DATE_WITHRAWAL_PRE-REGIS', 'WITHDRAWAL_REASON', 'HIGHER_EDU_REGISTER',
       'DATE_REGIS_PROOF', 'DATE_ENROLLMENT_REQUEST', 'LOTTERY_FORM',
       'DECENTRALIZED_RESULT_SELECTION', 'DECENTRALIZED_SELECTION_FOLLOWUP',
       'LOTTERY_RESULT', 'LOTTERY_STATUS', 'DATE_REQUEST_STOP', 'FINANCING',
       'DATE_FIRST_ENROL_REQUEST', 'STUDY_CHECK_PARTICIPATION',
       'DATE_STUDY_CHECK', 'STUDY_CHECK_RESULT', 'STUDY_CHECK_ADMISSION',
       'STUDY_PROGRAM_y', 'EXAM_ADMINISTERED', 'DATE_EXAM_STARTED',
       'EXAM_PROG_DETAILS', 'DATE_EXAM_CONDUCTED', 'EXAM_FINAL_RESULT',
       'EXAM_GRADE', 'HONORS_PROG_PARTICIPATION', 'PRIOR_EDUCATION',
       'PRIOR_SCHOOL_NAME', 'PRIOR_FINAL_EXAM_DATE',
       'PRIOR_DIMPLOMA_OBTAINTION', 'PRIOR_EXTENSION_CODE',
       'PRIOR_EXTENSION_NAME', 'PRIOR_VERIFICATION_STATUS',
       'PRIOR_VERIFICATION_DATE', 'BIRTH_DATE', 'GENDER', 'NATIONALITY',
       'YEAR_STARTED_HU'],
      dtype='object')

In [269]:
df4.columns

Index(['PRIOR_EDUCATION', 'PRIOR_QUALIFICATION_TYPE', 'INFO_CURRENT'], dtype='object')

In [270]:
# Confirm primary key for combined_df and df4
columns_df4 = set(df4.columns)
columns_combined = set(combined_df.columns)
# Find common columns
final_common = columns_df4.intersection(columns_combined)

print(final_common)

{'PRIOR_EDUCATION'}

In [271]:
# Merge combined_df and df4
df4_com = [combined_df, df4]
osiris = reduce(lambda left, right: pd.merge(left, right, on='PRIOR_EDUCATION'), df4_com)

osiris

,STUDENT_NUM,STUDY_PROGRAM_x,MAIN_STUDY_PROGRAM,ACADEMIC_YEAR,START_DATE,END_DATE,ENROLLMENT_TYPE,EXAM_TYPE,FULL_TIME_PART,PROGRAM_ACTIVE_CODE,DATE_ACTIVE_CODE_MODIFIED,DATE_WITHRAWAL_PRE-REGIS,WITHDRAWAL_REASON,HIGHER_EDU_REGISTER,DATE_REGIS_PROOF,DATE_ENROLLMENT_REQUEST,LOTTERY_FORM,DECENTRALIZED_RESULT_SELECTION,DECENTRALIZED_SELECTION_FOLLOWUP,LOTTERY_RESULT,LOTTERY_STATUS,DATE_REQUEST_STOP,FINANCING,DATE_FIRST_ENROL_REQUEST,STUDY_CHECK_PARTICIPATION,DATE_STUDY_CHECK,STUDY_CHECK_RESULT,STUDY_CHECK_ADMISSION,STUDY_PROGRAM_y,EXAM_ADMINISTERED,DATE_EXAM_STARTED,EXAM_PROG_DETAILS,DATE_EXAM_CONDUCTED,EXAM_FINAL_RESULT,EXAM_GRADE,HONORS_PROG_PARTICIPATION,PRIOR_EDUCATION,PRIOR_SCHOOL_NAME,PRIOR_FINAL_EXAM_DATE,PRIOR_DIMPLOMA_OBTAINTION,PRIOR_EXTENSION_CODE,PRIOR_EXTENSION_NAME,PRIOR_VERIFICATION_STATUS,PRIOR_VERIFICATION_DATE,BIRTH_DATE,GENDER,NATIONALITY,YEAR_STARTED_HU,PRIOR_QUALIFICATION_TYPE,INFO_CURRENT
0,1699140,BJDE,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,4,2016-08-27 00:00:00.0000000,NaN,NaN,34092,2016-08-29 00:00:00.0000000,2016-03-01 00:00:00.0000000,C,S,295.0,I,V,NaN,J,2016-03-01 00:00:00.0000000,NVT,NaN,NaN,NaN,BJDE,D,2016-09-01,JDE-DV-16,2017-12-20,---,N,N,379,Gereformeerde Scholengemeenschap Randstad Gymn...,2016-06-16,J,NaN,NaN,GD,2016-06-16,1999-10-08,V,NL,2016,HAVO,J
1,1699140,BJDE,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,4,2016-08-27 00:00:00.0000000,NaN,NaN,34092,2016-08-29 00:00:00.0000000,2016-03-01 00:00:00.0000000,C,S,295.0,I,V,NaN,J,2016-03-01 00:00:00.0000000,NVT,NaN,NaN,NaN,BJDE,D,2016-09-01,JDE-DV-16,2017-12-20,---,N,N,591,Hogeschool Utrecht,2022-02-01,J,34092.0,B Communication and Multimedia Design,GD,2022-02-01,1999-10-08,V,NL,2016,HBO,J
2,1699140,BJDE,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,4,2016-08-27 00:00:00.0000000,NaN,NaN,34092,2016-08-29 00:00:00.0000000,2016-03-01 00:00:00.0000000,C,S,295.0,I,V,NaN,J,2016-03-01 00:00:00.0000000,NVT,NaN,NaN,NaN,BJDE,D,2016-09-01,JDE-DV-16,2017-12-20,---,N,N,611,Hogeschool Utrecht,2017-12-20,J,34092.0,B Communication and Multimedia Design,GD,2017-12-20,1999-10-08,V,NL,2016,HBO,J
3,1699140,BJDE,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,4,2016-08-27 00:00:00.0000000,NaN,NaN,34092,2016-08-29 00:00:00.0000000,2016-03-01 00:00:00.0000000,C,S,295.0,I,V,NaN,J,2016-03-01 00:00:00.0000000,NVT,NaN,NaN,NaN,BJDE,B,2017-09-01,JDE-BV-17,2022-02-01,---,J,N,379,Gereformeerde Scholengemeenschap Randstad Gymn...,2016-06-16,J,NaN,NaN,GD,2016-06-16,1999-10-08,V,NL,2016,HAVO,J
4,1699140,BJDE,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,4,2016-08-27 00:00:00.0000000,NaN,NaN,34092,2016-08-29 00:00:00.0000000,2016-03-01 00:00:00.0000000,C,S,295.0,I,V,NaN,J,2016-03-01 00:00:00.0000000,NVT,NaN,NaN,NaN,BJDE,B,2017-09-01,JDE-BV-17,2022-02-01,---,J,N,591,Hogeschool Utrecht,2022-02-01,J,34092.0,B Communication and Multimedia Design,GD,2022-02-01,1999-10-08,V,NL,2016,HBO,J
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,1771302,BARE,BARE,2024,2024-09-01 00:00:00.0000000,2025-08-31 00:00:00.0000000,S,B,V,4,2024-05-13 13:05:24.0000000,NaN,NaN,39205,NaN,2024-05-13 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN,BARE,D,2019-09-01,ADR-HBRV-D-20,2022-11-10,---,N,N,SL 00591-01,Hogeschool Utrecht,NaT,N,39205.0,B HBO - Rechten,GV,2022-12-19,1997-03-03,V,NL,2019,HBO,J
207,1771302,BARE,BARE,2024,2024-09-01 00:00:00.0000000,2025-08-31 00:00:00.0000000,S,B,V,4,2024-05-13 13:05:24.0000000,NaN,NaN,39205,NaN,2024-05-13 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN,BARE,B,2021-09-01,ADR-HBRV-B-21,NaT,NaN,J,N,591,De Haagse Hogeschool; Den Haag,NaT,N,35158.0,B Pedagogiek,N,NaT,1997-03-03,V,NL,2019,HBO,J
208,1771302,BARE,BARE,2024,2024-09-01 00:00:00.0000000,2025-08-31 00:00:00.0000000,S,B,V,4,2024-05-13 13:05:24.0000000,NaN,NaN,39205,NaN,2024-05-13 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN,BARE,B,2021-09-01,ADR-HBRV-B-21,NaT,NaN,J,N,611,Hogeschool Utrecht,2022-11-10,J,39205.0,B HBO - Rechten,GD,2022-11-10,1997-03-03,V,NL,2019,HBO,J
209,1771302,BARE,BARE,2024,2024-09-01 00:00:00.0000000,2025-08-31 00:00:00.0000000,S,B,V,4,2024-05-13 13:05:24.0000000,NaN,NaN,39205,NaN,2024-05-13 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN,BARE,B,2021-09-01,ADR-HBRV-B-21,NaT,NaN,J,N,92632,Regionaal Opleidingen Centrum,2017-09-26,J,NaN,NaN,GD,2017-09-26,1997-03-03,V,NL,2019,MBO,J
210,1771302,BARE,BARE,2024,2024-09-01 00:00:00.0000000,2025-08-31 00:00:00.0000000,S,B,V,4,2024-05-13 13:05:24.0000000,NaN,NaN,39205,NaN,2024-05-13 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN,BARE,B,2021-09-01,ADR-HBRV-B-21,NaT,NaN,J,N,SL 00591-01,Hogeschool Utrecht,NaT,N,39205.0,B HBO - Rechten,GV,2022-12-19,1997-03-03,V,NL,2019,HBO,J

In [272]:
osiris.columns

Index(['STUDENT_NUM', 'STUDY_PROGRAM_x', 'MAIN_STUDY_PROGRAM', 'ACADEMIC_YEAR',
       'START_DATE', 'END_DATE', 'ENROLLMENT_TYPE', 'EXAM_TYPE',
       'FULL_TIME_PART', 'PROGRAM_ACTIVE_CODE', 'DATE_ACTIVE_CODE_MODIFIED',
       'DATE_WITHRAWAL_PRE-REGIS', 'WITHDRAWAL_REASON', 'HIGHER_EDU_REGISTER',
       'DATE_REGIS_PROOF', 'DATE_ENROLLMENT_REQUEST', 'LOTTERY_FORM',
       'DECENTRALIZED_RESULT_SELECTION', 'DECENTRALIZED_SELECTION_FOLLOWUP',
       'LOTTERY_RESULT', 'LOTTERY_STATUS', 'DATE_REQUEST_STOP', 'FINANCING',
       'DATE_FIRST_ENROL_REQUEST', 'STUDY_CHECK_PARTICIPATION',
       'DATE_STUDY_CHECK', 'STUDY_CHECK_RESULT', 'STUDY_CHECK_ADMISSION',
       'STUDY_PROGRAM_y', 'EXAM_ADMINISTERED', 'DATE_EXAM_STARTED',
       'EXAM_PROG_DETAILS', 'DATE_EXAM_CONDUCTED', 'EXAM_FINAL_RESULT',
       'EXAM_GRADE', 'HONORS_PROG_PARTICIPATION', 'PRIOR_EDUCATION',
       'PRIOR_SCHOOL_NAME', 'PRIOR_FINAL_EXAM_DATE',
       'PRIOR_DIMPLOMA_OBTAINTION', 'PRIOR_EXTENSION_CODE',
       'PRIOR_EXTENSION_NAME', 'PRIOR_VERIFICATION_STATUS',
       'PRIOR_VERIFICATION_DATE', 'BIRTH_DATE', 'GENDER', 'NATIONALITY',
       'YEAR_STARTED_HU', 'PRIOR_QUALIFICATION_TYPE', 'INFO_CURRENT'],
      dtype='object')

In [273]:
del osiris['STUDY_PROGRAM_y']
osiris.rename(columns={'STUDY_PROGRAM_x': 'STUDY_PROGRAM'}, inplace=True)

In [274]:
# Save the DataFrame to the CSV file
osiris.to_csv(os.path.join("..", "data", "processed", "osiris_combined.csv"), header=True)

In [275]:
osiris

,STUDENT_NUM,STUDY_PROGRAM,MAIN_STUDY_PROGRAM,ACADEMIC_YEAR,START_DATE,END_DATE,ENROLLMENT_TYPE,EXAM_TYPE,FULL_TIME_PART,PROGRAM_ACTIVE_CODE,DATE_ACTIVE_CODE_MODIFIED,DATE_WITHRAWAL_PRE-REGIS,WITHDRAWAL_REASON,HIGHER_EDU_REGISTER,DATE_REGIS_PROOF,DATE_ENROLLMENT_REQUEST,LOTTERY_FORM,DECENTRALIZED_RESULT_SELECTION,DECENTRALIZED_SELECTION_FOLLOWUP,LOTTERY_RESULT,LOTTERY_STATUS,DATE_REQUEST_STOP,FINANCING,DATE_FIRST_ENROL_REQUEST,STUDY_CHECK_PARTICIPATION,DATE_STUDY_CHECK,STUDY_CHECK_RESULT,STUDY_CHECK_ADMISSION,EXAM_ADMINISTERED,DATE_EXAM_STARTED,EXAM_PROG_DETAILS,DATE_EXAM_CONDUCTED,EXAM_FINAL_RESULT,EXAM_GRADE,HONORS_PROG_PARTICIPATION,PRIOR_EDUCATION,PRIOR_SCHOOL_NAME,PRIOR_FINAL_EXAM_DATE,PRIOR_DIMPLOMA_OBTAINTION,PRIOR_EXTENSION_CODE,PRIOR_EXTENSION_NAME,PRIOR_VERIFICATION_STATUS,PRIOR_VERIFICATION_DATE,BIRTH_DATE,GENDER,NATIONALITY,YEAR_STARTED_HU,PRIOR_QUALIFICATION_TYPE,INFO_CURRENT
0,1699140,BJDE,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,4,2016-08-27 00:00:00.0000000,NaN,NaN,34092,2016-08-29 00:00:00.0000000,2016-03-01 00:00:00.0000000,C,S,295.0,I,V,NaN,J,2016-03-01 00:00:00.0000000,NVT,NaN,NaN,NaN,D,2016-09-01,JDE-DV-16,2017-12-20,---,N,N,379,Gereformeerde Scholengemeenschap Randstad Gymn...,2016-06-16,J,NaN,NaN,GD,2016-06-16,1999-10-08,V,NL,2016,HAVO,J
1,1699140,BJDE,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,4,2016-08-27 00:00:00.0000000,NaN,NaN,34092,2016-08-29 00:00:00.0000000,2016-03-01 00:00:00.0000000,C,S,295.0,I,V,NaN,J,2016-03-01 00:00:00.0000000,NVT,NaN,NaN,NaN,D,2016-09-01,JDE-DV-16,2017-12-20,---,N,N,591,Hogeschool Utrecht,2022-02-01,J,34092.0,B Communication and Multimedia Design,GD,2022-02-01,1999-10-08,V,NL,2016,HBO,J
2,1699140,BJDE,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,4,2016-08-27 00:00:00.0000000,NaN,NaN,34092,2016-08-29 00:00:00.0000000,2016-03-01 00:00:00.0000000,C,S,295.0,I,V,NaN,J,2016-03-01 00:00:00.0000000,NVT,NaN,NaN,NaN,D,2016-09-01,JDE-DV-16,2017-12-20,---,N,N,611,Hogeschool Utrecht,2017-12-20,J,34092.0,B Communication and Multimedia Design,GD,2017-12-20,1999-10-08,V,NL,2016,HBO,J
3,1699140,BJDE,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,4,2016-08-27 00:00:00.0000000,NaN,NaN,34092,2016-08-29 00:00:00.0000000,2016-03-01 00:00:00.0000000,C,S,295.0,I,V,NaN,J,2016-03-01 00:00:00.0000000,NVT,NaN,NaN,NaN,B,2017-09-01,JDE-BV-17,2022-02-01,---,J,N,379,Gereformeerde Scholengemeenschap Randstad Gymn...,2016-06-16,J,NaN,NaN,GD,2016-06-16,1999-10-08,V,NL,2016,HAVO,J
4,1699140,BJDE,BJDE,2016,2016-09-01 00:00:00.0000000,2017-08-31 00:00:00.0000000,S,D,V,4,2016-08-27 00:00:00.0000000,NaN,NaN,34092,2016-08-29 00:00:00.0000000,2016-03-01 00:00:00.0000000,C,S,295.0,I,V,NaN,J,2016-03-01 00:00:00.0000000,NVT,NaN,NaN,NaN,B,2017-09-01,JDE-BV-17,2022-02-01,---,J,N,591,Hogeschool Utrecht,2022-02-01,J,34092.0,B Communication and Multimedia Design,GD,2022-02-01,1999-10-08,V,NL,2016,HBO,J
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,1771302,BARE,BARE,2024,2024-09-01 00:00:00.0000000,2025-08-31 00:00:00.0000000,S,B,V,4,2024-05-13 13:05:24.0000000,NaN,NaN,39205,NaN,2024-05-13 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN,D,2019-09-01,ADR-HBRV-D-20,2022-11-10,---,N,N,SL 00591-01,Hogeschool Utrecht,NaT,N,39205.0,B HBO - Rechten,GV,2022-12-19,1997-03-03,V,NL,2019,HBO,J
207,1771302,BARE,BARE,2024,2024-09-01 00:00:00.0000000,2025-08-31 00:00:00.0000000,S,B,V,4,2024-05-13 13:05:24.0000000,NaN,NaN,39205,NaN,2024-05-13 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN,B,2021-09-01,ADR-HBRV-B-21,NaT,NaN,J,N,591,De Haagse Hogeschool; Den Haag,NaT,N,35158.0,B Pedagogiek,N,NaT,1997-03-03,V,NL,2019,HBO,J
208,1771302,BARE,BARE,2024,2024-09-01 00:00:00.0000000,2025-08-31 00:00:00.0000000,S,B,V,4,2024-05-13 13:05:24.0000000,NaN,NaN,39205,NaN,2024-05-13 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN,B,2021-09-01,ADR-HBRV-B-21,NaT,NaN,J,N,611,Hogeschool Utrecht,2022-11-10,J,39205.0,B HBO - Rechten,GD,2022-11-10,1997-03-03,V,NL,2019,HBO,J
209,1771302,BARE,BARE,2024,2024-09-01 00:00:00.0000000,2025-08-31 00:00:00.0000000,S,B,V,4,2024-05-13 13:05:24.0000000,NaN,NaN,39205,NaN,2024-05-13 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN,B,2021-09-01,ADR-HBRV-B-21,NaT,NaN,J,N,92632,Regionaal Opleidingen Centrum,2017-09-26,J,NaN,NaN,GD,2017-09-26,1997-03-03,V,NL,2019,MBO,J
210,1771302,BARE,BARE,2024,2024-09-01 00:00:00.0000000,2025-08-31 00:00:00.0000000,S,B,V,4,2024-05-13 13:05:24.0000000,NaN,NaN,39205,NaN,2024-05-13 00:00:00.0000000,N,NaN,NaN,NaN,NaN,NaN,J,NaN,NVT,NaN,NaN,NaN,B,2021-09-01,ADR-HBRV-B-21,NaT,NaN,J,N,SL 00591-01,Hogeschool Utrecht,NaT,N,39205.0,B HBO - Rechten,GV,2022-12-19,1997-03-03,V,NL,2019,HBO,J

In [276]:
osiris.columns

Index(['STUDENT_NUM', 'STUDY_PROGRAM', 'MAIN_STUDY_PROGRAM', 'ACADEMIC_YEAR',
       'START_DATE', 'END_DATE', 'ENROLLMENT_TYPE', 'EXAM_TYPE',
       'FULL_TIME_PART', 'PROGRAM_ACTIVE_CODE', 'DATE_ACTIVE_CODE_MODIFIED',
       'DATE_WITHRAWAL_PRE-REGIS', 'WITHDRAWAL_REASON', 'HIGHER_EDU_REGISTER',
       'DATE_REGIS_PROOF', 'DATE_ENROLLMENT_REQUEST', 'LOTTERY_FORM',
       'DECENTRALIZED_RESULT_SELECTION', 'DECENTRALIZED_SELECTION_FOLLOWUP',
       'LOTTERY_RESULT', 'LOTTERY_STATUS', 'DATE_REQUEST_STOP', 'FINANCING',
       'DATE_FIRST_ENROL_REQUEST', 'STUDY_CHECK_PARTICIPATION',
       'DATE_STUDY_CHECK', 'STUDY_CHECK_RESULT', 'STUDY_CHECK_ADMISSION',
       'EXAM_ADMINISTERED', 'DATE_EXAM_STARTED', 'EXAM_PROG_DETAILS',
       'DATE_EXAM_CONDUCTED', 'EXAM_FINAL_RESULT', 'EXAM_GRADE',
       'HONORS_PROG_PARTICIPATION', 'PRIOR_EDUCATION', 'PRIOR_SCHOOL_NAME',
       'PRIOR_FINAL_EXAM_DATE', 'PRIOR_DIMPLOMA_OBTAINTION',
       'PRIOR_EXTENSION_CODE', 'PRIOR_EXTENSION_NAME',
       'PRIOR_VERIFICATION_STATUS', 'PRIOR_VERIFICATION_DATE', 'BIRTH_DATE',
       'GENDER', 'NATIONALITY', 'YEAR_STARTED_HU', 'PRIOR_QUALIFICATION_TYPE',
       'INFO_CURRENT'],
      dtype='object')

In [277]:
osiris.isnull().sum()

STUDENT_NUM                           0
STUDY_PROGRAM                         0
MAIN_STUDY_PROGRAM                    0
ACADEMIC_YEAR                         0
START_DATE                            0
END_DATE                              0
ENROLLMENT_TYPE                       0
EXAM_TYPE                             0
FULL_TIME_PART                        0
PROGRAM_ACTIVE_CODE                   0
DATE_ACTIVE_CODE_MODIFIED             0
DATE_WITHRAWAL_PRE-REGIS            205
WITHDRAWAL_REASON                   150
HIGHER_EDU_REGISTER                   0
DATE_REGIS_PROOF                     56
DATE_ENROLLMENT_REQUEST               0
LOTTERY_FORM                         28
DECENTRALIZED_RESULT_SELECTION      205
DECENTRALIZED_SELECTION_FOLLOWUP    205
LOTTERY_RESULT                      205
LOTTERY_STATUS                      205
DATE_REQUEST_STOP                   182
FINANCING                             0
DATE_FIRST_ENROL_REQUEST            152
STUDY_CHECK_PARTICIPATION             0
DATE_STUDY_CHECK                    175
STUDY_CHECK_RESULT                  175
STUDY_CHECK_ADMISSION               175
EXAM_ADMINISTERED                     0
DATE_EXAM_STARTED                     0
EXAM_PROG_DETAILS                     0
DATE_EXAM_CONDUCTED                  89
EXAM_FINAL_RESULT                    89
EXAM_GRADE                            0
HONORS_PROG_PARTICIPATION             0
PRIOR_EDUCATION                       0
PRIOR_SCHOOL_NAME                     0
PRIOR_FINAL_EXAM_DATE                58
PRIOR_DIMPLOMA_OBTAINTION             0
PRIOR_EXTENSION_CODE                 73
PRIOR_EXTENSION_NAME                 73
PRIOR_VERIFICATION_STATUS             0
PRIOR_VERIFICATION_DATE              44
BIRTH_DATE                            0
GENDER                                0
NATIONALITY                           0
YEAR_STARTED_HU                       0
PRIOR_QUALIFICATION_TYPE              1
INFO_CURRENT                          0
dtype: int64

In [278]:
osiris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 49 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   STUDENT_NUM                       211 non-null    int64
 1   STUDY_PROGRAM                     211 non-null    object
 2   MAIN_STUDY_PROGRAM                211 non-null    object
 3   ACADEMIC_YEAR                     211 non-null    int64
 4   START_DATE                        211 non-null    object
 5   END_DATE                          211 non-null    object
 6   ENROLLMENT_TYPE                   211 non-null    object
 7   EXAM_TYPE                         211 non-null    object
 8   FULL_TIME_PART                    211 non-null    object
 9   PROGRAM_ACTIVE_CODE               211 non-null    int64
 10  DATE_ACTIVE_CODE_MODIFIED         211 non-null    object
 11  DATE_WITHRAWAL_PRE-REGIS          6 non-null      object
 12  WITHDRAWAL_REASON                 61 non-null     object
 13  HIGHER_EDU_REGISTER               211 non-null    int64
 14  DATE_REGIS_PROOF                  155 non-null    object
 15  DATE_ENROLLMENT_REQUEST           211 non-null    object
 16  LOTTERY_FORM                      183 non-null    object
 17  DECENTRALIZED_RESULT_SELECTION    6 non-null      object
 18  DECENTRALIZED_SELECTION_FOLLOWUP  6 non-null      float64
 19  LOTTERY_RESULT                    6 non-null      object
 20  LOTTERY_STATUS                    6 non-null      object
 21  DATE_REQUEST_STOP                 29 non-null     object
 22  FINANCING                         211 non-null    object
 23  DATE_FIRST_ENROL_REQUEST          59 non-null     object
 24  STUDY_CHECK_PARTICIPATION         211 non-null    object
 25  DATE_STUDY_CHECK                  36 non-null     object
 26  STUDY_CHECK_RESULT                36 non-null     object
 27  STUDY_CHECK_ADMISSION             36 non-null     object
 28  EXAM_ADMINISTERED                 211 non-null    object
 29  DATE_EXAM_STARTED                 211 non-null    datetime64[ns]
 30  EXAM_PROG_DETAILS                 211 non-null    object
 31  DATE_EXAM_CONDUCTED               122 non-null    datetime64[ns]
 32  EXAM_FINAL_RESULT                 122 non-null    object
 33  EXAM_GRADE                        211 non-null    object
 34  HONORS_PROG_PARTICIPATION         211 non-null    object
 35  PRIOR_EDUCATION                   211 non-null    object
 36  PRIOR_SCHOOL_NAME                 211 non-null    object
 37  PRIOR_FINAL_EXAM_DATE             153 non-null    datetime64[ns]
 38  PRIOR_DIMPLOMA_OBTAINTION         211 non-null    object
 39  PRIOR_EXTENSION_CODE              138 non-null    float64
 40  PRIOR_EXTENSION_NAME              138 non-null    object
 41  PRIOR_VERIFICATION_STATUS         211 non-null    object
 42  PRIOR_VERIFICATION_DATE           167 non-null    datetime64[ns]
 43  BIRTH_DATE                        211 non-null    datetime64[ns]
 44  GENDER                            211 non-null    object
 45  NATIONALITY                       211 non-null    object
 46  YEAR_STARTED_HU                   211 non-null    int64
 47  PRIOR_QUALIFICATION_TYPE          210 non-null    object
 48  INFO_CURRENT                      211 non-null    object
dtypes: datetime64[ns](5), float64(2), int64(5), object(37)
memory usage: 80.9+ KB

In [279]:
# Missing values imputation: we see there are missing values for float and object data types. 
# For the float, KNN can can be used, its a good practice to reshuffle the dataframe before applying KNN
# For the object, mode can be used

In [280]:
# reshuffle dataframe
osiris = osiris.sample(frac=1).reset_index(drop=True)

In [281]:
from sklearn.impute import KNNImputer

# Identify columns with float data type
float_columns = osiris.select_dtypes(include=['float']).columns

# Filter columns that have missing values
float_columns_with_missing_values = [col for col in float_columns if osiris[col].isnull().any()]

print("Float columns with missing values:", float_columns_with_missing_values)

# Create a KNNImputer instance with K=25
imputer = KNNImputer(n_neighbors=25)

# Impute the missing values for the float columns
osiris[float_columns_with_missing_values] = imputer.fit_transform(osiris[float_columns_with_missing_values])

# Verify that there are no missing values left in the float columns
print(osiris[float_columns_with_missing_values].isnull().sum())

Float columns with missing values: ['DECENTRALIZED_SELECTION_FOLLOWUP', 'PRIOR_EXTENSION_CODE']
DECENTRALIZED_SELECTION_FOLLOWUP    0
PRIOR_EXTENSION_CODE                0
dtype: int64

In [282]:
# Identify columns with object data type
object_columns = osiris.select_dtypes(include=['object']).columns

# Filter columns that have missing values
object_columns_with_missing_values = [col for col in object_columns if osiris[col].isnull().any()]

print("Object columns with missing values:", object_columns_with_missing_values)

# Impute missing values with the mode for each column
for col in object_columns_with_missing_values:
    mode_value = osiris[col].mode()[0]  # Get the mode (most frequent value)
    osiris[col].fillna(mode_value, inplace=True)

# Verify that there are no missing values left in the object columns
print(osiris[object_columns_with_missing_values].isnull().sum())

Object columns with missing values: ['DATE_WITHRAWAL_PRE-REGIS', 'WITHDRAWAL_REASON', 'DATE_REGIS_PROOF', 'LOTTERY_FORM', 'DECENTRALIZED_RESULT_SELECTION', 'LOTTERY_RESULT', 'LOTTERY_STATUS', 'DATE_REQUEST_STOP', 'DATE_FIRST_ENROL_REQUEST', 'DATE_STUDY_CHECK', 'STUDY_CHECK_RESULT', 'STUDY_CHECK_ADMISSION', 'EXAM_FINAL_RESULT', 'PRIOR_EXTENSION_NAME', 'PRIOR_QUALIFICATION_TYPE']
DATE_WITHRAWAL_PRE-REGIS          0
WITHDRAWAL_REASON                 0
DATE_REGIS_PROOF                  0
LOTTERY_FORM                      0
DECENTRALIZED_RESULT_SELECTION    0
LOTTERY_RESULT                    0
LOTTERY_STATUS                    0
DATE_REQUEST_STOP                 0
DATE_FIRST_ENROL_REQUEST          0
DATE_STUDY_CHECK                  0
STUDY_CHECK_RESULT                0
STUDY_CHECK_ADMISSION             0
EXAM_FINAL_RESULT                 0
PRIOR_EXTENSION_NAME              0
PRIOR_QUALIFICATION_TYPE          0
dtype: int64

In [283]:
osiris.isnull().sum()

STUDENT_NUM                          0
STUDY_PROGRAM                        0
MAIN_STUDY_PROGRAM                   0
ACADEMIC_YEAR                        0
START_DATE                           0
END_DATE                             0
ENROLLMENT_TYPE                      0
EXAM_TYPE                            0
FULL_TIME_PART                       0
PROGRAM_ACTIVE_CODE                  0
DATE_ACTIVE_CODE_MODIFIED            0
DATE_WITHRAWAL_PRE-REGIS             0
WITHDRAWAL_REASON                    0
HIGHER_EDU_REGISTER                  0
DATE_REGIS_PROOF                     0
DATE_ENROLLMENT_REQUEST              0
LOTTERY_FORM                         0
DECENTRALIZED_RESULT_SELECTION       0
DECENTRALIZED_SELECTION_FOLLOWUP     0
LOTTERY_RESULT                       0
LOTTERY_STATUS                       0
DATE_REQUEST_STOP                    0
FINANCING                            0
DATE_FIRST_ENROL_REQUEST             0
STUDY_CHECK_PARTICIPATION            0
DATE_STUDY_CHECK                     0
STUDY_CHECK_RESULT                   0
STUDY_CHECK_ADMISSION                0
EXAM_ADMINISTERED                    0
DATE_EXAM_STARTED                    0
EXAM_PROG_DETAILS                    0
DATE_EXAM_CONDUCTED                 89
EXAM_FINAL_RESULT                    0
EXAM_GRADE                           0
HONORS_PROG_PARTICIPATION            0
PRIOR_EDUCATION                      0
PRIOR_SCHOOL_NAME                    0
PRIOR_FINAL_EXAM_DATE               58
PRIOR_DIMPLOMA_OBTAINTION            0
PRIOR_EXTENSION_CODE                 0
PRIOR_EXTENSION_NAME                 0
PRIOR_VERIFICATION_STATUS            0
PRIOR_VERIFICATION_DATE             44
BIRTH_DATE                           0
GENDER                               0
NATIONALITY                          0
YEAR_STARTED_HU                      0
PRIOR_QUALIFICATION_TYPE             0
INFO_CURRENT                         0
dtype: int64

In [284]:
# Function to fill datetime columns with median date
def fill_datetime_columns_with_median(osiris):
    for col in osiris.select_dtypes(include=['datetime']):
        median_date = osiris[col].dropna().median()
        osiris[col].fillna(median_date, inplace=True)
    return osiris

# Apply the function to the DataFrame
osiris = fill_datetime_columns_with_median(osiris)

In [285]:
osiris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 49 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   STUDENT_NUM                       211 non-null    int64
 1   STUDY_PROGRAM                     211 non-null    object
 2   MAIN_STUDY_PROGRAM                211 non-null    object
 3   ACADEMIC_YEAR                     211 non-null    int64
 4   START_DATE                        211 non-null    object
 5   END_DATE                          211 non-null    object
 6   ENROLLMENT_TYPE                   211 non-null    object
 7   EXAM_TYPE                         211 non-null    object
 8   FULL_TIME_PART                    211 non-null    object
 9   PROGRAM_ACTIVE_CODE               211 non-null    int64
 10  DATE_ACTIVE_CODE_MODIFIED         211 non-null    object
 11  DATE_WITHRAWAL_PRE-REGIS          211 non-null    object
 12  WITHDRAWAL_REASON                 211 non-null    object
 13  HIGHER_EDU_REGISTER               211 non-null    int64
 14  DATE_REGIS_PROOF                  211 non-null    object
 15  DATE_ENROLLMENT_REQUEST           211 non-null    object
 16  LOTTERY_FORM                      211 non-null    object
 17  DECENTRALIZED_RESULT_SELECTION    211 non-null    object
 18  DECENTRALIZED_SELECTION_FOLLOWUP  211 non-null    float64
 19  LOTTERY_RESULT                    211 non-null    object
 20  LOTTERY_STATUS                    211 non-null    object
 21  DATE_REQUEST_STOP                 211 non-null    object
 22  FINANCING                         211 non-null    object
 23  DATE_FIRST_ENROL_REQUEST          211 non-null    object
 24  STUDY_CHECK_PARTICIPATION         211 non-null    object
 25  DATE_STUDY_CHECK                  211 non-null    object
 26  STUDY_CHECK_RESULT                211 non-null    object
 27  STUDY_CHECK_ADMISSION             211 non-null    object
 28  EXAM_ADMINISTERED                 211 non-null    object
 29  DATE_EXAM_STARTED                 211 non-null    datetime64[ns]
 30  EXAM_PROG_DETAILS                 211 non-null    object
 31  DATE_EXAM_CONDUCTED               211 non-null    datetime64[ns]
 32  EXAM_FINAL_RESULT                 211 non-null    object
 33  EXAM_GRADE                        211 non-null    object
 34  HONORS_PROG_PARTICIPATION         211 non-null    object
 35  PRIOR_EDUCATION                   211 non-null    object
 36  PRIOR_SCHOOL_NAME                 211 non-null    object
 37  PRIOR_FINAL_EXAM_DATE             211 non-null    datetime64[ns]
 38  PRIOR_DIMPLOMA_OBTAINTION         211 non-null    object
 39  PRIOR_EXTENSION_CODE              211 non-null    float64
 40  PRIOR_EXTENSION_NAME              211 non-null    object
 41  PRIOR_VERIFICATION_STATUS         211 non-null    object
 42  PRIOR_VERIFICATION_DATE           211 non-null    datetime64[ns]
 43  BIRTH_DATE                        211 non-null    datetime64[ns]
 44  GENDER                            211 non-null    object
 45  NATIONALITY                       211 non-null    object
 46  YEAR_STARTED_HU                   211 non-null    int64
 47  PRIOR_QUALIFICATION_TYPE          211 non-null    object
 48  INFO_CURRENT                      211 non-null    object
dtypes: datetime64[ns](5), float64(2), int64(5), object(37)
memory usage: 80.9+ KB

In [286]:
# Print value counts for all columns
for col in osiris.columns:
    print(f"Value counts for column: {col}")
    print(osiris[col].value_counts(dropna=False))  # include NaN values in the count
    print("\n" + "="*50 + "\n")

Value counts for column: STUDENT_NUM
STUDENT_NUM
1771302    56
1699140    48
1766090    32
1769163    30
1768080    30
1765243    12
1764427     3
Name: count, dtype: int64

==================================================

Value counts for column: STUDY_PROGRAM
STUDY_PROGRAM
BARE         56
BJDE         42
BMLM         32
BTICIC       30
BTLCCY       30
BGHBFY       12
BJSCICM       6
BOPAPABOV     3
Name: count, dtype: int64

==================================================

Value counts for column: MAIN_STUDY_PROGRAM
MAIN_STUDY_PROGRAM
BARE         56
BJDE         48
BMLM         32
BTLCCY       30
BTICIC       30
BGHBFY       12
BOPAPABOV     3
Name: count, dtype: int64

==================================================

Value counts for column: ACADEMIC_YEAR
ACADEMIC_YEAR
2019    49
2020    44
2021    38
2022    28
2023    14
2016    12
2017    12
2024     8
2018     6
Name: count, dtype: int64

==================================================

Value counts for column: START_DATE
START_DATE
2021-09-01 00:00:00.0000000    38
2019-09-01 00:00:00.0000000    37
2020-09-01 00:00:00.0000000    34
2022-09-01 00:00:00.0000000    20
2023-09-01 00:00:00.0000000    14
2016-09-01 00:00:00.0000000    12
2024-09-01 00:00:00.0000000     8
2020-07-01 00:00:00.0000000     8
2022-11-11 00:00:00.0000000     8
2017-12-21 00:00:00.0000000     6
2017-09-01 00:00:00.0000000     6
2021-04-21 00:00:00.0000000     6
2018-09-01 00:00:00.0000000     6
2020-02-01 00:00:00.0000000     4
2021-03-01 00:00:00.0000000     4
Name: count, dtype: int64

==================================================

Value counts for column: END_DATE
END_DATE
2021-08-31 00:00:00.0000000    38
2020-08-31 00:00:00.0000000    30
2022-08-31 00:00:00.0000000    26
2024-08-31 00:00:00.0000000    14
2023-08-31 00:00:00.0000000    14
2017-08-31 00:00:00.0000000    12
2025-08-31 00:00:00.0000000     8
2020-06-30 00:00:00.0000000     8
2021-09-30 00:00:00.0000000     8
2020-01-31 00:00:00.0000000     8
2022-11-10 00:00:00.0000000     8
2018-08-31 00:00:00.0000000     6
2017-12-20 00:00:00.0000000     6
2023-02-28 00:00:00.0000000     6
2021-04-20 00:00:00.0000000     6
2019-08-31 00:00:00.0000000     6
2022-01-31 00:00:00.0000000     4
2019-10-31 00:00:00.0000000     3
Name: count, dtype: int64

==================================================

Value counts for column: ENROLLMENT_TYPE
ENROLLMENT_TYPE
S    211
Name: count, dtype: int64

==================================================

Value counts for column: EXAM_TYPE
EXAM_TYPE
B    108
D    103
Name: count, dtype: int64

==================================================

Value counts for column: FULL_TIME_PART
FULL_TIME_PART
V    178
D     33
Name: count, dtype: int64

==================================================

Value counts for column: PROGRAM_ACTIVE_CODE
PROGRAM_ACTIVE_CODE
4    205
0      6
Name: count, dtype: int64

==================================================

Value counts for column: DATE_ACTIVE_CODE_MODIFIED
DATE_ACTIVE_CODE_MODIFIED
2024-05-13 13:05:24.0000000    8
2021-07-22 09:27:05.0000000    8
2020-07-16 14:50:23.0000000    8
2019-07-10 08:01:31.0000000    8
2020-07-24 09:57:38.0000000    8
2022-07-19 12:02:36.0000000    8
2022-12-19 10:40:50.0000000    8
2021-08-31 19:17:32.0000000    8
2019-08-23 09:03:15.0000000    8
2020-09-28 14:11:00.0000000    8
2023-06-27 15:06:18.0000000    8
2022-06-26 19:45:08.0000000    6
2017-08-10 12:17:45.0000000    6
2023-09-13 21:25:19.0000000    6
2021-07-10 18:55:02.0000000    6
2018-02-08 10:05:39.0000000    6
2021-09-24 10:24:26.0000000    6
2020-08-23 12:12:06.0000000    6
2019-07-18 15:06:26.0000000    6
2021-06-11 13:40:34.0000000    6
2019-07-31 12:41:10.0000000    6
2016-08-27 00:00:00.0000000    6
2022-05-10 12:20:41.0000000    6
2021-08-12 15:50:56.0000000    6
2020-08-30 17:20:20.0000000    6
2016-04-28 14:54:22.0000000    6
2019-08-27 09:21:13.0000000    6
2018-08-20 14:08:44.0000000    6
2020-07-07 20:19:24.0000000    6
2021-02-17 09:20:11.0000000    4
2019-11-08 11:47:33.0000000    4
2021-09-30 09:38:06.0000000    4
2019-06-17 07:54:45.0000000    3
Name: count, dtype: int64

==================================================

Value counts for column: DATE_WITHRAWAL_PRE-REGIS
DATE_WITHRAWAL_PRE-REGIS
2016-06-02 00:00:00.0000000    211
Name: count, dtype: int64

==================================================

Value counts for column: WITHDRAWAL_REASON
WITHDRAWAL_REASON
VB           183
PROP_EXAM     28
Name: count, dtype: int64

==================================================

Value counts for column: HIGHER_EDU_REGISTER
HIGHER_EDU_REGISTER
39205    56
34092    42
35522    32
30020    30
34396    30
34570    12
34430     6
34808     3
Name: count, dtype: int64

==================================================

Value counts for column: DATE_REGIS_PROOF
DATE_REGIS_PROOF
2019-07-18 00:00:00.0000000    72
2021-07-29 00:00:00.0000000    14
2017-08-14 00:00:00.0000000    12
2020-07-13 00:00:00.0000000    12
2020-07-28 00:00:00.0000000     8
2021-09-02 00:00:00.0000000     8
2019-08-27 00:00:00.0000000     8
2020-07-21 00:00:00.0000000     8
2021-09-28 00:00:00.0000000     6
2019-08-29 00:00:00.0000000     6
2016-08-29 00:00:00.0000000     6
2019-08-06 00:00:00.0000000     6
2020-09-01 00:00:00.0000000     6
2018-08-23 00:00:00.0000000     6
2021-08-17 00:00:00.0000000     6
2020-08-25 00:00:00.0000000     6
2019-08-13 00:00:00.0000000     6
2021-02-18 00:00:00.0000000     4
2019-11-12 00:00:00.0000000     4
2021-09-30 00:00:00.0000000     4
2019-09-03 00:00:00.0000000     3
Name: count, dtype: int64

==================================================

Value counts for column: DATE_ENROLLMENT_REQUEST
DATE_ENROLLMENT_REQUEST
2022-05-10 00:00:00.0000000    14
2024-05-13 00:00:00.0000000     8
2019-04-25 00:00:00.0000000     8
2020-06-11 00:00:00.0000000     8
2021-06-08 00:00:00.0000000     8
2021-08-31 00:00:00.0000000     8
2019-07-10 00:00:00.0000000     8
2020-03-20 00:00:00.0000000     8
2022-12-19 10:40:50.0000000     8
2023-06-26 00:00:00.0000000     8
2020-09-28 14:11:00.0000000     8
2022-06-12 00:00:00.0000000     6
2017-07-29 00:00:00.0000000     6
2018-02-08 10:05:39.0000000     6
2021-07-01 00:00:00.0000000     6
2023-08-30 00:00:00.0000000     6
2020-06-12 00:00:00.0000000     6
2019-05-15 00:00:00.0000000     6
2021-06-11 13:40:34.0000000     6
2019-06-10 00:00:00.0000000     6
2016-03-01 00:00:00.0000000     6
2021-09-24 00:00:00.0000000     6
2021-08-12 00:00:00.0000000     6
2020-08-27 00:00:00.0000000     6
2016-04-28 00:00:00.0000000     6
2019-04-30 00:00:00.0000000     6
2018-08-05 00:00:00.0000000     6
2020-06-20 00:00:00.0000000     6
2021-02-03 00:00:00.0000000     4
2019-04-23 00:00:00.0000000     4
2021-08-29 00:00:00.0000000     4
2019-04-18 00:00:00.0000000     3
Name: count, dtype: int64

==================================================

Value counts for column: LOTTERY_FORM
LOTTERY_FORM
N    205
C      6
Name: count, dtype: int64

==================================================

Value counts for column: DECENTRALIZED_RESULT_SELECTION
DECENTRALIZED_RESULT_SELECTION
S    211
Name: count, dtype: int64

==================================================

Value counts for column: DECENTRALIZED_SELECTION_FOLLOWUP
DECENTRALIZED_SELECTION_FOLLOWUP
295.0    211
Name: count, dtype: int64

==================================================

Value counts for column: LOTTERY_RESULT
LOTTERY_RESULT
I    211
Name: count, dtype: int64

==================================================

Value counts for column: LOTTERY_STATUS
LOTTERY_STATUS
V    211
Name: count, dtype: int64

==================================================

Value counts for column: DATE_REQUEST_STOP
DATE_REQUEST_STOP
2020-01-31 00:00:00.0000000    190
2021-09-30 00:00:00.0000000      8
2023-02-07 00:00:00.0000000      6
2022-01-30 00:00:00.0000000      4
2019-10-09 00:00:00.0000000      3
Name: count, dtype: int64

==================================================

Value counts for column: FINANCING
FINANCING
J    199
M     12
Name: count, dtype: int64

==================================================

Value counts for column: DATE_FIRST_ENROL_REQUEST
DATE_FIRST_ENROL_REQUEST
2019-04-30 00:00:00.0000000    166
2016-03-01 00:00:00.0000000     12
2020-03-20 00:00:00.0000000      8
2019-04-25 00:00:00.0000000      8
2019-05-15 00:00:00.0000000      6
2020-08-19 00:00:00.0000000      4
2019-04-23 00:00:00.0000000      4
2019-04-18 00:00:00.0000000      3
Name: count, dtype: int64

==================================================

Value counts for column: STUDY_CHECK_PARTICIPATION
STUDY_CHECK_PARTICIPATION
NVT    166
J       39
N        6
Name: count, dtype: int64

==================================================

Value counts for column: DATE_STUDY_CHECK
DATE_STUDY_CHECK
2019-06-21 00:00:00.0000000    183
2020-06-05 00:00:00.0000000      8
2019-08-21 00:00:00.0000000      8
2019-08-22 00:00:00.0000000      6
2016-06-02 00:00:00.0000000      6
Name: count, dtype: int64

==================================================

Value counts for column: STUDY_CHECK_RESULT
STUDY_CHECK_RESULT
T     199
P       6
ND      6
Name: count, dtype: int64

==================================================

Value counts for column: STUDY_CHECK_ADMISSION
STUDY_CHECK_ADMISSION
JT    191
JO      8
JP      6
NN      6
Name: count, dtype: int64

==================================================

Value counts for column: EXAM_ADMINISTERED
EXAM_ADMINISTERED
B    110
D    101
Name: count, dtype: int64

==================================================

Value counts for column: DATE_EXAM_STARTED
DATE_EXAM_STARTED
2019-09-01    77
2020-09-01    31
2021-09-01    28
2016-09-01    24
2017-09-01    24
2020-01-01    15
2020-02-01    12
Name: count, dtype: int64

==================================================

Value counts for column: EXAM_PROG_DETAILS
EXAM_PROG_DETAILS
ADR-HBRV-D-20      28
ADR-HBRV-B-21      28
JDE-BV-17          24
JDE-DV-16          24
MBLM-BV-19         16
MBLM-DV-19         16
TCHY-PROPD-19      15
TICT-VBAOPIC-20    15
TICT-VPOPICT-19    15
TCHY-BASD-19       15
G-EXTERN-17        12
OTVP-DT-19          3
Name: count, dtype: int64

==================================================

Value counts for column: DATE_EXAM_CONDUCTED
DATE_EXAM_CONDUCTED
2022-02-01    113
2022-11-10     28
2017-12-20     24
2020-06-30     16
2021-04-20     15
2023-02-02     15
Name: count, dtype: int64

==================================================

Value counts for column: EXAM_FINAL_RESULT
EXAM_FINAL_RESULT
---    196
MG      15
Name: count, dtype: int64

==================================================

Value counts for column: EXAM_GRADE
EXAM_GRADE
J    128
N     83
Name: count, dtype: int64

==================================================

Value counts for column: HONORS_PROG_PARTICIPATION
HONORS_PROG_PARTICIPATION
N    211
Name: count, dtype: int64

==================================================

Value counts for column: PRIOR_EDUCATION
PRIOR_EDUCATION
591            62
611            51
SL 00591-01    17
379            16
92632          14
601            10
3              10
91711          10
179             8
741             8
371             3
361             1
711             1
Name: count, dtype: int64

==================================================

Value counts for column: PRIOR_SCHOOL_NAME
PRIOR_SCHOOL_NAME
Hogeschool Utrecht                                                        110
Gereformeerde Scholengemeenschap Randstad Gymnasium Atheneum HAVO VMBO     16
De Haagse Hogeschool; Den Haag                                             14
Regionaal Opleidingen Centrum                                              14
Stichting ROC Midden Nederland                                             10
ROC West-Brabant                                                           10
Hogeschool Utrecht; Utrecht                                                10
Universiteit Utrecht; Utrecht                                               8
Het Schoonhovens College                                                    8
Hogeschool van Amsterdam                                                    6
Martinus College Christelijke Scholengemeenschap voor LYC HAVO MAVO VB      3
Scholengemeenschap voor Voortgezet Vrije Schoolonderwijs                    1
onbekend, zie diploma                                                       1
Name: count, dtype: int64

==================================================

Value counts for column: PRIOR_FINAL_EXAM_DATE
PRIOR_FINAL_EXAM_DATE
2018-06-13    66
2022-02-01    16
2016-06-16    16
2017-12-20    16
2017-09-26    14
2022-11-10    14
2010-07-06    10
2021-04-20    10
2015-06-26    10
2023-02-02    10
2019-05-09    10
2020-06-30     8
2018-07-19     3
2017-06-15     3
2022-01-26     3
1988-06-10     1
1990-05-18     1
Name: count, dtype: int64

==================================================

Value counts for column: PRIOR_DIMPLOMA_OBTAINTION
PRIOR_DIMPLOMA_OBTAINTION
J    153
N     58
Name: count, dtype: int64

==================================================

Value counts for column: PRIOR_EXTENSION_CODE
PRIOR_EXTENSION_CODE
36166.072464    71
34092.000000    32
39205.000000    28
34396.000000    20
35522.000000    16
35158.000000    14
30020.000000    10
50950.000000     8
34572.000000     6
34570.000000     3
36722.080000     2
34808.000000     1
Name: count, dtype: int64

==================================================

Value counts for column: PRIOR_EXTENSION_NAME
PRIOR_EXTENSION_NAME
B Communication and Multimedia Design         105
B HBO - Rechten                                28
B Chemie                                       20
B Logistics Management                         16
B Pedagogiek                                   14
B HBO-ICT                                      10
B Economie en Bedrijfseconomie                  8
B Opleiding tot Oefentherapeut-Mensendieck      3
B Opleiding tot Oefentherapeut                  3
B Opleiding tot Fysiotherapeut                  3
B Opleiding tot leraar Basisonderwijs           1
Name: count, dtype: int64

==================================================

Value counts for column: PRIOR_VERIFICATION_STATUS
PRIOR_VERIFICATION_STATUS
GD    131
N      44
GV     25
DD     11
Name: count, dtype: int64

==================================================

Value counts for column: PRIOR_VERIFICATION_DATE
PRIOR_VERIFICATION_DATE
2020-06-30    52
2022-02-01    16
2017-12-20    16
2016-06-16    16
2022-12-19    14
2022-11-10    14
2017-09-26    14
2021-04-20    10
2010-07-06    10
2019-05-21    10
2021-09-24    10
2023-02-02    10
2018-06-13     8
2017-06-15     3
2018-07-19     3
2022-01-26     3
2019-05-10     1
2019-06-17     1
Name: count, dtype: int64

==================================================

Value counts for column: BIRTH_DATE
BIRTH_DATE
1997-03-03    56
1999-10-08    48
2000-03-08    32
1989-12-30    30
1994-01-15    30
1999-02-23    12
1968-07-30     3
Name: count, dtype: int64

==================================================

Value counts for column: GENDER
GENDER
V    119
M     92
Name: count, dtype: int64

==================================================

Value counts for column: NATIONALITY
NATIONALITY
NL     181
XXX     30
Name: count, dtype: int64

==================================================

Value counts for column: YEAR_STARTED_HU
YEAR_STARTED_HU
2019    163
2016     48
Name: count, dtype: int64

==================================================

Value counts for column: PRIOR_QUALIFICATION_TYPE
PRIOR_QUALIFICATION_TYPE
HBO     131
MBO      24
VWO      19
HAVO     19
VO       10
WO        8
Name: count, dtype: int64

==================================================

Value counts for column: INFO_CURRENT
INFO_CURRENT
J    201
N     10
Name: count, dtype: int64

==================================================

The results above indicate that:

# EXAM_FINAL_RESULT has --- as special characters
replace --- with unknown
# Study_Program and Main_Study_Program are same. 
delete Main_Study_Program
# NATIONALITEIT has XXX
Replace XXX with others
# Some columns have no variation, just same value throughout: 
keep them, with more data, there might be other values
# Values for PRIOR_SCHOOL_NAME & PRIOR_EXTENSION_NAME are sentences
Reduce sentences and make them categories
# PRIOR_EDUCATION values are int with very high magnitude, are these IDs or they have other meanings
Remove SL- from the strings
# STUDENT_NUMBER is not unique, there are only 7 unique student numbers,
group dataframe by STUDENT_NUMBER

In [287]:
osiris.columns

Index(['STUDENT_NUM', 'STUDY_PROGRAM', 'MAIN_STUDY_PROGRAM', 'ACADEMIC_YEAR',
       'START_DATE', 'END_DATE', 'ENROLLMENT_TYPE', 'EXAM_TYPE',
       'FULL_TIME_PART', 'PROGRAM_ACTIVE_CODE', 'DATE_ACTIVE_CODE_MODIFIED',
       'DATE_WITHRAWAL_PRE-REGIS', 'WITHDRAWAL_REASON', 'HIGHER_EDU_REGISTER',
       'DATE_REGIS_PROOF', 'DATE_ENROLLMENT_REQUEST', 'LOTTERY_FORM',
       'DECENTRALIZED_RESULT_SELECTION', 'DECENTRALIZED_SELECTION_FOLLOWUP',
       'LOTTERY_RESULT', 'LOTTERY_STATUS', 'DATE_REQUEST_STOP', 'FINANCING',
       'DATE_FIRST_ENROL_REQUEST', 'STUDY_CHECK_PARTICIPATION',
       'DATE_STUDY_CHECK', 'STUDY_CHECK_RESULT', 'STUDY_CHECK_ADMISSION',
       'EXAM_ADMINISTERED', 'DATE_EXAM_STARTED', 'EXAM_PROG_DETAILS',
       'DATE_EXAM_CONDUCTED', 'EXAM_FINAL_RESULT', 'EXAM_GRADE',
       'HONORS_PROG_PARTICIPATION', 'PRIOR_EDUCATION', 'PRIOR_SCHOOL_NAME',
       'PRIOR_FINAL_EXAM_DATE', 'PRIOR_DIMPLOMA_OBTAINTION',
       'PRIOR_EXTENSION_CODE', 'PRIOR_EXTENSION_NAME',
       'PRIOR_VERIFICATION_STATUS', 'PRIOR_VERIFICATION_DATE', 'BIRTH_DATE',
       'GENDER', 'NATIONALITY', 'YEAR_STARTED_HU', 'PRIOR_QUALIFICATION_TYPE',
       'INFO_CURRENT'],
      dtype='object')

In [288]:
#replace --- with unknown
osiris['EXAM_FINAL_RESULT'] = osiris['EXAM_FINAL_RESULT'].apply(lambda x: x.replace('---','unknown')) 
osiris['EXAM_FINAL_RESULT'].value_counts()

EXAM_FINAL_RESULT
unknown    196
MG          15
Name: count, dtype: int64

In [289]:
#delete Main_Study_Program
del osiris['MAIN_STUDY_PROGRAM']

In [290]:
#Replace XXX with others
osiris['NATIONALITY'] = osiris['NATIONALITY'].apply(lambda x: x.replace('XXX','others')) 
osiris['NATIONALITY'].value_counts()

NATIONALITY
NL        181
others     30
Name: count, dtype: int64

In [291]:
#Reduce sentences and make them categories for PRIOR_SCHOOL_NAME
osiris['PRIOR_SCHOOL_NAME'].value_counts()

PRIOR_SCHOOL_NAME
Hogeschool Utrecht                                                        110
Gereformeerde Scholengemeenschap Randstad Gymnasium Atheneum HAVO VMBO     16
De Haagse Hogeschool; Den Haag                                             14
Regionaal Opleidingen Centrum                                              14
Stichting ROC Midden Nederland                                             10
ROC West-Brabant                                                           10
Hogeschool Utrecht; Utrecht                                                10
Universiteit Utrecht; Utrecht                                               8
Het Schoonhovens College                                                    8
Hogeschool van Amsterdam                                                    6
Martinus College Christelijke Scholengemeenschap voor LYC HAVO MAVO VB      3
Scholengemeenschap voor Voortgezet Vrije Schoolonderwijs                    1
onbekend, zie diploma                                                       1
Name: count, dtype: int64

In [292]:
# Function to replace sentence with the first letter of each word
def abbreviate_sentence(sentence):
    if pd.isna(sentence):  # Handle NaN values
        return sentence
    words = sentence.split()
    return ''.join([word[0].upper() for word in words])

In [293]:
# Apply the function to the PRIOR_SCHOOL_NAME column
osiris['PRIOR_SCHOOL_NAME'] = osiris['PRIOR_SCHOOL_NAME'].apply(abbreviate_sentence)
osiris['PRIOR_SCHOOL_NAME'].value_counts()

PRIOR_SCHOOL_NAME
HU           110
GSRGAHV       16
DHHDH         14
ROC           14
SRMN          10
RW            10
HUU           10
UUU            8
HSC            8
HVA            6
MCCSVLHMV      3
SVVVS          1
OZD            1
Name: count, dtype: int64

In [294]:
#Reduce sentences and make them categories for PRIOR_EXTENSION_NAME 
osiris['PRIOR_EXTENSION_NAME'].value_counts()

PRIOR_EXTENSION_NAME
B Communication and Multimedia Design         105
B HBO - Rechten                                28
B Chemie                                       20
B Logistics Management                         16
B Pedagogiek                                   14
B HBO-ICT                                      10
B Economie en Bedrijfseconomie                  8
B Opleiding tot Oefentherapeut-Mensendieck      3
B Opleiding tot Oefentherapeut                  3
B Opleiding tot Fysiotherapeut                  3
B Opleiding tot leraar Basisonderwijs           1
Name: count, dtype: int64

In [295]:
osiris['PRIOR_EXTENSION_NAME'] = osiris['PRIOR_EXTENSION_NAME'].apply(abbreviate_sentence)
osiris['PRIOR_EXTENSION_NAME'].value_counts()

PRIOR_EXTENSION_NAME
BCAMD    105
BH-R      28
BC        20
BLM       16
BP        14
BH        10
BEEB       8
BOTO       6
BOTF       3
BOTLB      1
Name: count, dtype: int64

In [296]:
osiris['PRIOR_EDUCATION'].value_counts()

PRIOR_EDUCATION
591            62
611            51
SL 00591-01    17
379            16
92632          14
601            10
3              10
91711          10
179             8
741             8
371             3
361             1
711             1
Name: count, dtype: int64

In [297]:
# Replace SL 00591-01 with 591 from the strings of PRIOR_EDUCATION
osiris['PRIOR_EDUCATION'] = osiris['PRIOR_EDUCATION'].astype(str)
osiris['PRIOR_EDUCATION'] = osiris['PRIOR_EDUCATION'].apply(lambda x: x.replace('SL 00591-01','591'))
osiris['PRIOR_EDUCATION'].value_counts()

PRIOR_EDUCATION
591      79
611      51
379      16
92632    14
91711    10
3        10
601      10
741       8
179       8
371       3
361       1
711       1
Name: count, dtype: int64

# Groupby STUDENT_NUM and aggregate

In [298]:
# Firt identify and print columns with 'DATE' in their name
datetime_like_columns = []

for col in osiris.columns:
    if 'DATE' in col.upper():  # Check if 'DATE' is in the column name
        print(f"Column '{col}'")
        datetime_like_columns.append(col)

Column 'START_DATE'
Column 'END_DATE'
Column 'DATE_ACTIVE_CODE_MODIFIED'
Column 'DATE_WITHRAWAL_PRE-REGIS'
Column 'DATE_REGIS_PROOF'
Column 'DATE_ENROLLMENT_REQUEST'
Column 'DATE_REQUEST_STOP'
Column 'DATE_FIRST_ENROL_REQUEST'
Column 'DATE_STUDY_CHECK'
Column 'DATE_EXAM_STARTED'
Column 'DATE_EXAM_CONDUCTED'
Column 'PRIOR_FINAL_EXAM_DATE'
Column 'PRIOR_VERIFICATION_DATE'
Column 'BIRTH_DATE'

In [300]:
# Convert identified columns to datetime format
for col in datetime_like_columns:
    osiris[col] = pd.to_datetime(osiris[col], errors='coerce').dt.date

# Display the updated DataFrame
osiris

,STUDENT_NUM,STUDY_PROGRAM,ACADEMIC_YEAR,START_DATE,END_DATE,ENROLLMENT_TYPE,EXAM_TYPE,FULL_TIME_PART,PROGRAM_ACTIVE_CODE,DATE_ACTIVE_CODE_MODIFIED,DATE_WITHRAWAL_PRE-REGIS,WITHDRAWAL_REASON,HIGHER_EDU_REGISTER,DATE_REGIS_PROOF,DATE_ENROLLMENT_REQUEST,LOTTERY_FORM,DECENTRALIZED_RESULT_SELECTION,DECENTRALIZED_SELECTION_FOLLOWUP,LOTTERY_RESULT,LOTTERY_STATUS,DATE_REQUEST_STOP,FINANCING,DATE_FIRST_ENROL_REQUEST,STUDY_CHECK_PARTICIPATION,DATE_STUDY_CHECK,STUDY_CHECK_RESULT,STUDY_CHECK_ADMISSION,EXAM_ADMINISTERED,DATE_EXAM_STARTED,EXAM_PROG_DETAILS,DATE_EXAM_CONDUCTED,EXAM_FINAL_RESULT,EXAM_GRADE,HONORS_PROG_PARTICIPATION,PRIOR_EDUCATION,PRIOR_SCHOOL_NAME,PRIOR_FINAL_EXAM_DATE,PRIOR_DIMPLOMA_OBTAINTION,PRIOR_EXTENSION_CODE,PRIOR_EXTENSION_NAME,PRIOR_VERIFICATION_STATUS,PRIOR_VERIFICATION_DATE,BIRTH_DATE,GENDER,NATIONALITY,YEAR_STARTED_HU,PRIOR_QUALIFICATION_TYPE,INFO_CURRENT
0,1771302,BARE,2024,2024-09-01,2025-08-31,S,B,V,4,2024-05-13,2016-06-02,VB,39205,2019-07-18,2024-05-13,N,S,295.0,I,V,2020-01-31,J,2019-04-30,NVT,2019-06-21,T,JT,D,2019-09-01,ADR-HBRV-D-20,2022-11-10,unknown,N,N,591,DHHDH,2018-06-13,N,35158.000000,BP,N,2020-06-30,1997-03-03,V,NL,2019,HBO,J
1,1768080,BTICIC,2023,2023-09-01,2024-08-31,S,D,V,4,2023-09-13,2016-06-02,VB,30020,2019-07-18,2023-08-30,N,S,295.0,I,V,2020-01-31,J,2019-04-30,NVT,2019-06-21,T,JT,B,2020-09-01,TICT-VBAOPIC-20,2022-02-01,unknown,J,N,3,SRMN,2015-06-26,J,36166.072464,BCAMD,N,2020-06-30,1994-01-15,M,others,2019,VWO,N
2,1769163,BTLCCY,2021,2021-09-01,2022-08-31,S,B,D,4,2021-07-10,2016-06-02,VB,34396,2021-07-29,2021-07-01,N,S,295.0,I,V,2020-01-31,J,2019-04-30,NVT,2019-06-21,T,JT,D,2019-09-01,TCHY-PROPD-19,2021-04-20,unknown,N,N,611,HU,2021-04-20,J,34396.000000,BC,GD,2021-04-20,1989-12-30,M,NL,2019,HBO,J
3,1699140,BJDE,2017,2017-12-21,2018-08-31,S,B,V,4,2018-02-08,2016-06-02,VB,34092,2017-08-14,2018-02-08,N,S,295.0,I,V,2020-01-31,J,2019-04-30,NVT,2019-06-21,T,JT,D,2016-09-01,JDE-DV-16,2017-12-20,unknown,N,N,591,HU,2022-02-01,J,34092.000000,BCAMD,GD,2022-02-01,1999-10-08,V,NL,2016,HBO,J
4,1765243,BGHBFY,2020,2021-03-01,2021-08-31,S,B,V,4,2021-02-17,2016-06-02,VB,34570,2021-02-18,2021-02-03,N,S,295.0,I,V,2020-01-31,M,2020-08-19,NVT,2019-06-21,T,JT,B,2020-02-01,G-EXTERN-17,2022-02-01,unknown,J,N,611,HVA,2018-07-19,J,34572.000000,BOTO,GD,2018-07-19,1999-02-23,V,NL,2019,HBO,J
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,1699140,BJDE,2021,2021-09-01,2022-08-31,S,B,V,4,2021-08-12,2016-06-02,VB,34092,2021-08-17,2021-08-12,N,S,295.0,I,V,2020-01-31,J,2019-04-30,NVT,2019-06-21,T,JT,D,2016-09-01,JDE-DV-16,2017-12-20,unknown,N,N,379,GSRGAHV,2016-06-16,J,36166.072464,BCAMD,GD,2016-06-16,1999-10-08,V,NL,2016,HAVO,J
207,1771302,BARE,2020,2020-09-01,2021-08-31,S,D,V,4,2020-07-16,2016-06-02,VB,39205,2020-07-21,2020-03-20,N,S,295.0,I,V,2020-01-31,J,2020-03-20,J,2020-06-05,T,JO,D,2019-09-01,ADR-HBRV-D-20,2022-11-10,unknown,N,N,591,DHHDH,2018-06-13,N,35158.000000,BP,N,2020-06-30,1997-03-03,V,NL,2019,HBO,J
208,1766090,BMLM,2019,2019-09-01,2020-06-30,S,D,V,4,2019-07-10,2016-06-02,PROP_EXAM,35522,2019-07-18,2019-04-25,N,S,295.0,I,V,2020-01-31,J,2019-04-25,J,2019-06-21,T,JT,D,2019-09-01,MBLM-DV-19,2020-06-30,unknown,N,N,611,HU,2020-06-30,J,35522.000000,BLM,GD,2020-06-30,2000-03-08,M,NL,2019,HBO,J
209,1771302,BARE,2024,2024-09-01,2025-08-31,S,B,V,4,2024-05-13,2016-06-02,VB,39205,2019-07-18,2024-05-13,N,S,295.0,I,V,2020-01-31,J,2019-04-30,NVT,2019-06-21,T,JT,B,2021-09-01,ADR-HBRV-B-21,2022-02-01,unknown,J,N,92632,ROC,2017-09-26,J,36166.072464,BCAMD,GD,2017-09-26,1997-03-03,V,NL,2019,MBO,J
210,1769163,BTLCCY,2019,2019-09-01,2020-08-31,S,D,D,4,2019-07-18,2016-06-02,VB,34396,2019-08-13,2019-05-15,N,S,295.0,I,V,2020-01-31,J,2019-05-15,N,2019-06-21,T,JT,B,2020-01-01,TCHY-BASD-19,2023-02-02,MG,J,N,611,HU,2021-04-20,J,34396.000000,BC,GD,2021-04-20,1989-12-30,M,NL,2019,HBO,J

In [303]:
osiris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 48 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   STUDENT_NUM                       211 non-null    int64
 1   STUDY_PROGRAM                     211 non-null    object
 2   ACADEMIC_YEAR                     211 non-null    int64
 3   START_DATE                        211 non-null    object
 4   END_DATE                          211 non-null    object
 5   ENROLLMENT_TYPE                   211 non-null    object
 6   EXAM_TYPE                         211 non-null    object
 7   FULL_TIME_PART                    211 non-null    object
 8   PROGRAM_ACTIVE_CODE               211 non-null    int64
 9   DATE_ACTIVE_CODE_MODIFIED         211 non-null    object
 10  DATE_WITHRAWAL_PRE-REGIS          211 non-null    object
 11  WITHDRAWAL_REASON                 211 non-null    object
 12  HIGHER_EDU_REGISTER               211 non-null    int64
 13  DATE_REGIS_PROOF                  211 non-null    object
 14  DATE_ENROLLMENT_REQUEST           211 non-null    object
 15  LOTTERY_FORM                      211 non-null    object
 16  DECENTRALIZED_RESULT_SELECTION    211 non-null    object
 17  DECENTRALIZED_SELECTION_FOLLOWUP  211 non-null    float64
 18  LOTTERY_RESULT                    211 non-null    object
 19  LOTTERY_STATUS                    211 non-null    object
 20  DATE_REQUEST_STOP                 211 non-null    object
 21  FINANCING                         211 non-null    object
 22  DATE_FIRST_ENROL_REQUEST          211 non-null    object
 23  STUDY_CHECK_PARTICIPATION         211 non-null    object
 24  DATE_STUDY_CHECK                  211 non-null    object
 25  STUDY_CHECK_RESULT                211 non-null    object
 26  STUDY_CHECK_ADMISSION             211 non-null    object
 27  EXAM_ADMINISTERED                 211 non-null    object
 28  DATE_EXAM_STARTED                 211 non-null    object
 29  EXAM_PROG_DETAILS                 211 non-null    object
 30  DATE_EXAM_CONDUCTED               211 non-null    object
 31  EXAM_FINAL_RESULT                 211 non-null    object
 32  EXAM_GRADE                        211 non-null    object
 33  HONORS_PROG_PARTICIPATION         211 non-null    object
 34  PRIOR_EDUCATION                   211 non-null    object
 35  PRIOR_SCHOOL_NAME                 211 non-null    object
 36  PRIOR_FINAL_EXAM_DATE             211 non-null    object
 37  PRIOR_DIMPLOMA_OBTAINTION         211 non-null    object
 38  PRIOR_EXTENSION_CODE              211 non-null    float64
 39  PRIOR_EXTENSION_NAME              211 non-null    object
 40  PRIOR_VERIFICATION_STATUS         211 non-null    object
 41  PRIOR_VERIFICATION_DATE           211 non-null    object
 42  BIRTH_DATE                        211 non-null    object
 43  GENDER                            211 non-null    object
 44  NATIONALITY                       211 non-null    object
 45  YEAR_STARTED_HU                   211 non-null    int64
 46  PRIOR_QUALIFICATION_TYPE          211 non-null    object
 47  INFO_CURRENT                      211 non-null    object
dtypes: float64(2), int64(5), object(41)
memory usage: 79.3+ KB

In [305]:
# Convert all columns to object data type
osiris = osiris.astype(str)
osiris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 48 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   STUDENT_NUM                       211 non-null    object
 1   STUDY_PROGRAM                     211 non-null    object
 2   ACADEMIC_YEAR                     211 non-null    object
 3   START_DATE                        211 non-null    object
 4   END_DATE                          211 non-null    object
 5   ENROLLMENT_TYPE                   211 non-null    object
 6   EXAM_TYPE                         211 non-null    object
 7   FULL_TIME_PART                    211 non-null    object
 8   PROGRAM_ACTIVE_CODE               211 non-null    object
 9   DATE_ACTIVE_CODE_MODIFIED         211 non-null    object
 10  DATE_WITHRAWAL_PRE-REGIS          211 non-null    object
 11  WITHDRAWAL_REASON                 211 non-null    object
 12  HIGHER_EDU_REGISTER               211 non-null    object
 13  DATE_REGIS_PROOF                  211 non-null    object
 14  DATE_ENROLLMENT_REQUEST           211 non-null    object
 15  LOTTERY_FORM                      211 non-null    object
 16  DECENTRALIZED_RESULT_SELECTION    211 non-null    object
 17  DECENTRALIZED_SELECTION_FOLLOWUP  211 non-null    object
 18  LOTTERY_RESULT                    211 non-null    object
 19  LOTTERY_STATUS                    211 non-null    object
 20  DATE_REQUEST_STOP                 211 non-null    object
 21  FINANCING                         211 non-null    object
 22  DATE_FIRST_ENROL_REQUEST          211 non-null    object
 23  STUDY_CHECK_PARTICIPATION         211 non-null    object
 24  DATE_STUDY_CHECK                  211 non-null    object
 25  STUDY_CHECK_RESULT                211 non-null    object
 26  STUDY_CHECK_ADMISSION             211 non-null    object
 27  EXAM_ADMINISTERED                 211 non-null    object
 28  DATE_EXAM_STARTED                 211 non-null    object
 29  EXAM_PROG_DETAILS                 211 non-null    object
 30  DATE_EXAM_CONDUCTED               211 non-null    object
 31  EXAM_FINAL_RESULT                 211 non-null    object
 32  EXAM_GRADE                        211 non-null    object
 33  HONORS_PROG_PARTICIPATION         211 non-null    object
 34  PRIOR_EDUCATION                   211 non-null    object
 35  PRIOR_SCHOOL_NAME                 211 non-null    object
 36  PRIOR_FINAL_EXAM_DATE             211 non-null    object
 37  PRIOR_DIMPLOMA_OBTAINTION         211 non-null    object
 38  PRIOR_EXTENSION_CODE              211 non-null    object
 39  PRIOR_EXTENSION_NAME              211 non-null    object
 40  PRIOR_VERIFICATION_STATUS         211 non-null    object
 41  PRIOR_VERIFICATION_DATE           211 non-null    object
 42  BIRTH_DATE                        211 non-null    object
 43  GENDER                            211 non-null    object
 44  NATIONALITY                       211 non-null    object
 45  YEAR_STARTED_HU                   211 non-null    object
 46  PRIOR_QUALIFICATION_TYPE          211 non-null    object
 47  INFO_CURRENT                      211 non-null    object
dtypes: object(48)
memory usage: 79.3+ KB

In [306]:
osiris.head(5)

,STUDENT_NUM,STUDY_PROGRAM,ACADEMIC_YEAR,START_DATE,END_DATE,ENROLLMENT_TYPE,EXAM_TYPE,FULL_TIME_PART,PROGRAM_ACTIVE_CODE,DATE_ACTIVE_CODE_MODIFIED,DATE_WITHRAWAL_PRE-REGIS,WITHDRAWAL_REASON,HIGHER_EDU_REGISTER,DATE_REGIS_PROOF,DATE_ENROLLMENT_REQUEST,LOTTERY_FORM,DECENTRALIZED_RESULT_SELECTION,DECENTRALIZED_SELECTION_FOLLOWUP,LOTTERY_RESULT,LOTTERY_STATUS,DATE_REQUEST_STOP,FINANCING,DATE_FIRST_ENROL_REQUEST,STUDY_CHECK_PARTICIPATION,DATE_STUDY_CHECK,STUDY_CHECK_RESULT,STUDY_CHECK_ADMISSION,EXAM_ADMINISTERED,DATE_EXAM_STARTED,EXAM_PROG_DETAILS,DATE_EXAM_CONDUCTED,EXAM_FINAL_RESULT,EXAM_GRADE,HONORS_PROG_PARTICIPATION,PRIOR_EDUCATION,PRIOR_SCHOOL_NAME,PRIOR_FINAL_EXAM_DATE,PRIOR_DIMPLOMA_OBTAINTION,PRIOR_EXTENSION_CODE,PRIOR_EXTENSION_NAME,PRIOR_VERIFICATION_STATUS,PRIOR_VERIFICATION_DATE,BIRTH_DATE,GENDER,NATIONALITY,YEAR_STARTED_HU,PRIOR_QUALIFICATION_TYPE,INFO_CURRENT
0,1771302,BARE,2024,2024-09-01,2025-08-31,S,B,V,4,2024-05-13,2016-06-02,VB,39205,2019-07-18,2024-05-13,N,S,295.0,I,V,2020-01-31,J,2019-04-30,NVT,2019-06-21,T,JT,D,2019-09-01,ADR-HBRV-D-20,2022-11-10,unknown,N,N,591,DHHDH,2018-06-13,N,35158.0,BP,N,2020-06-30,1997-03-03,V,NL,2019,HBO,J
1,1768080,BTICIC,2023,2023-09-01,2024-08-31,S,D,V,4,2023-09-13,2016-06-02,VB,30020,2019-07-18,2023-08-30,N,S,295.0,I,V,2020-01-31,J,2019-04-30,NVT,2019-06-21,T,JT,B,2020-09-01,TICT-VBAOPIC-20,2022-02-01,unknown,J,N,3,SRMN,2015-06-26,J,36166.07246376811,BCAMD,N,2020-06-30,1994-01-15,M,others,2019,VWO,N
2,1769163,BTLCCY,2021,2021-09-01,2022-08-31,S,B,D,4,2021-07-10,2016-06-02,VB,34396,2021-07-29,2021-07-01,N,S,295.0,I,V,2020-01-31,J,2019-04-30,NVT,2019-06-21,T,JT,D,2019-09-01,TCHY-PROPD-19,2021-04-20,unknown,N,N,611,HU,2021-04-20,J,34396.0,BC,GD,2021-04-20,1989-12-30,M,NL,2019,HBO,J
3,1699140,BJDE,2017,2017-12-21,2018-08-31,S,B,V,4,2018-02-08,2016-06-02,VB,34092,2017-08-14,2018-02-08,N,S,295.0,I,V,2020-01-31,J,2019-04-30,NVT,2019-06-21,T,JT,D,2016-09-01,JDE-DV-16,2017-12-20,unknown,N,N,591,HU,2022-02-01,J,34092.0,BCAMD,GD,2022-02-01,1999-10-08,V,NL,2016,HBO,J
4,1765243,BGHBFY,2020,2021-03-01,2021-08-31,S,B,V,4,2021-02-17,2016-06-02,VB,34570,2021-02-18,2021-02-03,N,S,295.0,I,V,2020-01-31,M,2020-08-19,NVT,2019-06-21,T,JT,B,2020-02-01,G-EXTERN-17,2022-02-01,unknown,J,N,611,HVA,2018-07-19,J,34572.0,BOTO,GD,2018-07-19,1999-02-23,V,NL,2019,HBO,J

In [307]:
osiris.columns

Index(['STUDENT_NUM', 'STUDY_PROGRAM', 'ACADEMIC_YEAR', 'START_DATE',
       'END_DATE', 'ENROLLMENT_TYPE', 'EXAM_TYPE', 'FULL_TIME_PART',
       'PROGRAM_ACTIVE_CODE', 'DATE_ACTIVE_CODE_MODIFIED',
       'DATE_WITHRAWAL_PRE-REGIS', 'WITHDRAWAL_REASON', 'HIGHER_EDU_REGISTER',
       'DATE_REGIS_PROOF', 'DATE_ENROLLMENT_REQUEST', 'LOTTERY_FORM',
       'DECENTRALIZED_RESULT_SELECTION', 'DECENTRALIZED_SELECTION_FOLLOWUP',
       'LOTTERY_RESULT', 'LOTTERY_STATUS', 'DATE_REQUEST_STOP', 'FINANCING',
       'DATE_FIRST_ENROL_REQUEST', 'STUDY_CHECK_PARTICIPATION',
       'DATE_STUDY_CHECK', 'STUDY_CHECK_RESULT', 'STUDY_CHECK_ADMISSION',
       'EXAM_ADMINISTERED', 'DATE_EXAM_STARTED', 'EXAM_PROG_DETAILS',
       'DATE_EXAM_CONDUCTED', 'EXAM_FINAL_RESULT', 'EXAM_GRADE',
       'HONORS_PROG_PARTICIPATION', 'PRIOR_EDUCATION', 'PRIOR_SCHOOL_NAME',
       'PRIOR_FINAL_EXAM_DATE', 'PRIOR_DIMPLOMA_OBTAINTION',
       'PRIOR_EXTENSION_CODE', 'PRIOR_EXTENSION_NAME',
       'PRIOR_VERIFICATION_STATUS', 'PRIOR_VERIFICATION_DATE', 'BIRTH_DATE',
       'GENDER', 'NATIONALITY', 'YEAR_STARTED_HU', 'PRIOR_QUALIFICATION_TYPE',
       'INFO_CURRENT'],
      dtype='object')

In [309]:
# Define the aggregation functions to use ' '.join for all columns
aggregation_functions = {col: ' '.join for col in osiris.columns if col != 'STUDENT_NUM'}

# Apply groupby and aggregation using ' '.join for all columns
grouped_osiris = osiris.groupby('STUDENT_NUM').agg(aggregation_functions).reset_index()

# Display the grouped DataFrame
print("\nGrouped DataFrame:")
grouped_osiris

Grouped DataFrame:

,STUDENT_NUM,STUDY_PROGRAM,ACADEMIC_YEAR,START_DATE,END_DATE,ENROLLMENT_TYPE,EXAM_TYPE,FULL_TIME_PART,PROGRAM_ACTIVE_CODE,DATE_ACTIVE_CODE_MODIFIED,DATE_WITHRAWAL_PRE-REGIS,WITHDRAWAL_REASON,HIGHER_EDU_REGISTER,DATE_REGIS_PROOF,DATE_ENROLLMENT_REQUEST,LOTTERY_FORM,DECENTRALIZED_RESULT_SELECTION,DECENTRALIZED_SELECTION_FOLLOWUP,LOTTERY_RESULT,LOTTERY_STATUS,DATE_REQUEST_STOP,FINANCING,DATE_FIRST_ENROL_REQUEST,STUDY_CHECK_PARTICIPATION,DATE_STUDY_CHECK,STUDY_CHECK_RESULT,STUDY_CHECK_ADMISSION,EXAM_ADMINISTERED,DATE_EXAM_STARTED,EXAM_PROG_DETAILS,DATE_EXAM_CONDUCTED,EXAM_FINAL_RESULT,EXAM_GRADE,HONORS_PROG_PARTICIPATION,PRIOR_EDUCATION,PRIOR_SCHOOL_NAME,PRIOR_FINAL_EXAM_DATE,PRIOR_DIMPLOMA_OBTAINTION,PRIOR_EXTENSION_CODE,PRIOR_EXTENSION_NAME,PRIOR_VERIFICATION_STATUS,PRIOR_VERIFICATION_DATE,BIRTH_DATE,GENDER,NATIONALITY,YEAR_STARTED_HU,PRIOR_QUALIFICATION_TYPE,INFO_CURRENT
0,1699140,BJDE BJDE BJDE BJDE BJDE BJDE BJDE BJDE BJDE B...,2017 2016 2017 2017 2019 2020 2021 2021 2017 2...,2017-12-21 2016-09-01 2017-09-01 2017-09-01 20...,2018-08-31 2017-08-31 2017-12-20 2017-12-20 20...,S S S S S S S S S S S S S S S S S S S S S S S ...,B D D D B B B B D B B B B D B B D D B B D B B ...,V V V V V V V V V V V V V V V V V V V V V V V ...,4 4 4 4 4 4 4 4 4 4 4 4 4 0 4 4 0 4 4 4 4 4 4 ...,2018-02-08 2016-08-27 2017-08-10 2017-08-10 20...,2016-06-02 2016-06-02 2016-06-02 2016-06-02 20...,VB VB PROP_EXAM PROP_EXAM VB VB VB VB PROP_EXA...,34092 34092 34092 34092 34092 34092 34092 3409...,2017-08-14 2016-08-29 2017-08-14 2017-08-14 20...,2018-02-08 2016-03-01 2017-07-29 2017-07-29 20...,N C N N N N N N N N N N N N N N N N N N N N N ...,S S S S S S S S S S S S S S S S S S S S S S S ...,295.0 295.0 295.0 295.0 295.0 295.0 295.0 295....,I I I I I I I I I I I I I I I I I I I I I I I ...,V V V V V V V V V V V V V V V V V V V V V V V ...,2020-01-31 2020-01-31 2020-01-31 2020-01-31 20...,J J J J J J J J J J J J J J J J J J J J J J J ...,2019-04-30 2016-03-01 2019-04-30 2019-04-30 20...,NVT NVT NVT NVT NVT NVT NVT NVT NVT NVT NVT NV...,2019-06-21 2019-06-21 2019-06-21 2019-06-21 20...,T T T T T T T T T T T T T ND T T ND T T T T T ...,JT JT JT JT JT JT JT JT JT JT JT JT JT NN JT J...,D D B D D B B D D B B B D B B D D B D D D D B ...,2016-09-01 2016-09-01 2017-09-01 2016-09-01 20...,JDE-DV-16 JDE-DV-16 JDE-BV-17 JDE-DV-16 JDE-DV...,2017-12-20 2017-12-20 2022-02-01 2017-12-20 20...,unknown unknown unknown unknown unknown unknow...,N N J N N J J N N J J J N J J N N J N N N N J ...,N N N N N N N N N N N N N N N N N N N N N N N ...,591 379 379 591 379 591 611 591 611 379 611 37...,HU GSRGAHV GSRGAHV HU GSRGAHV HU HU HU HU GSRG...,2022-02-01 2016-06-16 2016-06-16 2022-02-01 20...,J J J J J J J J J J J J J J J J J J J J J J J ...,34092.0 36722.08 36166.07246376811 34092.0 361...,BCAMD BCAMD BCAMD BCAMD BCAMD BCAMD BCAMD BCAM...,GD GD GD GD GD GD GD GD GD GD GD GD GD GD GD G...,2022-02-01 2016-06-16 2016-06-16 2022-02-01 20...,1999-10-08 1999-10-08 1999-10-08 1999-10-08 19...,V V V V V V V V V V V V V V V V V V V V V V V ...,NL NL NL NL NL NL NL NL NL NL NL NL NL NL NL N...,2016 2016 2016 2016 2016 2016 2016 2016 2016 2...,HBO HAVO HAVO HBO HAVO HBO HBO HBO HBO HAVO HB...,J J J J J J J J J J J J J J J J J J J J J J J ...
1,1764427,BOPAPABOV BOPAPABOV BOPAPABOV,2019 2019 2019,2019-09-01 2019-09-01 2019-09-01,2019-10-31 2019-10-31 2019-10-31,S S S,D D D,D D D,4 4 4,2019-06-17 2019-06-17 2019-06-17,2016-06-02 2016-06-02 2016-06-02,VB VB VB,34808 34808 34808,2019-09-03 2019-09-03 2019-09-03,2019-04-18 2019-04-18 2019-04-18,N N N,S S S,295.0 295.0 295.0,I I I,V V V,2019-10-09 2019-10-09 2019-10-09,J J J,2019-04-18 2019-04-18 2019-04-18,J J J,2019-06-21 2019-06-21 2019-06-21,T T T,JT JT JT,D D D,2019-09-01 2019-09-01 2019-09-01,OTVP-DT-19 OTVP-DT-19 OTVP-DT-19,2022-02-01 2022-02-01 2022-02-01,unknown unknown unknown,J J J,N N N,361 711 591,SVVVS OZD HU,1988-06-10 1990-05-18 2018-06-13,J J N,36166.07246376811 36166.07246376811 34808.0,BCAMD BCAMD BOTLB,DD N GV,2019-05-10 2020-06-30 2019-06-17,1968-07-30 1968-07-30 1968-07-30,V V V,NL NL NL,2019 2019 2019,VWO HBO HBO,J J J
2,1765243,BGHBFY BGHBFY BGHBFY BGHBFY BGHBFY BGHBFY BGHB...,2020 2019 2020 2021 2020 2021 2020 2019 2021 2...,2021-03-01 2020-02-01 2021-03-01 2021-09-01 20...,2021-08-31 2020-08-31 2021-08-31 2022-01-31 20...,S S S S S S S S S S S S,B B B B B B B B B B B B,V V V V V V V V V V V V,4 4 4 4 4 4 4 4 4 4 4 4,2021-02-17 2019-11-08 2021-02-17 2021-09-30 20...,2016-06-02 2016-06-02 2016-06-02 2016-06-02 20...,VB VB VB VB VB VB VB VB VB VB VB VB,34570 34570 34570 34570 34570 34570 34570 3457...,2021-02-18 2019-11-12 2021-02-18 2021-09-30 20...,2021-02-03 2019-04-23 2021-02-03 2021-08-29 20...,N N N N N N N N N N N N,S S S S S S S S S S S S,295.0 295.0 295.0 295.0 295.0 295.0 295.0 295....,I I I I I I I I I I I I,V V V V V V V V V V V V,2020-01-31 2020-01-31 2020-01-31 2022-01-30 20...,M M M M M M M M M M M M,2020-08-19 2019-04-23 2020-08-19 2019-04-30 20...,NVT NVT NVT NVT NVT NVT NVT NVT NVT NVT NVT NVT,2019-06-21 2019-06-21 2019-06-21 2019-06-21 20...,T T T T T T T T T T T T,JT JT JT JT JT JT JT JT JT JT JT JT,B B B B B B B B B B B B,2020-02-01 2020-02-01 2020-02-01 2020-02-01 20...,G-EXTERN-17 G-EXTERN-17 G-EXTERN-17 G-EXTERN-1...,2022-02-01 2022-02-01 2022-02-01 2022-02-01 20...,unknown unknown unknown unknown unknown unknow...,J J J J J J J J J J J J,N N N N N N N N N N N N,611 371 591 591 371 591 591 611 371 611 591 591,HVA MCCSVLHMV HVA HU MCCSVLHMV HVA HU HVA MCCS...,2018-07-19 2017-06-15 2022-01-26 2018-06-13 20...,J J J N J J N J J J J N,34572.0 36166.07246376811 34572.0 34570.0 3616...,BOTO BCAMD BOTO BOTF BCAMD BOTO BOTF BOTO BCAM...,GD GD GD N GD GD N GD GD GD GD N,2018-07-19 2017-06-15 2022-01-26 2020-06-30 20...,1999-02-23 1999-02-23 1999-02-23 1999-02-23 19...,V V V V V V V V V V V V,NL NL NL NL NL NL NL NL NL NL NL NL,2019 2019 2019 2019 2019 2019 2019 2019 2019 2...,HBO HAVO HBO HBO HAVO HBO HBO HBO HAVO HBO HBO...,J J J J J J J J J J J J
3,1766090,BMLM BMLM BMLM BMLM BMLM BMLM BMLM BMLM BMLM B...,2020 2019 2020 2021 2020 2021 2021 2019 2019 2...,2020-09-01 2019-09-01 2020-09-01 2021-09-01 20...,2021-08-31 2020-06-30 2021-08-31 2021-09-30 20...,S S S S S S S S S S S S S S S S S S S S S S S ...,B D B B B B B B D B B B D B B B B B B B D B B ...,V V V V V V V V V V V V V V V V V V V V V V V ...,4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 ...,2020-07-24 2019-07-10 2020-07-24 2021-08-31 20...,2016-06-02 2016-06-02 2016-06-02 2016-06-02 20...,VB PROP_EXAM VB VB VB VB VB VB PROP_EXAM VB VB...,35522 35522 35522 35522 35522 35522 35522 3552...,2020-07-28 2019-07-18 2020-07-28 2021-09-02 20...,2020-06-11 2019-04-25 2020-06-11 2021-08-31 20...,N N N N N N N N N N N N N N N N N N N N N N N ...,S S S S S S S S S S S S S S S S S S S S S S S ...,295.0 295.0 295.0 295.0 295.0 295.0 295.0 295....,I I I I I I I I I I I I I I I I I I I I I I I ...,V V V V V V V V V V V V V V V V V V V V V V V ...,2020-01-31 2020-01-31 2020-01-31 2021-09-30 20...,J J J J J J J J J J J J J J J J J J J J J J J ...,2019-04-30 2019-04-25 2019-04-30 2019-04-30 20...,NVT J NVT NVT NVT NVT NVT NVT J NVT NVT NVT J ...,2019-06-21 2019-06-21 2019-06-21 2019-06-21 20...,T T T T T T T T T T T T T T T T T T T T T T T ...,JT JT JT JT JT JT JT JT JT JT JT JT JT JT JT J...,D D D D B D B B B B D D B D D B B B B B B B B ...,2019-09-01 2019-09-01 2019-09-01 2019-09-01 20...,MBLM-DV-19 MBLM-DV-19 MBLM-DV-19 MBLM-DV-19 MB...,2020-06-30 2020-06-30 2020-06-30 2020-06-30 20...,unknown unknown unknown unknown unknown unknow...,N N N N J N J J J J N N J N N J J J J J J J J ...,N N N N N N N N N N N N N N N N N N N N N N N ...,611 741 179 611 611 741 741 611 741 591 591 59...,HU UUU HSC HU HU UUU UUU HU UUU HU HU HU HSC U...,2020-06-30 2018-06-13 2018-06-13 2020-06-30 20...,J N J J J N N J N N N N J N J N J N J N N J N ...,35522.0 50950.0 36166.07246376811 35522.0 3552...,BLM BEEB BCAMD BLM BLM BEEB BEEB BLM BEEB BLM ...,GD N GD GD GD N N GD N N N N GD N GD N GD N GD...,2020-06-30 2020-06-30 2018-06-13 2020-06-30 20...,2000-03-08 2000-03-08 2000-03-08 2000-03-08 20...,M M M M M M M M M M M M M M M M M M M M M M M ...,NL NL NL NL NL NL NL NL NL NL NL NL NL NL NL N...,2019 2019 2019 2019 2019 2019 2019 2019 2019 2...,HBO WO VWO HBO HBO WO WO HBO WO HBO HBO HBO VW...,J J J J J J J J J J J J J J J J J J J J J J J ...
4,1768080,BTICIC BTICIC BTICIC BTICIC BTICIC BTICIC BTIC...,2023 2021 2022 2021 2020 2022 2019 2021 2021 2...,2023-09-01 2021-09-01 2022-09-01 2021-09-01 20...,2024-08-31 2022-08-31 2023-08-31 2022-08-31 20...,S S S S S S S S S S S S S S S S S S S S S S S ...,D D D D D D D D D D D D D D D D D D D D D D D ...,V V V V V V V V V V V V V V V V V V V V V V V ...,4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 ...,2023-09-13 2021-09-24 2022-05-10 2021-09-24 20...,2016-06-02 2016-06-02 2016-06-02 2016-06-02 20...,VB VB VB VB VB VB VB VB VB VB VB VB VB VB VB V...,30020 30020 30020 30020 30020 30020 30020 3002...,2019-07-18 2021-09-28 2019-07-18 2021-09-28 20...,2023-08-30 2021-09-24 2022-05-10 2021-09-24 20...,N N N N N N N N N N N N N N N N N N N N N N N ...,S S S S S S S S S S S S S S S S S S S S S S S ...,295.0 295.0 295.0 295.0 295.0 295.0 295.0 295....,I I I I I I I I I I I I I I I I I I I I I I I ...,V V V V V V V V V V V V V V V V V V V V V V V ...,2020-01-31 2020-01-31 2020-01-31 2020-01-31 20...,J J J J J J J J J J J J J J J J J J J J J J J ...,2019-04-30 2019-04-30 2019-04-30 2019-04-30 20...,NVT NVT NVT NVT NVT NVT J NVT NVT NVT NVT NVT ...,2019-06-21 2019-06-21 2019-06-21 2019-06-21 20...,T T T T T T P T T T T T P T P T P T T T T T T ...,JT JT JT JT JT JT JP JT JT JT JT JT JP JT JP J...,B B B D D B B B D B B D B D D D D B B D D D B ...,2020-09-01 2020-09-01 2020-09-01 2019-09-01 20...,TICT-VBAOPIC-20 TICT-VBAOPIC-20 TICT-VBAOPIC-2...,2022-02-01 2022-02-01 2022-02-01 2022-02-01 20...,unknown unknown unknown unknown unknown unknow...,J J J J J J J J J J J J J J J J J J J J J J J ...,N N N N N N N N N N N N N N N N N N N N N N N ...,3 3 3 3 601 601 3 601 591 591 3 601 601 3 591 ...,SRMN SRMN SRMN SRMN HUU HUU SRMN HUU HU HU SRM...,2015-06-26 2015-06-26 2015-06-26 2015-06-26 20...,J J J J J J J J N N J J J J N N J N N J N J N ...,36166.07246376811 36166.07246376811 36166.0724...,BCAMD BCAMD BCAMD BCAMD BCAMD BCAMD BCAMD BCAM...,N N N N DD DD N DD GV GV N DD DD N GV GV DD GV...,2020-06-30 2020-06-30 2020-06-30 2020-06-30 20...,1994-01-15 1994-01-15 1994-01-15 1994-01-15 19...,M M M M M M M M M M M M M M M M M M M M M M M ...,others others others others others others othe...,2019 2019 2019 2019 2019 2019 2019 2019 2019 2...,VWO VWO VWO VWO VO VO VWO VO HBO HBO VWO VO VO...,N N N N J J N J J J N J J N J J J J J N J J J ...
5,1769163,BTLCCY BTLCCY BTLCCY BTLCCY BTLCCY BTLCCY BTLC...,2021 2022 2021 2020 2022 2019 2020 2020 2021 2...,2021-09-01 2022-09-01 2021-09-01 2021-04-21 20...,2022-08-31 2023-02-28 2022-08-31 2021-08-31 20...,S S S S S S S S S S S S S S S S S S S S S S S ...,B B B B B D D B B B D B B D B B D B D B B B B ...,D D D D D D D D D D D D D D D D D D D D D D D ...,4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 ...,2021-07-10 2022-06-26 2021-07-10 2021-06-11 20...,2016-06-02 2016-06-02 2016-06-02 2016-06-02 20...,VB VB VB VB VB VB PROP_EXAM VB VB VB VB VB VB ...,34396 34396 34396 34396 34396 34396 34396 3439...,2021-07-29 2019-07-18 2021-07-29 2020-07-13 20...,2021-07-01 2022-06-12 2021-07-01 2021-06-11 20...,N N N N N N N N N N N N N N N N N N N N N N N ...,S S S S S S S S S S S S S S S S S S S S S S S ...,295.0 295.0 295.0 295.0 295.0 295.0 295.0 295....,I I I I I I I I I I I I I I I I I I I I I I I ...,V V V V V V V V V V V V V V V V V V V V V V V ...,2020-01-31 2023-02-07 2020-01-31 2020-01-31 20...,J J J J J J J J J J J J J J J J J J J J J J J ...,2019-04-30 2019-04-30 2019-04-30 2019-04-30 20...,NVT NVT NVT NVT NVT N NVT NVT NVT NVT N NVT NV...,2019-06-21 2019-06-21 2019-06-21 2019-06-21 20...,T T T T T T T T T T T T T T T T T T T T T T T ...,JT JT JT JT JT JT JT JT JT JT JT JT JT JT JT J...,D B B D B B D D B B D D D D D D D D B D B B B ...,2019-09-01 2020-01-01 2020-01-01 2019-09-01 20...,TCHY-PROPD-19 TCHY-BASD-19 TCHY-BASD-19 TCHY-P...,2021-04-20 2023-02-02 2023-02-02 2021-04-20 20...,unknown MG MG unknown MG MG unknown unknown MG...,N J J N J J N N J J N N N N N N N N J N J J J ...,N N N N N N N N N N N N N N N N N N N N N N N ...,611 91711 91711 611 611 591 91711 591 611 611 ...,HU RW RW HU HU HU RW HU HU HU RW RW RW HU HU H...,2021-04-20 2010-07-06 2010-07-06 2021-04-20 20...,J J J J J J J J J J J J J J J J J J J J J J J ...,34396.0 36166.07246376811 36166.07246376811 34...,BC BCAMD BCAMD BC BC BC BCAMD BC BC BC BCAMD B...,GD GD GD GD GD GD GD GD GD GD GD GD GD GD GD G...,2021-04-20 2010-07-06 2010-07-06 2021-04-20 20...,1989-12-30 1989-12-30 1989-12-30 1989-12-30 19...,M M M M M M M M M M M M M M M M M M M M M M M ...,NL NL NL NL NL NL NL NL NL NL NL NL NL NL NL N...,2019 2019 2019 2019 2019 2019 2019 2019 2019 2...,HBO MBO MBO HBO HBO HBO MBO HBO HBO HBO MBO MB...,J J J J J J J J J J J J J J J J J J J J J J J ...
6,1771302,BARE BARE BARE BARE BARE BARE BARE BARE BARE B...,2024 2021 2020 2019 2021 2021 2021 2022 2022 2...,2024-09-01 2021-09-01 2020-09-01 2019-09-01 20...,2025-08-31 2022-08-31 2021-08-31 2020-01-31 20...,S S S S S S S S S S S S S S S S S S S S S S S ...,B D D D D D D B B D D D B B D B B D D D B B D ...,V V V V V V V V V V V V V V V V V V V V V V V ...,4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 ...,2024-05-13 2021-07-22 2020-07-16 2019-08-23 20...,2016-06-02 2016-06-02 2016-06-02 2016-06-02 20...,VB VB VB VB VB VB VB VB VB PROP_EXAM VB VB VB ...,39205 39205 39205 39205 39205 39205 39205 3920...,2019-07-18 2021-07-29 2020-07-21 2019-08-27 20...,2024-05-13 2021-06-08 2020-03-20 2019-07-10 20...,N N N N N N N N N N N N N N N N N N N N N N N ...,S S S S S S S S S S S S S S S S S S S S S S S ...,295.0 295.0 295.0 295.0 295.0 295.0 295.0 295....,I I I I I I I I I I I I I I I I I I I I I I I ...,V V V V V V V V V V V V V V V V V V V V V V V ...,2020-01-31 2020-01-31 2020-01-31 2020-01-31 20...,J J J J J J J J J J J J J J J J J J J J J J J ...,2019-04-30 2019-04-30 2020-03-20 2019-04-30 20...,NVT NVT J J NVT NVT NVT NVT NVT NVT NVT J NVT ...,2019-06-21 2019-06-21 2020-06-05 2019-08-21 20...,T T T T T T T T T T T T T T T T T T T T T T T ...,JT JT JO JT JT JT JT JT JT JT JT JO JT JT JT J...,D D D D B D B B B B B D D D D D B D D B B B B ...,2019-09-01 2019-09-01 2019-09-01 2019-09-01 20...,ADR-HBRV-D-20 ADR-HBRV-D-20 ADR-HBRV-D-20 ADR-...,2022-11-10 2022-11-10 2022-11-10 2022-11-10 20...,unknown unknown unknown unknown unknown unknow...,N N N N J N J J J J J N N N N N J N N J J J J ...,N N N N N N N N N N N N N N N N N N N N N N N ...,591 92632 611 92632 591 591 611 92632 591 611 ...,DHHDH ROC HU ROC DHHDH DHHDH HU ROC HU HU HU H...,2018-06-13 2017-09-26 2022-11-10 2017-09-26 20...,N J J J N N J J N J N N N J J J J N J N J N J ...,35158.0 36166.07246376811 39205.0 36166.072463...,BP BCAMD BH-R BCAMD BP BP BH-R BCAMD BH-R BH-R...,N GD GD GD N N GD GD GV GD GV GV GV GD GD GD G...,2020-06-30 2017-09-26 2022-11-10 2017-09-26 20...,1997-03-03 1997-03-03 1997-03-03 1997-03-03 19...,V V V V V V V V V V V V V V V V V V V V V V V ...,NL NL NL NL NL NL NL NL NL NL NL NL NL NL NL N...,2019 2019 2019 2019 2019 2019 2019 2019 2019 2...,HBO MBO HBO MBO HBO HBO HBO MBO HBO HBO HBO HB...,J J J J J J J J J J J J J J J J J J J J J J J ...

In [311]:
# keeping only the 'first' string if all strings in a column for a particular STUDENT_NUM are the same, and 
# concatenating the strings if they are different

# Define the aggregation functions to use ' '.join for all columns
aggregation_functions = {col: ' '.join for col in osiris.columns if col != 'STUDENT_NUM'}

# Apply groupby and aggregation using ' '.join for all columns
grouped_osiris = osiris.groupby('STUDENT_NUM').agg(aggregation_functions).reset_index()

# Function to remove duplicate strings and keep only one occurrence
def remove_duplicates(text):
    words = text.split()
    unique_words = list(dict.fromkeys(words))  # Keep only the first occurrence
    return ' '.join(unique_words)

# Apply the remove_duplicates function to all columns except 'STUDENT_NUM'
for col in grouped_osiris.columns:
    if col != 'STUDENT_NUM':
        grouped_osiris[col] = grouped_osiris[col].apply(remove_duplicates)

# Display the cleaned DataFrame
print("\nCleaned Grouped DataFrame with Unique Strings:")
grouped_osiris

Cleaned Grouped DataFrame with Unique Strings:

,STUDENT_NUM,STUDY_PROGRAM,ACADEMIC_YEAR,START_DATE,END_DATE,ENROLLMENT_TYPE,EXAM_TYPE,FULL_TIME_PART,PROGRAM_ACTIVE_CODE,DATE_ACTIVE_CODE_MODIFIED,DATE_WITHRAWAL_PRE-REGIS,WITHDRAWAL_REASON,HIGHER_EDU_REGISTER,DATE_REGIS_PROOF,DATE_ENROLLMENT_REQUEST,LOTTERY_FORM,DECENTRALIZED_RESULT_SELECTION,DECENTRALIZED_SELECTION_FOLLOWUP,LOTTERY_RESULT,LOTTERY_STATUS,DATE_REQUEST_STOP,FINANCING,DATE_FIRST_ENROL_REQUEST,STUDY_CHECK_PARTICIPATION,DATE_STUDY_CHECK,STUDY_CHECK_RESULT,STUDY_CHECK_ADMISSION,EXAM_ADMINISTERED,DATE_EXAM_STARTED,EXAM_PROG_DETAILS,DATE_EXAM_CONDUCTED,EXAM_FINAL_RESULT,EXAM_GRADE,HONORS_PROG_PARTICIPATION,PRIOR_EDUCATION,PRIOR_SCHOOL_NAME,PRIOR_FINAL_EXAM_DATE,PRIOR_DIMPLOMA_OBTAINTION,PRIOR_EXTENSION_CODE,PRIOR_EXTENSION_NAME,PRIOR_VERIFICATION_STATUS,PRIOR_VERIFICATION_DATE,BIRTH_DATE,GENDER,NATIONALITY,YEAR_STARTED_HU,PRIOR_QUALIFICATION_TYPE,INFO_CURRENT
0,1699140,BJDE BJSCICM,2017 2016 2019 2020 2021 2018,2017-12-21 2016-09-01 2017-09-01 2019-09-01 20...,2018-08-31 2017-08-31 2017-12-20 2020-08-31 20...,S,B D,V,4 0,2018-02-08 2016-08-27 2017-08-10 2019-07-31 20...,2016-06-02,VB PROP_EXAM,34092 34430,2017-08-14 2016-08-29 2019-08-06 2020-09-01 20...,2018-02-08 2016-03-01 2017-07-29 2019-06-10 20...,N C,S,295.0,I,V,2020-01-31,J,2019-04-30 2016-03-01,NVT J,2019-06-21 2016-06-02,T ND,JT NN,D B,2016-09-01 2017-09-01,JDE-DV-16 JDE-BV-17,2017-12-20 2022-02-01,unknown,N J,N,591 379 611,HU GSRGAHV,2022-02-01 2016-06-16 2017-12-20,J,34092.0 36722.08 36166.07246376811,BCAMD,GD,2022-02-01 2016-06-16 2017-12-20,1999-10-08,V,NL,2016,HBO HAVO,J
1,1764427,BOPAPABOV,2019,2019-09-01,2019-10-31,S,D,D,4,2019-06-17,2016-06-02,VB,34808,2019-09-03,2019-04-18,N,S,295.0,I,V,2019-10-09,J,2019-04-18,J,2019-06-21,T,JT,D,2019-09-01,OTVP-DT-19,2022-02-01,unknown,J,N,361 711 591,SVVVS OZD HU,1988-06-10 1990-05-18 2018-06-13,J N,36166.07246376811 34808.0,BCAMD BOTLB,DD N GV,2019-05-10 2020-06-30 2019-06-17,1968-07-30,V,NL,2019,VWO HBO,J
2,1765243,BGHBFY,2020 2019 2021,2021-03-01 2020-02-01 2021-09-01,2021-08-31 2020-08-31 2022-01-31,S,B,V,4,2021-02-17 2019-11-08 2021-09-30,2016-06-02,VB,34570,2021-02-18 2019-11-12 2021-09-30,2021-02-03 2019-04-23 2021-08-29,N,S,295.0,I,V,2020-01-31 2022-01-30,M,2020-08-19 2019-04-23 2019-04-30,NVT,2019-06-21,T,JT,B,2020-02-01,G-EXTERN-17,2022-02-01,unknown,J,N,611 371 591,HVA MCCSVLHMV HU,2018-07-19 2017-06-15 2022-01-26 2018-06-13,J N,34572.0 36166.07246376811 34570.0,BOTO BCAMD BOTF,GD N,2018-07-19 2017-06-15 2022-01-26 2020-06-30,1999-02-23,V,NL,2019,HBO HAVO,J
3,1766090,BMLM,2020 2019 2021,2020-09-01 2019-09-01 2021-09-01 2020-07-01,2021-08-31 2020-06-30 2021-09-30 2020-08-31,S,B D,V,4,2020-07-24 2019-07-10 2021-08-31 2020-09-28,2016-06-02,VB PROP_EXAM,35522,2020-07-28 2019-07-18 2021-09-02,2020-06-11 2019-04-25 2021-08-31 2020-09-28,N,S,295.0,I,V,2020-01-31 2021-09-30,J,2019-04-30 2019-04-25,NVT J,2019-06-21,T,JT,D B,2019-09-01 2020-09-01,MBLM-DV-19 MBLM-BV-19,2020-06-30 2022-02-01,unknown,N J,N,611 741 179 591,HU UUU HSC,2020-06-30 2018-06-13,J N,35522.0 50950.0 36166.07246376811,BLM BEEB BCAMD,GD N,2020-06-30 2018-06-13,2000-03-08,M,NL,2019,HBO WO VWO,J
4,1768080,BTICIC,2023 2021 2022 2020 2019,2023-09-01 2021-09-01 2022-09-01 2020-09-01 20...,2024-08-31 2022-08-31 2023-08-31 2021-08-31 20...,S,D,V,4,2023-09-13 2021-09-24 2022-05-10 2020-08-23 20...,2016-06-02,VB,30020,2019-07-18 2021-09-28 2020-08-25 2019-08-29,2023-08-30 2021-09-24 2022-05-10 2020-06-12 20...,N,S,295.0,I,V,2020-01-31,J,2019-04-30,NVT J,2019-06-21 2019-08-22,T P,JT JP,B D,2020-09-01 2019-09-01,TICT-VBAOPIC-20 TICT-VPOPICT-19,2022-02-01,unknown,J,N,3 601 591,SRMN HUU HU,2015-06-26 2019-05-09 2018-06-13,J N,36166.07246376811 30020.0,BCAMD BH,N DD GV,2020-06-30 2019-05-21 2021-09-24,1994-01-15,M,others,2019,VWO VO HBO,N J
5,1769163,BTLCCY,2021 2022 2020 2019,2021-09-01 2022-09-01 2021-04-21 2019-09-01 20...,2022-08-31 2023-02-28 2021-08-31 2020-08-31 20...,S,B D,D,4,2021-07-10 2022-06-26 2021-06-11 2019-07-18 20...,2016-06-02,VB PROP_EXAM,34396,2021-07-29 2019-07-18 2020-07-13 2019-08-13,2021-07-01 2022-06-12 2021-06-11 2019-05-15 20...,N,S,295.0,I,V,2020-01-31 2023-02-07,J,2019-04-30 2019-05-15,NVT N,2019-06-21,T,JT,D B,2019-09-01 2020-01-01,TCHY-PROPD-19 TCHY-BASD-19,2021-04-20 2023-02-02,unknown MG,N J,N,611 91711 591,HU RW,2021-04-20 2010-07-06 2023-02-02,J,34396.0 36166.07246376811,BC BCAMD,GD,2021-04-20 2010-07-06 2023-02-02,1989-12-30,M,NL,2019,HBO MBO,J
6,1771302,BARE,2024 2021 2020 2019 2022 2023,2024-09-01 2021-09-01 2020-09-01 2019-09-01 20...,2025-08-31 2022-08-31 2021-08-31 2020-01-31 20...,S,B D,V,4,2024-05-13 2021-07-22 2020-07-16 2019-08-23 20...,2016-06-02,VB PROP_EXAM,39205,2019-07-18 2021-07-29 2020-07-21 2019-08-27,2024-05-13 2021-06-08 2020-03-20 2019-07-10 20...,N,S,295.0,I,V,2020-01-31,J,2019-04-30 2020-03-20,NVT J,2019-06-21 2020-06-05 2019-08-21,T,JT JO,D B,2019-09-01 2021-09-01,ADR-HBRV-D-20 ADR-HBRV-B-21,2022-11-10 2022-02-01,unknown,N J,N,591 92632 611,DHHDH ROC HU,2018-06-13 2017-09-26 2022-11-10,N J,35158.0 36166.07246376811 39205.0,BP BCAMD BH-R,N GD GV,2020-06-30 2017-09-26 2022-11-10 2022-12-19,1997-03-03,V,NL,2019,HBO MBO,J