In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from functools import reduce
import os
import warnings
warnings.filterwarnings('ignore')
pd.options.display.max_columns = None
from IPython.display import display

In [2]:
# Reset cells output
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')
pd.reset_option('display.max_colwidth')
pd.reset_option('display.width')
pd.reset_option('display.expand_frame_repr')

In [3]:
print("hello")

hello

In [4]:
# Load the Excel file
file_path = '../data/raw/1.2 250319_DSP_StudentDropoutProject_DWH-OSI_combi.xlsx'
data = pd.read_excel(file_path, sheet_name=None)

# Print the names of all sheets
print("Sheet names:", data.keys())

# Display the first few rows of each sheet
for sheet_name, sheet_data in data.items():
    print(f"---{sheet_name}---")
    print(sheet_data.head())

Sheet names: dict_keys(['DATA', 'PIVOT', 'PIVOT (2)', 'ATTRIBUTES', 'DWH_SQL', 'OSI_SQL'])
---DATA---
   studentnummer   sinh_d  cohort_opleiding  collegejaar ingangsdatum  \
0        1699279  1546413              2018         2018   2018-09-01
1        1714870  1549026              2018         2018   2018-09-01
2        1719899  1543665              2018         2018   2018-09-01
3        1722984  1556941              2018         2018   2018-09-01
4        1734406  1536214              2018         2018   2018-09-01

  afloopdatum                     opl_naam_en opleiding  croho type_ho  ...  \
0  2019-08-31  B Arts Therapies (Art Therapy)    BACTBE  34644      BA  ...
1  2019-08-31  B Arts Therapies (Art Therapy)    BACTBE  34644      BA  ...
2  2019-08-31  B Arts Therapies (Art Therapy)    BACTBE  34644      BA  ...
3  2019-08-31  B Arts Therapies (Art Therapy)    BACTBE  34644      BA  ...
4  2019-08-31  B Arts Therapies (Art Therapy)    BACTBE  34644      BA  ...

  C2 C3 vooropleiding  type_vooropleiding  datum_eindexamen  school  \
0  0  0         94524                 MBO          07-07-15  02PK00
1  0  0         92662                 MBO          05-07-17  09MR00
2  0  0         92631                 MBO          19-09-17  27DV00
3  0  0          5171                 VWO          13-06-18  25PT00
4  0  0          0373                HAVO          14-06-17  02EA00

                                                naam      plaats  postcode  \
0  Nimeto Algemen Bijzondere Scholengemeenschap v...     UTRECHT   3572 LP
1  Hoornbeeck College voor Mbo op Reformatorische...  AMERSFOORT   3818 ET
2    Stichting Regionaal Opleidingen Centrum AVENTUS   APELDOORN   7331 VZ
3                                    Talland College     ALKMAAR   1817 BC
4  Scholengroep Driestar-Wartburg - Driestar Goud...       GOUDA   2803 ZV

  land
0   NL
1   NL
2   NL
3   NL
4   NL

[5 rows x 27 columns]
---PIVOT---
                                          Unnamed: 0   Unnamed: 1  \
0  C1.    Gone out of HU but successfully with a ...          NaN
1                           Aantal van studentnummer  Kolomlabels
2                                          Rijlabels         2018
3                                                  0     0.965906
4                                                  1     0.034094

    Unnamed: 2   Unnamed: 3   Unnamed: 4   Unnamed: 5   Unnamed: 6  Unnamed: 7
0          NaN          NaN          NaN          NaN          NaN         NaN
1          NaN          NaN          NaN          NaN          NaN         NaN
2  2019.000000  2020.000000  2021.000000  2022.000000  2023.000000  Eindtotaal
3     0.960428     0.961361     0.966174     0.960509     0.958032      0.9621
4     0.039572     0.038639     0.033826     0.039491     0.041968      0.0379
---PIVOT (2)---
                                 Unnamed: 0   Unnamed: 1  Unnamed: 2  \
0                                       NaN          NaN         NaN
1                  Aantal van studentnummer  Kolomlabels         NaN
2                                 Rijlabels         2018      2019.0
3  B Information & Communication Technology          562       512.0
4                             B Social Work          445       415.0

   Unnamed: 3  Unnamed: 4  Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  \
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN
2      2020.0      2021.0      2022.0      2023.0  Eindtotaal         NaN
3       497.0       500.0       539.0       605.0        3215         NaN
4       504.0       447.0       479.0       433.0        2723         NaN

                                          Unnamed: 9
0  C1.    Gone out of HU but successfully with a ...
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
---ATTRIBUTES---
      studentnummer                Unique id of student
0            sinh_d              Unique id of enrolment
1  cohort_opleiding    Starting year of study programme
2       collegejaar                       Academic year
3      ingangsdatum  Starting date within academic year
4       afloopdatum       End date within academic year
---DWH_SQL---
  WITH CTE_INS AS ( -- records of programme enrolment per academic year  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

  Unnamed: 1                        Unnamed: 2  \
0        NaN           SELECT si.studentnummer
1        NaN                               NaN
2        NaN       , MIN(si.sinh_id) AS sinh_d
3        NaN
4        NaN                               NaN

                                          Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0                                                NaN        NaN        NaN
1                                  , si.d_student_id        NaN        NaN
2                                                NaN        NaN        NaN
3   , si.cohort_opleiding -- first academic year ...        NaN        NaN
4                                   , si.collegejaar        NaN        NaN

  Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11  \
0        NaN        NaN        NaN        NaN         NaN         NaN
1        NaN        NaN        NaN        NaN         NaN         NaN
2        NaN        NaN        NaN        NaN         NaN         NaN
3        NaN        NaN        NaN        NaN         NaN         NaN
4        NaN        NaN        NaN        NaN         NaN         NaN

   Unnamed: 12 Unnamed: 13
0          NaN         NaN
1          NaN         NaN
2          NaN         NaN
3          NaN         NaN
4          NaN         NaN
---OSI_SQL---
  with std_opl_aanv as (select std_opl.studentnummer
0                             , nvl(ooh.opleiding...
1                             , min(std_opl.min_i...
2                             , min(std_opl.min_i...
3                                               from
4                              (select osi_1.stud...

In [5]:
# Load only the 'DATA' sheet into a DataFrame
data = pd.read_excel(file_path, sheet_name='DATA')

# Display the first few rows of the 'DATA' sheet
data

,studentnummer,sinh_d,cohort_opleiding,collegejaar,ingangsdatum,afloopdatum,opl_naam_en,opleiding,croho,type_ho,...,C2,C3,vooropleiding,type_vooropleiding,datum_eindexamen,school,naam,plaats,postcode,land
0,1699279,1546413,2018,2018,2018-09-01,2019-08-31,B Arts Therapies (Art Therapy),BACTBE,34644,BA,...,0,0,94524,MBO,07-07-15,02PK00,Nimeto Algemen Bijzondere Scholengemeenschap v...,UTRECHT,3572 LP,NL
1,1714870,1549026,2018,2018,2018-09-01,2019-08-31,B Arts Therapies (Art Therapy),BACTBE,34644,BA,...,0,0,92662,MBO,05-07-17,09MR00,Hoornbeeck College voor Mbo op Reformatorische...,AMERSFOORT,3818 ET,NL
2,1719899,1543665,2018,2018,2018-09-01,2019-08-31,B Arts Therapies (Art Therapy),BACTBE,34644,BA,...,0,0,92631,MBO,19-09-17,27DV00,Stichting Regionaal Opleidingen Centrum AVENTUS,APELDOORN,7331 VZ,NL
3,1722984,1556941,2018,2018,2018-09-01,2019-08-31,B Arts Therapies (Art Therapy),BACTBE,34644,BA,...,0,0,5171,VWO,13-06-18,25PT00,Talland College,ALKMAAR,1817 BC,NL
4,1734406,1536214,2018,2018,2018-09-01,2019-08-31,B Arts Therapies (Art Therapy),BACTBE,34644,BA,...,0,0,0373,HAVO,14-06-17,02EA00,Scholengroep Driestar-Wartburg - Driestar Goud...,GOUDA,2803 ZV,NL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48386,1867539,1964301,2023,2023,2023-09-01,2024-08-31,Biology & Medical Laboratory Research,BTLCLS,34397,BA,...,0,0,0171,VWO,09-06-22,21EX00,Theresialyceum voor gymnasium atheneum en havo,TILBURG,5037 DA,NL
48387,1867813,1966882,2023,2023,2023-09-01,2024-08-31,Biology & Medical Laboratory Research,BTLCLS,34397,BA,...,0,0,0271,VWO,09-06-22,02DQ00,Christelijk Gymnasium Sorghvliet,'S-GRAVENHAGE,2517 JR,NL
48388,1868156,1972247,2023,2023,2023-09-01,2024-08-31,Biology & Medical Laboratory Research,BTLCLS,34397,BA,...,1,0,0089,EDUCATIE,21-12-23,30PK,College voor Toetsen en Examens,0,0,0
48389,1868215,1973119,2023,2023,2023-09-01,2024-08-31,Biology & Medical Laboratory Research,BTLCLS,34397,BA,...,1,0,0371,HAVO,10-06-21,20ST00,Sint-Janslyceum School voor Gymnasium Atheneum...,'S-HERTOGENBOSCH,5216 EG,NL
48390,1869081,1980114,2023,2023,2024-07-01,2024-08-31,Biology & Medical Laboratory Research,BTLCLS,34397,BA,...,0,0,00611,OVERIG,30-06-20,28DN00,Hogeschool van Amsterdam: Amsterdam,AMSTERDAM,1097 DZ,NL

In [6]:
data.columns

Index(['studentnummer', 'sinh_d', 'cohort_opleiding', 'collegejaar',
       'ingangsdatum', 'afloopdatum', 'opl_naam_en', 'opleiding', 'croho',
       'type_ho', 'vorm', 'fase', 'p_examendatum', 'p_behaald',
       'uit_zonder_dip', 'opleiding_switch', 'C1', 'C2', 'C3', 'vooropleiding',
       'type_vooropleiding', 'datum_eindexamen', 'school', 'naam', 'plaats',
       'postcode', 'land'],
      dtype='object')

In [7]:
# renaming columns for data
data_rename_mapping = {
    'studentnummer': 'Student_num',
    'sinh_d': 'Enrollment_ID',
    'cohort_opleiding': 'Study_Pro_Start_Year',
    'collegejaar': 'College_Year',
    'ingangsdatum': 'Student_Start_Date',
    'afloopdatum': 'Student_End_Date',
    'vorm': 'Student_Full_Parttime_Dual',
    'opl_naam_en': 'Study_Prog_Name',
    'opleiding': 'Study_Prog_Code',
    'croho': 'Study_Prog_Group_ID',
    'type_ho': 'Study_Bach_Master_Type',
    'fase': 'Study_Prog_Phase',
    'p_examendatum': 'Study_Prog_Exam_Date',
    'p_behaald': 'Study_Prog_Exam_Completed',
    'uit_zonder_dip': 'Dropped_No_Diploma',
    'opleiding_switch': 'Switched',
    'C1': 'Left_Successfully',
    'C2': 'Left_Unsuccessfully',
    'C3': 'Switched_Internally',
    'vooropleiding': 'Prior_Edu_ID',
    'type_vooropleiding': 'Prior_Edu_Type',
    'datum_eindexamen': 'Prior_Edu_Exam_Date',
    'school': 'Prior_Edu_School_Code',
    'naam': 'Prior_Edu_School_Name',
    'plaats': 'Prior_Edu_School_Location',
    'postcode': 'Prior_Edu_Postcode',
    'land': 'Prior_Edu_Country'
    }

# Rename columns
data.rename(columns=data_rename_mapping, inplace=True)
# Create a list of the new column names
new_columns = list(data_rename_mapping.values())
# Keep only the renamed columns and drop the rest, this is because we want to avoid the problem of a new column added in the database renders the tool not working. 
# A randomly added column is not cleaned and we should be notified of this to properly clean and add the new column.
data = data[new_columns]

In [8]:
data.columns

Index(['Student_num', 'Enrollment_ID', 'Study_Pro_Start_Year', 'College_Year',
       'Student_Start_Date', 'Student_End_Date', 'Student_Full_Parttime_Dual',
       'Study_Prog_Name', 'Study_Prog_Code', 'Study_Prog_Group_ID',
       'Study_Bach_Master_Type', 'Study_Prog_Phase', 'Study_Prog_Exam_Date',
       'Study_Prog_Exam_Completed', 'Dropped_No_Diploma', 'Switched',
       'Left_Successfully', 'Left_Unsuccessfully', 'Switched_Internally',
       'Prior_Edu_ID', 'Prior_Edu_Type', 'Prior_Edu_Exam_Date',
       'Prior_Edu_School_Code', 'Prior_Edu_School_Name',
       'Prior_Edu_School_Location', 'Prior_Edu_Postcode', 'Prior_Edu_Country'],
      dtype='object')

In [9]:
data

,Student_num,Enrollment_ID,Study_Pro_Start_Year,College_Year,Student_Start_Date,Student_End_Date,Student_Full_Parttime_Dual,Study_Prog_Name,Study_Prog_Code,Study_Prog_Group_ID,...,Left_Unsuccessfully,Switched_Internally,Prior_Edu_ID,Prior_Edu_Type,Prior_Edu_Exam_Date,Prior_Edu_School_Code,Prior_Edu_School_Name,Prior_Edu_School_Location,Prior_Edu_Postcode,Prior_Edu_Country
0,1699279,1546413,2018,2018,2018-09-01,2019-08-31,Voltijd,B Arts Therapies (Art Therapy),BACTBE,34644,...,0,0,94524,MBO,07-07-15,02PK00,Nimeto Algemen Bijzondere Scholengemeenschap v...,UTRECHT,3572 LP,NL
1,1714870,1549026,2018,2018,2018-09-01,2019-08-31,Voltijd,B Arts Therapies (Art Therapy),BACTBE,34644,...,0,0,92662,MBO,05-07-17,09MR00,Hoornbeeck College voor Mbo op Reformatorische...,AMERSFOORT,3818 ET,NL
2,1719899,1543665,2018,2018,2018-09-01,2019-08-31,Voltijd,B Arts Therapies (Art Therapy),BACTBE,34644,...,0,0,92631,MBO,19-09-17,27DV00,Stichting Regionaal Opleidingen Centrum AVENTUS,APELDOORN,7331 VZ,NL
3,1722984,1556941,2018,2018,2018-09-01,2019-08-31,Voltijd,B Arts Therapies (Art Therapy),BACTBE,34644,...,0,0,5171,VWO,13-06-18,25PT00,Talland College,ALKMAAR,1817 BC,NL
4,1734406,1536214,2018,2018,2018-09-01,2019-08-31,Voltijd,B Arts Therapies (Art Therapy),BACTBE,34644,...,0,0,0373,HAVO,14-06-17,02EA00,Scholengroep Driestar-Wartburg - Driestar Goud...,GOUDA,2803 ZV,NL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48386,1867539,1964301,2023,2023,2023-09-01,2024-08-31,Voltijd,Biology & Medical Laboratory Research,BTLCLS,34397,...,0,0,0171,VWO,09-06-22,21EX00,Theresialyceum voor gymnasium atheneum en havo,TILBURG,5037 DA,NL
48387,1867813,1966882,2023,2023,2023-09-01,2024-08-31,Voltijd,Biology & Medical Laboratory Research,BTLCLS,34397,...,0,0,0271,VWO,09-06-22,02DQ00,Christelijk Gymnasium Sorghvliet,'S-GRAVENHAGE,2517 JR,NL
48388,1868156,1972247,2023,2023,2023-09-01,2024-08-31,Voltijd,Biology & Medical Laboratory Research,BTLCLS,34397,...,1,0,0089,EDUCATIE,21-12-23,30PK,College voor Toetsen en Examens,0,0,0
48389,1868215,1973119,2023,2023,2023-09-01,2024-08-31,Voltijd,Biology & Medical Laboratory Research,BTLCLS,34397,...,1,0,0371,HAVO,10-06-21,20ST00,Sint-Janslyceum School voor Gymnasium Atheneum...,'S-HERTOGENBOSCH,5216 EG,NL
48390,1869081,1980114,2023,2023,2024-07-01,2024-08-31,Voltijd,Biology & Medical Laboratory Research,BTLCLS,34397,...,0,0,00611,OVERIG,30-06-20,28DN00,Hogeschool van Amsterdam: Amsterdam,AMSTERDAM,1097 DZ,NL

In [10]:


# Ensure no two or more columns have the same values
identical_columns = []
columns = data.columns.tolist()

for i in range(len(columns)):
    for j in range(i+1, len(columns)):
        col1, col2 = columns[i], columns[j]
        if data[col1].equals(data[col2]):
            identical_columns.append((col1, col2))

if identical_columns:
    print("Identical columns found:")
    for col_pair in identical_columns:
        print(col_pair)
else:
    print("No identical columns found.")

Identical columns found:
('Study_Pro_Start_Year', 'College_Year')
('Dropped_No_Diploma', 'Left_Unsuccessfully')
('Switched', 'Switched_Internally')

In [11]:
# Delete the duplicates and only leave columns whose names make more sense
del data['College_Year']
del data['Dropped_No_Diploma']
del data['Switched']

In [12]:
# Delete IDs that do not add value to the analysis

# del data['Enrollment_ID']
del data['Study_Prog_Code']
del data['Prior_Edu_ID']
del data['Prior_Edu_School_Code']

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48391 entries, 0 to 48390
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_num                 48391 non-null  int64
 1   Enrollment_ID               48391 non-null  int64
 2   Study_Pro_Start_Year        48391 non-null  int64
 3   Student_Start_Date          48391 non-null  datetime64[ns]
 4   Student_End_Date            48391 non-null  datetime64[ns]
 5   Student_Full_Parttime_Dual  48391 non-null  object
 6   Study_Prog_Name             48391 non-null  object
 7   Study_Prog_Group_ID         48391 non-null  int64
 8   Study_Bach_Master_Type      48391 non-null  object
 9   Study_Prog_Phase            48391 non-null  object
 10  Study_Prog_Exam_Date        13611 non-null  datetime64[ns]
 11  Study_Prog_Exam_Completed   48391 non-null  int64
 12  Left_Successfully           48391 non-null  int64
 13  Left_Unsuccessfully         48391 non-null  int64
 14  Switched_Internally         48391 non-null  int64
 15  Prior_Edu_Type              48391 non-null  object
 16  Prior_Edu_Exam_Date         48391 non-null  object
 17  Prior_Edu_School_Name       48391 non-null  object
 18  Prior_Edu_School_Location   48391 non-null  object
 19  Prior_Edu_Postcode          48391 non-null  object
 20  Prior_Edu_Country           48391 non-null  object
dtypes: datetime64[ns](3), int64(8), object(10)
memory usage: 7.8+ MB

In [14]:
data.isnull().sum()

Student_num                       0
Enrollment_ID                     0
Study_Pro_Start_Year              0
Student_Start_Date                0
Student_End_Date                  0
Student_Full_Parttime_Dual        0
Study_Prog_Name                   0
Study_Prog_Group_ID               0
Study_Bach_Master_Type            0
Study_Prog_Phase                  0
Study_Prog_Exam_Date          34780
Study_Prog_Exam_Completed         0
Left_Successfully                 0
Left_Unsuccessfully               0
Switched_Internally               0
Prior_Edu_Type                    0
Prior_Edu_Exam_Date               0
Prior_Edu_School_Name             0
Prior_Edu_School_Location         0
Prior_Edu_Postcode                0
Prior_Edu_Country                 0
dtype: int64

In [15]:
#  For now, delete the Study_Prog_Exam_Date because it has more than 50% of missing values, because of this high percentage of missing values, imputing them can unreliable.
del data['Study_Prog_Exam_Date']

In [16]:
data.columns

Index(['Student_num', 'Enrollment_ID', 'Study_Pro_Start_Year',
       'Student_Start_Date', 'Student_End_Date', 'Student_Full_Parttime_Dual',
       'Study_Prog_Name', 'Study_Prog_Group_ID', 'Study_Bach_Master_Type',
       'Study_Prog_Phase', 'Study_Prog_Exam_Completed', 'Left_Successfully',
       'Left_Unsuccessfully', 'Switched_Internally', 'Prior_Edu_Type',
       'Prior_Edu_Exam_Date', 'Prior_Edu_School_Name',
       'Prior_Edu_School_Location', 'Prior_Edu_Postcode', 'Prior_Edu_Country'],
      dtype='object')

In [17]:
#pd.set_option('display.max_rows', None)   # Show all rows (be careful if huge!)
#pd.set_option('display.max_columns', None)
#pd.set_option('display.max_colwidth', None)
#pd.set_option('display.width', 0)         # Automatically adjusts line-wrapping
#pd.set_option('display.expand_frame_repr', False)  

# Print value counts for all columns
for col in data.columns:
    print(f"Value counts for column: {col}")
    print(data[col].value_counts(dropna=False))  # include NaN values in the count
    print("\n" + "="*50 + "\n")

Value counts for column: Student_num
Student_num
1738512    5
1790132    4
1749375    4
1757301    4
1789725    4
          ..
1867539    1
1867813    1
1868156    1
1868215    1
1869081    1
Name: count, Length: 44681, dtype: int64

==================================================

Value counts for column: Enrollment_ID
Enrollment_ID
1980114    1
1546413    1
1549026    1
1543665    1
1556941    1
          ..
1550788    1
1547656    1
1546754    1
1545364    1
1544764    1
Name: count, Length: 48391, dtype: int64

==================================================

Value counts for column: Study_Pro_Start_Year
Study_Pro_Start_Year
2020    8463
2018    8418
2023    8030
2019    7935
2021    7923
2022    7622
Name: count, dtype: int64

==================================================

Value counts for column: Student_Start_Date
Student_Start_Date
2018-09-01    8274
2020-09-01    8272
2023-09-01    7765
2019-09-01    7740
2021-09-01    7655
              ...
2023-04-01       2
2022-06-01       2
2021-05-01       2
2023-06-01       2
2020-04-01       1
Name: count, Length: 64, dtype: int64

==================================================

Value counts for column: Student_End_Date
Student_End_Date
2021-08-31    6934
2019-08-31    6587
2020-08-31    6368
2024-08-31    6335
2022-08-31    6139
              ...
2021-06-30       2
2024-06-30       2
2020-07-31       1
2021-07-31       1
2024-07-31       1
Name: count, Length: 68, dtype: int64

==================================================

Value counts for column: Student_Full_Parttime_Dual
Student_Full_Parttime_Dual
Voltijd    48391
Name: count, dtype: int64

==================================================

Value counts for column: Study_Prog_Name
Study_Prog_Name
B Information & Communication Technology                 3215
B Social Work                                            2723
Journalism                                               2681
Creative Business                                        2516
Nursing                                                  2465
Bachelor of Law                                          2139
B International Business Utrecht                         2008
Physiotherapy                                            1860
B Business Administration                                1851
B Communication and Multimedia Design                    1774
B Marketing Management                                   1677
Biology & Medical Laboratory Research                    1663
B Safety and Security Management                         1562
Communication                                            1238
Educational Theory                                       1154
B Teacher Education in English                           1153
Industrial Engineering & Management                      1143
B Built Environment                                      1085
Social Legal Services                                    1042
B Human Resource Management                               930
B Pharmaceutical Business Administration                  842
B Finance & Control                                       653
Skin Therapy                                              647
Mechanical Engineering                                    638
B Education in Primary Schools (age 4 - 12) (day)         633
Dental Hygiene                                            604
B Teacher Education in History                            585
B Entrepreneurship & Retail Management                    569
Optometry                                                 534
B Accountancy                                             520
Chemistry                                                 465
Electrical and Electronic Engineering                     460
Speech and Language Therapy                               431
Health Care Management                                    419
B Finance, Tax and Advice                                 368
B Education in Primary Schools (age 4 - 12) (ALPO)        353
B Logistics Management                                    346
Orthoptics                                                339
B Cesar Kinetics Therapy                                  231
B Education in Primary Schools (age 4 - 12) (Regular)     222
B Teacher Education in Spanish                            215
Allied Medical Care                                       214
Interpreter                                               208
B Teacher Education in Mathematics                        203
Chemical Engineering                                      197
B Teacher Education in Social Skills                      189
B Teacher Education in Biology                            181
B Teacher Education in Geography                          157
B Arts Therapies (Art Therapy)                            146
B Teacher Education in Dutch                              120
B Facility Management                                     112
B Arts Therapies (Music Therapy)                          108
B Teacher Education in Welfare and Health Care            104
B Arts Therapies (Drama Therapy)                           93
Teacher                                                    89
B Teacher Education in German                              82
B Teacher Education in Physics                             78
B Teacher Education in Chemics                             76
B Teacher Education in French                              57
B Teacher Education in Technology                          24
Name: count, dtype: int64

==================================================

Value counts for column: Study_Prog_Group_ID
Study_Prog_Group_ID
30020    3215
34116    2723
34686    2681
35516    2516
34560    2465
39205    2139
30029    2008
34570    1860
34035    1851
34092    1774
34402    1677
34397    1663
39268    1562
34405    1238
34808    1208
35158    1154
35195    1153
34421    1143
39280    1085
34641    1042
34609     930
34090     842
35520     653
34091     647
34280     638
34576     604
35197     585
35523     569
34549     534
34406     520
34396     465
34267     460
34578     431
34538     419
35517     368
34644     347
35522     346
34577     339
34104     297
34571     231
35255     215
30023     214
35221     203
34275     197
35421     189
35301     181
35201     157
35198     120
34500     112
35388     104
35193      82
35261      78
35199      76
35196      57
35254      24
Name: count, dtype: int64

==================================================

Value counts for column: Study_Bach_Master_Type
Study_Bach_Master_Type
BA    48391
Name: count, dtype: int64

==================================================

Value counts for column: Study_Prog_Phase
Study_Prog_Phase
D    48391
Name: count, dtype: int64

==================================================

Value counts for column: Study_Prog_Exam_Completed
Study_Prog_Exam_Completed
0    34780
1    13611
Name: count, dtype: int64

==================================================

Value counts for column: Left_Successfully
Left_Successfully
0    46557
1     1834
Name: count, dtype: int64

==================================================

Value counts for column: Left_Unsuccessfully
Left_Unsuccessfully
0    30400
1    17991
Name: count, dtype: int64

==================================================

Value counts for column: Switched_Internally
Switched_Internally
0    44902
1     3489
Name: count, dtype: int64

==================================================

Value counts for column: Prior_Edu_Type
Prior_Edu_Type
HAVO          26918
MBO           12618
VWO            3320
BUITENL_SL     2768
OVERIG         2235
HBO             231
EDUCATIE        200
WO               61
-1               40
Name: count, dtype: int64

==================================================

Value counts for column: Prior_Edu_Exam_Date
Prior_Edu_Exam_Date
13-06-18    4066
12-06-19    3628
10-06-21    3413
09-06-22    3065
04-06-20    2371
            ...
11-06-13       1
29-05-15       1
28-05-18       1
18-10-16       1
02-07-12       1
Name: count, Length: 2104, dtype: int64

==================================================

Value counts for column: Prior_Edu_School_Name
Prior_Edu_School_Name
Stichting ROC Midden Nederland                                            3781
0                                                                         2842
Hogeschool Utrecht: Utrecht                                               1310
ROC van Amsterdam                                                         1176
Stichting Interconfessioneel Beroepsonderwijs Volwasseneneducatie regi    1136
                                                                          ...
Mariëndael                                                                   1
Compass voor Atheneum Havo en Mavo                                           1
PC/RK Scholengemeenschap De Grundel voor Lyceum Havo Mavo Vbo Lwoo           1
ROC Utrecht Maatwerk B.V.                                                    1
SOMT: Amersfoort                                                             1
Name: count, Length: 785, dtype: int64

==================================================

Value counts for column: Prior_Edu_School_Location
Prior_Edu_School_Location
UTRECHT       9254
0             3529
AMERSFOORT    3401
AMSTERDAM     2153
ROTTERDAM     1345
              ...
TER APEL         1
SOMEREN          1
BRUNSSUM         1
DOKKUM           1
GRAVE            1
Name: count, Length: 254, dtype: int64

==================================================

Value counts for column: Prior_Edu_Postcode
Prior_Edu_Postcode
3562 CS    3778
0          3570
3513 EX    1310
3526 AB    1256
1102 CV    1176
           ...
3012 BN       1
5912 BG       1
9727 DW       1
5361 HZ       1
3563 AT       1
Name: count, Length: 768, dtype: int64

==================================================

Value counts for column: Prior_Edu_Country
Prior_Edu_Country
NL    45155
0      3196
-1       40
Name: count, dtype: int64

==================================================

In [18]:
data.columns

Index(['Student_num', 'Enrollment_ID', 'Study_Pro_Start_Year',
       'Student_Start_Date', 'Student_End_Date', 'Student_Full_Parttime_Dual',
       'Study_Prog_Name', 'Study_Prog_Group_ID', 'Study_Bach_Master_Type',
       'Study_Prog_Phase', 'Study_Prog_Exam_Completed', 'Left_Successfully',
       'Left_Unsuccessfully', 'Switched_Internally', 'Prior_Edu_Type',
       'Prior_Edu_Exam_Date', 'Prior_Edu_School_Name',
       'Prior_Edu_School_Location', 'Prior_Edu_Postcode', 'Prior_Edu_Country'],
      dtype='object')

# Feature Engineering

In [19]:
# Student_ID: repeats but Enrollment_ID is unique, focus on Enrollement_ID
# Student_Full_Parttime_Dual: has only one value, delete
# Study_Bach_Master_Type: has only one value, delete
# Study_Prog_Phase: has only one value, delete
# Study_Prog_Name: collapse all subjects of Teacher Education to one category "Teacher_Education". 
  # check if sentence contains the key words Teacher Education
  # Add underscore between the words in all categories to make it one word, for this check object data types.
# Study_Prog_Group_ID: Create study program group size from this
# Prior_Edu_Type: if value count < 200, replace with  others
# Prior_Edu_School_Name: if value count < 100, replace with  others
# Prior_Edu_Exam_Date:Create Student_Enrollment_Gap from this and Student_Start_Date
# Prior_Edu_School_Location: if value count < 100, replace with  others, reclassify these locations into provinces?
  # Use Prior_Edu_Postcode instead, its more reliable than Prior_Edu_School_Location

In [20]:
# Student_Full_Parttime_Dual: has only one value, delete

del data['Student_Full_Parttime_Dual']
del data['Study_Bach_Master_Type']
del data['Study_Prog_Phase']

Engineer Study_Prog_Name

In [21]:
print(data['Study_Prog_Name'].value_counts())

Study_Prog_Name
B Information & Communication Technology                 3215
B Social Work                                            2723
Journalism                                               2681
Creative Business                                        2516
Nursing                                                  2465
Bachelor of Law                                          2139
B International Business Utrecht                         2008
Physiotherapy                                            1860
B Business Administration                                1851
B Communication and Multimedia Design                    1774
B Marketing Management                                   1677
Biology & Medical Laboratory Research                    1663
B Safety and Security Management                         1562
Communication                                            1238
Educational Theory                                       1154
B Teacher Education in English                           1153
Industrial Engineering & Management                      1143
B Built Environment                                      1085
Social Legal Services                                    1042
B Human Resource Management                               930
B Pharmaceutical Business Administration                  842
B Finance & Control                                       653
Skin Therapy                                              647
Mechanical Engineering                                    638
B Education in Primary Schools (age 4 - 12) (day)         633
Dental Hygiene                                            604
B Teacher Education in History                            585
B Entrepreneurship & Retail Management                    569
Optometry                                                 534
B Accountancy                                             520
Chemistry                                                 465
Electrical and Electronic Engineering                     460
Speech and Language Therapy                               431
Health Care Management                                    419
B Finance, Tax and Advice                                 368
B Education in Primary Schools (age 4 - 12) (ALPO)        353
B Logistics Management                                    346
Orthoptics                                                339
B Cesar Kinetics Therapy                                  231
B Education in Primary Schools (age 4 - 12) (Regular)     222
B Teacher Education in Spanish                            215
Allied Medical Care                                       214
Interpreter                                               208
B Teacher Education in Mathematics                        203
Chemical Engineering                                      197
B Teacher Education in Social Skills                      189
B Teacher Education in Biology                            181
B Teacher Education in Geography                          157
B Arts Therapies (Art Therapy)                            146
B Teacher Education in Dutch                              120
B Facility Management                                     112
B Arts Therapies (Music Therapy)                          108
B Teacher Education in Welfare and Health Care            104
B Arts Therapies (Drama Therapy)                           93
Teacher                                                    89
B Teacher Education in German                              82
B Teacher Education in Physics                             78
B Teacher Education in Chemics                             76
B Teacher Education in French                              57
B Teacher Education in Technology                          24
Name: count, dtype: int64

In [22]:
def clean_study_prog_name(value):
    if isinstance(value, str):
        # 1. Remove leading "B " if present
        if value.startswith("B "):
            value = value[2:]
        
        # 2. Replace based on keywords
        if "Teacher" in value:
            value = "Teacher_Education"
        elif "Arts Therapies" in value:
            value = "Arts_Therapies"
        elif "Education in Primary Schools" in value:
            value = "Primary_Education"
        else:
            # 3. Remove "&" and "," signs
            value = value.replace("&", "").replace(",", "").strip()
        
        # 4. Replace spaces between words with underscores
        value = "_".join(value.split())
        return value
    return value

# Apply the function to the column
data['Study_Prog_Name'] = data['Study_Prog_Name'].apply(clean_study_prog_name)

In [23]:
print(data['Study_Prog_Name'].value_counts())

Study_Prog_Name
Teacher_Education                         3313
Information_Communication_Technology      3215
Social_Work                               2723
Journalism                                2681
Creative_Business                         2516
Nursing                                   2465
Bachelor_of_Law                           2139
International_Business_Utrecht            2008
Physiotherapy                             1860
Business_Administration                   1851
Communication_and_Multimedia_Design       1774
Marketing_Management                      1677
Biology_Medical_Laboratory_Research       1663
Safety_and_Security_Management            1562
Communication                             1238
Primary_Education                         1208
Educational_Theory                        1154
Industrial_Engineering_Management         1143
Built_Environment                         1085
Social_Legal_Services                     1042
Human_Resource_Management                  930
Pharmaceutical_Business_Administration     842
Finance_Control                            653
Skin_Therapy                               647
Mechanical_Engineering                     638
Dental_Hygiene                             604
Entrepreneurship_Retail_Management         569
Optometry                                  534
Accountancy                                520
Chemistry                                  465
Electrical_and_Electronic_Engineering      460
Speech_and_Language_Therapy                431
Health_Care_Management                     419
Finance_Tax_and_Advice                     368
Arts_Therapies                             347
Logistics_Management                       346
Orthoptics                                 339
Cesar_Kinetics_Therapy                     231
Allied_Medical_Care                        214
Interpreter                                208
Chemical_Engineering                       197
Facility_Management                        112
Name: count, dtype: int64

Engineer Study_Prog_Group_ID

In [24]:
print(data['Study_Prog_Group_ID'].value_counts())

Study_Prog_Group_ID
30020    3215
34116    2723
34686    2681
35516    2516
34560    2465
39205    2139
30029    2008
34570    1860
34035    1851
34092    1774
34402    1677
34397    1663
39268    1562
34405    1238
34808    1208
35158    1154
35195    1153
34421    1143
39280    1085
34641    1042
34609     930
34090     842
35520     653
34091     647
34280     638
34576     604
35197     585
35523     569
34549     534
34406     520
34396     465
34267     460
34578     431
34538     419
35517     368
34644     347
35522     346
34577     339
34104     297
34571     231
35255     215
30023     214
35221     203
34275     197
35421     189
35301     181
35201     157
35198     120
34500     112
35388     104
35193      82
35261      78
35199      76
35196      57
35254      24
Name: count, dtype: int64

In [25]:
def add_group_size_column(data, group_column, new_column):
    """
    Adds a new column to the DataFrame that contains the count of each group based on the `group_column`.
    
    Parameters:
        data (DataFrame): The DataFrame where the new column will be added.
        group_column (str): The name of the column to group by.
        new_column (str): The name of the new column that will store the group sizes.
        
    Returns:
        DataFrame: The DataFrame with the new column added.
    """
    # Create a dictionary of counts for each group
    group_size = data[group_column].value_counts().to_dict()

    # Map the counts back to the dataframe as a new column
    data[new_column] = data[group_column].map(group_size)
    
    # Optionally drop the group column (if needed)
    del data[group_column]
    
    return data
    
# Example usage
data = add_group_size_column(data, 'Study_Prog_Group_ID', 'Study_Prog_Group_Size')

# Check if the new column is created and see its unique values
print(data['Study_Prog_Group_Size'].unique())

[ 347 1562  930 1154 2139 1042 2723  231  842 1860 2465  647  431  214
  604  534  339  419 2516 1238 1774 2681  520 1851 1677  653  112  368
 2008  346  569  181  104   78   76   24  203  297  157  585  189 1208
   82 1153   57  120  215 1085  460 1143 3215  638  197  465 1663]

Engineer Prior_Edu_Type

In [26]:
print(data['Prior_Edu_Type'].value_counts())

Prior_Edu_Type
HAVO          26918
MBO           12618
VWO            3320
BUITENL_SL     2768
OVERIG         2235
HBO             231
EDUCATIE        200
WO               61
-1               40
Name: count, dtype: int64

In [27]:
def clean_prior_edu_type(data, threshold=100, replacement="Others"):
    """
    Replaces values in the 'Prior_Edu_Type' column that appear less than a specified threshold with a replacement value.
    
    Parameters:
        data (DataFrame): The DataFrame where the replacement will be applied.
        threshold (int): The threshold for the minimum count, below which values will be replaced.
        replacement (str): The value that will replace the smaller counts.
        
    Returns:
        DataFrame: The DataFrame with the modified 'Prior_Edu_Type' column.
    """
    # Get the value counts for the 'Prior_Edu_Type' column
    value_counts = data['Prior_Edu_Type'].value_counts()
    
    # Identify values with counts less than the threshold
    small_values = value_counts[value_counts < threshold].index
    
    # Replace values with counts less than the threshold with 'Others'
    data['Prior_Edu_Type'] = data['Prior_Edu_Type'].replace(small_values, replacement)
    
    return data
# Call the function to clean the 'Prior_Edu_Type' column
data = clean_prior_edu_type(data, threshold=100, replacement="Others")

# Check the updated value counts
print(data['Prior_Edu_Type'].value_counts())

Prior_Edu_Type
HAVO          26918
MBO           12618
VWO            3320
BUITENL_SL     2768
OVERIG         2235
HBO             231
EDUCATIE        200
Others          101
Name: count, dtype: int64

Engineer Prior_Edu_School_Name

In [28]:
print(data['Prior_Edu_School_Name'].value_counts())

Prior_Edu_School_Name
Stichting ROC Midden Nederland                                            3781
0                                                                         2842
Hogeschool Utrecht: Utrecht                                               1310
ROC van Amsterdam                                                         1176
Stichting Interconfessioneel Beroepsonderwijs Volwasseneneducatie regi    1136
                                                                          ...
Mariëndael                                                                   1
Compass voor Atheneum Havo en Mavo                                           1
PC/RK Scholengemeenschap De Grundel voor Lyceum Havo Mavo Vbo Lwoo           1
ROC Utrecht Maatwerk B.V.                                                    1
SOMT: Amersfoort                                                             1
Name: count, Length: 785, dtype: int64

In [29]:
# Looking at how clumsy the sentences look like, I decided to use the Prior_Edu_Postcode column instead, later the postcode can be used to match the school name

Engineer Prior_Edu_Postcode

In [30]:
print(data['Prior_Edu_Postcode'].value_counts())

Prior_Edu_Postcode
3562 CS    3778
0          3570
3513 EX    1310
3526 AB    1256
1102 CV    1176
           ...
3012 BN       1
5912 BG       1
9727 DW       1
5361 HZ       1
3563 AT       1
Name: count, Length: 768, dtype: int64

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48391 entries, 0 to 48390
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Student_num                48391 non-null  int64
 1   Enrollment_ID              48391 non-null  int64
 2   Study_Pro_Start_Year       48391 non-null  int64
 3   Student_Start_Date         48391 non-null  datetime64[ns]
 4   Student_End_Date           48391 non-null  datetime64[ns]
 5   Study_Prog_Name            48391 non-null  object
 6   Study_Prog_Exam_Completed  48391 non-null  int64
 7   Left_Successfully          48391 non-null  int64
 8   Left_Unsuccessfully        48391 non-null  int64
 9   Switched_Internally        48391 non-null  int64
 10  Prior_Edu_Type             48391 non-null  object
 11  Prior_Edu_Exam_Date        48391 non-null  object
 12  Prior_Edu_School_Name      48391 non-null  object
 13  Prior_Edu_School_Location  48391 non-null  object
 14  Prior_Edu_Postcode         48391 non-null  object
 15  Prior_Edu_Country          48391 non-null  object
 16  Study_Prog_Group_Size      48391 non-null  int64
dtypes: datetime64[ns](2), int64(8), object(7)
memory usage: 6.3+ MB

In [32]:
# Function to clean Prior_Edu_Postcode
def clean_prior_edu_postcode(data, threshold=50, replacement="Others"):
    """
    Cleans the 'Prior_Edu_Postcode' column by:
    - Converting values to strings and stripping spaces
    - Replacing any zero or asterisk values (even with spaces) with '0000_ABROAD'
    - Adding underscores between words in postcode strings
    - Replacing rare postcodes (frequency < threshold) with 'Others'
    """
    # Convert to string and strip
    data['Prior_Edu_Postcode'] = data['Prior_Edu_Postcode'].astype(str).str.strip()
    
    # Replace zeros or asterisks with '0000_ABROAD' using regex
    data['Prior_Edu_Postcode'] = data['Prior_Edu_Postcode'].replace(
        to_replace=[r'^0+$', r'^\*+$'], value='0000_ABROAD', regex=True
    )
    
    # Add underscores between words
    data['Prior_Edu_Postcode'] = data['Prior_Edu_Postcode'].apply(lambda x: "_".join(x.split()))
    
    # Replace rare values with 'Others'
    value_counts = data['Prior_Edu_Postcode'].value_counts()
    small_values = value_counts[value_counts < threshold].index
    data['Prior_Edu_Postcode'] = data['Prior_Edu_Postcode'].replace(small_values, replacement)
    
    return data

# ✅ Validator function
def validate_prior_edu_postcode(data):
    """
    Check for leftover zero, asterisk, or trailing whitespace issues in Prior_Edu_Postcode.
    """
    remaining_issues = data['Prior_Edu_Postcode'][data['Prior_Edu_Postcode'].str.match(r'^(0+|\*+)$')]
    if remaining_issues.empty:
        print("✅ No '0' or '*' values remain in Prior_Edu_Postcode!")
    else:
        print("⚠️ Still found problematic values:")
        print(remaining_issues.value_counts())
    
    # Check for trailing spaces (should not happen if cleaned, but good check)
    trailing_space_issues = data['Prior_Edu_Postcode'][data['Prior_Edu_Postcode'].str.contains(r'\s$')]
    if trailing_space_issues.empty:
        print("✅ No trailing spaces found in Prior_Edu_Postcode.")
    else:
        print("⚠️ Found trailing spaces in:")
        print(trailing_space_issues.unique())

# ✅ Example Usage:
data = clean_prior_edu_postcode(data)   # Clean the column
validate_prior_edu_postcode(data)       # Validate if everything is fixed
data['Prior_Edu_Postcode'].value_counts()  # Check distribution if desired

✅ No '0' or '*' values remain in Prior_Edu_Postcode!
✅ No trailing spaces found in Prior_Edu_Postcode.

Prior_Edu_Postcode
Others         8589
3562_CS        3778
0000_ABROAD    3733
3513_EX        1310
3526_AB        1256
               ...
3034_PT          53
8932_NX          53
1071_ED          52
7231_NN          52
6904_GZ          51
Name: count, Length: 155, dtype: int64

In [33]:
data.columns

Index(['Student_num', 'Enrollment_ID', 'Study_Pro_Start_Year',
       'Student_Start_Date', 'Student_End_Date', 'Study_Prog_Name',
       'Study_Prog_Exam_Completed', 'Left_Successfully', 'Left_Unsuccessfully',
       'Switched_Internally', 'Prior_Edu_Type', 'Prior_Edu_Exam_Date',
       'Prior_Edu_School_Name', 'Prior_Edu_School_Location',
       'Prior_Edu_Postcode', 'Prior_Edu_Country', 'Study_Prog_Group_Size'],
      dtype='object')

In [34]:
print(data['Prior_Edu_School_Location'].value_counts())

Prior_Edu_School_Location
UTRECHT       9254
0             3529
AMERSFOORT    3401
AMSTERDAM     2153
ROTTERDAM     1345
              ...
TER APEL         1
SOMEREN          1
BRUNSSUM         1
DOKKUM           1
GRAVE            1
Name: count, Length: 254, dtype: int64

In [35]:
# Function to clean Prior_Edu_School_Location
def clean_prior_edu_school_location(data, threshold=50, abroad_replacement="0000_ABROAD", rare_replacement="Others"):
    """
    Cleans the 'Prior_Edu_School_Location' column by:
    - Stripping spaces
    - Replacing values '0', '*', or '-1' with abroad_replacement
    - Adding underscores between words
    - Replacing rare values (below threshold) with rare_replacement
    """
    # Strip spaces
    data['Prior_Edu_School_Location'] = data['Prior_Edu_School_Location'].astype(str).str.strip()
    
    # Replace '0', '*', or '-1' (even if they appear alone) with abroad_replacement
    data['Prior_Edu_School_Location'] = data['Prior_Edu_School_Location'].replace(
        to_replace=[r'^0+$', r'^\*+$', r'^-1$'], value=abroad_replacement, regex=True
    )
    
    # Add underscores between words
    data['Prior_Edu_School_Location'] = data['Prior_Edu_School_Location'].apply(lambda x: "_".join(x.split()))
    
    # Replace values appearing less than threshold times with rare_replacement
    value_counts = data['Prior_Edu_School_Location'].value_counts()
    small_values = value_counts[value_counts < threshold].index
    data['Prior_Edu_School_Location'] = data['Prior_Edu_School_Location'].replace(small_values, rare_replacement)
    
    return data

def validate_prior_edu_school_location(data):
    """
    Validates that no invalid values ('0', '*', '-1') or trailing spaces remain in 'Prior_Edu_School_Location'.
    """
    issues = data['Prior_Edu_School_Location'][data['Prior_Edu_School_Location'].str.match(r'^(0+|\*+|-1)$')]
    if issues.empty:
        print("✅ No invalid '0', '*', or '-1' values remain in Prior_Edu_School_Location.")
    else:
        print("⚠️ Found invalid values:")
        print(issues.value_counts())
    
    trailing_spaces = data['Prior_Edu_School_Location'][data['Prior_Edu_School_Location'].str.contains(r'\s$')]
    if trailing_spaces.empty:
        print("✅ No trailing spaces found.")
    else:
        print("⚠️ Found trailing spaces in:")
        print(trailing_spaces.unique())

# ✅ Usage:
data = clean_prior_edu_school_location(data)
validate_prior_edu_school_location(data)
data['Prior_Edu_School_Location'].value_counts()

✅ No invalid '0', '*', or '-1' values remain in Prior_Edu_School_Location.
✅ No trailing spaces found.

Prior_Edu_School_Location
UTRECHT                   9254
0000_ABROAD               3569
AMERSFOORT                3401
Others                    2818
AMSTERDAM                 2153
                          ...
BERGEN_NH                   54
CAPELLE_AAN_DEN_IJSSEL      53
PURMEREND                   53
WARNSVELD                   52
ZEVENAAR                    51
Name: count, Length: 89, dtype: int64

Engineer Prior_Edu_Country

In [36]:
data['Prior_Edu_Country'].value_counts()

Prior_Edu_Country
NL    45155
0      3196
-1       40
Name: count, dtype: int64

In [37]:
def clean_prior_edu_country(data, threshold=50, abroad_replacement="outside_NL", rare_replacement="Others"):
    """
    Cleans the 'Prior_Edu_Country' column by:
    - Stripping spaces
    - Replacing '0' and '-1' with abroad_replacement
    - Adding underscores between words
    - Replacing rare values (below threshold) with rare_replacement
    """
    # Strip spaces
    data['Prior_Edu_Country'] = data['Prior_Edu_Country'].astype(str).str.strip()
    
    # Replace '0' and '-1' with abroad_replacement
    data['Prior_Edu_Country'] = data['Prior_Edu_Country'].replace(
        to_replace=[r'^0+$', r'^-1$'], value=abroad_replacement, regex=True
    )
    
    # Add underscores between words
    data['Prior_Edu_Country'] = data['Prior_Edu_Country'].apply(lambda x: "_".join(x.split()))
    
    # Replace rare values
    value_counts = data['Prior_Edu_Country'].value_counts()
    small_values = value_counts[value_counts < threshold].index
    data['Prior_Edu_Country'] = data['Prior_Edu_Country'].replace(small_values, rare_replacement)
    
    return data

def validate_prior_edu_country(data):
    """
    Validates that no invalid values ('0' or '-1') or trailing spaces remain in 'Prior_Edu_Country'.
    """
    issues = data['Prior_Edu_Country'][data['Prior_Edu_Country'].str.match(r'^(0+|-1)$')]
    if issues.empty:
        print("✅ No invalid '0' or '-1' values remain in Prior_Edu_Country.")
    else:
        print("⚠️ Found invalid values:")
        print(issues.value_counts())
    
    trailing_spaces = data['Prior_Edu_Country'][data['Prior_Edu_Country'].str.contains(r'\s$')]
    if trailing_spaces.empty:
        print("✅ No trailing spaces found.")
    else:
        print("⚠️ Found trailing spaces in:")
        print(trailing_spaces.unique())

# ✅ Usage:
data = clean_prior_edu_country(data)
validate_prior_edu_country(data)
data['Prior_Edu_Country'].value_counts()

✅ No invalid '0' or '-1' values remain in Prior_Edu_Country.
✅ No trailing spaces found.

Prior_Edu_Country
NL            45155
outside_NL     3236
Name: count, dtype: int64

In [38]:
data.columns

Index(['Student_num', 'Enrollment_ID', 'Study_Pro_Start_Year',
       'Student_Start_Date', 'Student_End_Date', 'Study_Prog_Name',
       'Study_Prog_Exam_Completed', 'Left_Successfully', 'Left_Unsuccessfully',
       'Switched_Internally', 'Prior_Edu_Type', 'Prior_Edu_Exam_Date',
       'Prior_Edu_School_Name', 'Prior_Edu_School_Location',
       'Prior_Edu_Postcode', 'Prior_Edu_Country', 'Study_Prog_Group_Size'],
      dtype='object')

In [39]:
df1 = data
data = df1

# Feature Extraction

In [40]:
# Create Student_Enrollment_Gap column from Prior_Edu_Exam_Date and Student_Start_Date

import numpy as np

# Ensure the date columns are in datetime format
data['Student_Start_Date'] = pd.to_datetime(data['Student_Start_Date'], errors='coerce')
data['Prior_Edu_Exam_Date'] = pd.to_datetime(data['Prior_Edu_Exam_Date'], errors='coerce')

# Calculate the gap in days, then convert it to weeks and round down the result
data['Student_Enrollment_Gap'] = np.floor((data['Student_Start_Date'] - data['Prior_Edu_Exam_Date']).dt.days / 7)

# Optional: To handle cases where the date conversion fails (NaT), you can fill them with a value, e.g., 0 or another placeholder
data['Student_Enrollment_Gap'].fillna(0, inplace=True)

# Check the result
data[['Student_Start_Date', 'Prior_Edu_Exam_Date', 'Student_Enrollment_Gap']].head()

  Student_Start_Date Prior_Edu_Exam_Date  Student_Enrollment_Gap
0         2018-09-01          2015-07-07                   164.0
1         2018-09-01          2017-05-07                    68.0
2         2018-09-01          2017-09-19                    49.0
3         2018-09-01          2018-06-13                    11.0
4         2018-09-01          2017-06-14                    63.0

In [41]:
# Could negative values indicate that some students starting in HU before their Prior_Edu_Exam_Date? Could this be true or its not possible.
data['Student_Enrollment_Gap'].value_counts()

Student_Enrollment_Gap
 11.0      4882
 9.0       3210
-14.0      2297
-1.0       2270
-5.0       2132
           ...
 580.0        1
 288.0        1
 1409.0       1
 583.0        1
 1887.0       1
Name: count, Length: 577, dtype: int64

In [42]:
data.columns

Index(['Student_num', 'Enrollment_ID', 'Study_Pro_Start_Year',
       'Student_Start_Date', 'Student_End_Date', 'Study_Prog_Name',
       'Study_Prog_Exam_Completed', 'Left_Successfully', 'Left_Unsuccessfully',
       'Switched_Internally', 'Prior_Edu_Type', 'Prior_Edu_Exam_Date',
       'Prior_Edu_School_Name', 'Prior_Edu_School_Location',
       'Prior_Edu_Postcode', 'Prior_Edu_Country', 'Study_Prog_Group_Size',
       'Student_Enrollment_Gap'],
      dtype='object')

Create Exit_Status common from 'Left_Successfully', 'Left_Unsuccessfully', and 'Switched_Internally'

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48391 entries, 0 to 48390
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Student_num                48391 non-null  int64
 1   Enrollment_ID              48391 non-null  int64
 2   Study_Pro_Start_Year       48391 non-null  int64
 3   Student_Start_Date         48391 non-null  datetime64[ns]
 4   Student_End_Date           48391 non-null  datetime64[ns]
 5   Study_Prog_Name            48391 non-null  object
 6   Study_Prog_Exam_Completed  48391 non-null  int64
 7   Left_Successfully          48391 non-null  int64
 8   Left_Unsuccessfully        48391 non-null  int64
 9   Switched_Internally        48391 non-null  int64
 10  Prior_Edu_Type             48391 non-null  object
 11  Prior_Edu_Exam_Date        48391 non-null  datetime64[ns]
 12  Prior_Edu_School_Name      48391 non-null  object
 13  Prior_Edu_School_Location  48391 non-null  object
 14  Prior_Edu_Postcode         48391 non-null  object
 15  Prior_Edu_Country          48391 non-null  object
 16  Study_Prog_Group_Size      48391 non-null  int64
 17  Student_Enrollment_Gap     48391 non-null  float64
dtypes: datetime64[ns](3), float64(1), int64(8), object(6)
memory usage: 6.6+ MB

In [44]:
data[['Left_Successfully']].value_counts()

Left_Successfully
0                    46557
1                     1834
Name: count, dtype: int64

In [45]:
data[['Left_Unsuccessfully']].value_counts()

Left_Unsuccessfully
0                      30400
1                      17991
Name: count, dtype: int64

In [46]:
data[['Switched_Internally']].value_counts()

Switched_Internally
0                      44902
1                       3489
Name: count, dtype: int64

In [47]:
# Step 1: Create the 'Exit_Status' column and set default to 'leaving_unsuccessfully'
data['Exit_Status'] = 'leaving_unsuccessfully'  

# Step 2: Assign 'leaving_successfully' where Left_Successfully == 1
data.loc[data['Left_Successfully'] == 1, 'Exit_Status'] = 'leaving_successfully'  

# Step 3: Assign 'switching_internally' where Switched_Internally == 1
data.loc[data['Switched_Internally'] == 1, 'Exit_Status'] = 'switching_internally'  

# Step 4: Drop the original columns since they are now redundant
data.drop(columns=['Left_Successfully', 'Left_Unsuccessfully', 'Switched_Internally'], inplace=True)  

# Step 5: Verify the results
print(data['Exit_Status'].value_counts())

Exit_Status
leaving_unsuccessfully    43154
switching_internally       3489
leaving_successfully       1748
Name: count, dtype: int64

# Sample Data by undersampling

In [48]:
# Shuffle the dataset first
data = data.sample(frac=1, random_state=42).reset_index(drop=True)

# Find the minimum count among categories
min_count = data["Exit_Status"].value_counts().min()

# Perform undersampling after shuffling
undersampled_data = (
    data.groupby("Exit_Status")
    .apply(lambda x: x.sample(n=min_count, random_state=42))
    .reset_index(drop=True)
)

# Display the new counts
print(undersampled_data["Exit_Status"].value_counts())

Exit_Status
leaving_successfully      1748
leaving_unsuccessfully    1748
switching_internally      1748
Name: count, dtype: int64

In [49]:
data = undersampled_data

In [50]:
data.columns

Index(['Student_num', 'Enrollment_ID', 'Study_Pro_Start_Year',
       'Student_Start_Date', 'Student_End_Date', 'Study_Prog_Name',
       'Study_Prog_Exam_Completed', 'Prior_Edu_Type', 'Prior_Edu_Exam_Date',
       'Prior_Edu_School_Name', 'Prior_Edu_School_Location',
       'Prior_Edu_Postcode', 'Prior_Edu_Country', 'Study_Prog_Group_Size',
       'Student_Enrollment_Gap', 'Exit_Status'],
      dtype='object')

In [51]:
data.to_csv(os.path.join("..", "data", "processed", "EDA.csv"), header=True)

In [52]:
# Drop these columns because they do not add more value to the analysis

data.drop(columns=['Student_num', 
                   'Study_Pro_Start_Year',
                   'Student_Start_Date', 
                   'Student_End_Date', 
                   'Prior_Edu_Exam_Date',
                   'Prior_Edu_School_Name'], 
                   inplace=True)
data.columns

Index(['Enrollment_ID', 'Study_Prog_Name', 'Study_Prog_Exam_Completed',
       'Prior_Edu_Type', 'Prior_Edu_School_Location', 'Prior_Edu_Postcode',
       'Prior_Edu_Country', 'Study_Prog_Group_Size', 'Student_Enrollment_Gap',
       'Exit_Status'],
      dtype='object')

In [53]:
data.to_csv(os.path.join("..", "data", "processed", "features_engineered.csv"), header=True)

In [54]:
file_path = os.path.join("..", "data", "processed", "features_engineered.csv")

# Read CSV with index_col=0 to avoid unnamed column issues
df2 = pd.read_csv(file_path, index_col=0)

# Display the DataFrame
data = df2
data

,Enrollment_ID,Study_Prog_Name,Study_Prog_Exam_Completed,Prior_Edu_Type,Prior_Edu_School_Location,Prior_Edu_Postcode,Prior_Edu_Country,Study_Prog_Group_Size,Student_Enrollment_Gap,Exit_Status
0,1536258,Teacher_Education,1,BUITENL_SL,0000_ABROAD,0000_ABROAD,outside_NL,1153,39.0,leaving_successfully
1,1909325,Communication,1,HAVO,HOORN_NH,Others,NL,1238,51.0,leaving_successfully
2,1920233,Bachelor_of_Law,1,HAVO,CULEMBORG,4103_NM,NL,2139,51.0,leaving_successfully
3,1548428,Communication,1,HAVO,ZEIST,3707_EP,NL,1238,61.0,leaving_successfully
4,1848231,Bachelor_of_Law,1,HAVO,ZEIST,3708_AG,NL,2139,125.0,leaving_successfully
...,...,...,...,...,...,...,...,...,...,...
5239,1752948,Information_Communication_Technology,0,BUITENL_SL,0000_ABROAD,0000_ABROAD,outside_NL,3215,326.0,switching_internally
5240,1601483,International_Business_Utrecht,0,HAVO,BAARN,3742_CS,NL,2008,9.0,switching_internally
5241,1853782,Social_Work,0,HAVO,ZUTPHEN,Others,NL,2723,47.0,switching_internally
5242,1853742,Bachelor_of_Law,0,HAVO,NIEUWEGEIN,3439_MV,NL,2139,47.0,switching_internally
5243,1632514,Health_Care_Management,0,MBO,UTRECHT,3562_CS,NL,419,0.0,switching_internally

# Feature Extraction

In [55]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5244 entries, 0 to 5243
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Enrollment_ID              5244 non-null   int64
 1   Study_Prog_Name            5244 non-null   object
 2   Study_Prog_Exam_Completed  5244 non-null   int64
 3   Prior_Edu_Type             5244 non-null   object
 4   Prior_Edu_School_Location  5244 non-null   object
 5   Prior_Edu_Postcode         5244 non-null   object
 6   Prior_Edu_Country          5244 non-null   object
 7   Study_Prog_Group_Size      5244 non-null   int64
 8   Student_Enrollment_Gap     5244 non-null   float64
 9   Exit_Status                5244 non-null   object
dtypes: float64(1), int64(3), object(6)
memory usage: 450.7+ KB

In [56]:
print(data['Study_Prog_Exam_Completed'].value_counts())

Study_Prog_Exam_Completed
0    2988
1    2256
Name: count, dtype: int64

In [57]:
print(data['Prior_Edu_Country'].value_counts())

Prior_Edu_Country
NL            4953
outside_NL     291
Name: count, dtype: int64

In [58]:
# Define a mapping for Prior_Edu_Country
prior_edu_country_mapping = {
    'outside_NL': 0,
    'NL': 1
}

# Apply the mapping to replace categorical values with numbers
data['Prior_Edu_Country'] = data['Prior_Edu_Country'].map(prior_edu_country_mapping)

# Show the first few rows to verify
print(data['Prior_Edu_Country'].value_counts())

Prior_Edu_Country
1    4953
0     291
Name: count, dtype: int64

In [59]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5244 entries, 0 to 5243
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Enrollment_ID              5244 non-null   int64
 1   Study_Prog_Name            5244 non-null   object
 2   Study_Prog_Exam_Completed  5244 non-null   int64
 3   Prior_Edu_Type             5244 non-null   object
 4   Prior_Edu_School_Location  5244 non-null   object
 5   Prior_Edu_Postcode         5244 non-null   object
 6   Prior_Edu_Country          5244 non-null   int64
 7   Study_Prog_Group_Size      5244 non-null   int64
 8   Student_Enrollment_Gap     5244 non-null   float64
 9   Exit_Status                5244 non-null   object
dtypes: float64(1), int64(4), object(5)
memory usage: 450.7+ KB

In [60]:
# One-hot-encoded all columns with object data type

# Step 1: Identify all object (categorical) columns except 'Exit_Status'
categorical_cols = data.select_dtypes(include=['object']).columns  
categorical_cols = categorical_cols[categorical_cols != 'Exit_Status']  # Exclude 'Exit_Status'

# Step 2: Perform one-hot encoding with column names as prefixes
data = pd.get_dummies(data, columns=categorical_cols, prefix=categorical_cols, dtype=int)  

# Step 3: Check the transformed DataFrame  
data

,Enrollment_ID,Study_Prog_Exam_Completed,Prior_Edu_Country,Study_Prog_Group_Size,Student_Enrollment_Gap,Exit_Status,Study_Prog_Name_Accountancy,Study_Prog_Name_Allied_Medical_Care,Study_Prog_Name_Arts_Therapies,Study_Prog_Name_Bachelor_of_Law,...,Prior_Edu_Postcode_7414_AR,Prior_Edu_Postcode_7553_VZ,Prior_Edu_Postcode_8017_CA,Prior_Edu_Postcode_8024_AH,Prior_Edu_Postcode_8031_AA,Prior_Edu_Postcode_8081_VV,Prior_Edu_Postcode_8233_GA,Prior_Edu_Postcode_8932_NX,Prior_Edu_Postcode_9723_ZS,Prior_Edu_Postcode_Others
0,1536258,1,0,1153,39.0,leaving_successfully,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1909325,1,1,1238,51.0,leaving_successfully,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,1920233,1,1,2139,51.0,leaving_successfully,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1548428,1,1,1238,61.0,leaving_successfully,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1848231,1,1,2139,125.0,leaving_successfully,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5239,1752948,0,0,3215,326.0,switching_internally,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5240,1601483,0,1,2008,9.0,switching_internally,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5241,1853782,0,1,2723,47.0,switching_internally,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5242,1853742,0,1,2139,47.0,switching_internally,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5243,1632514,0,1,419,0.0,switching_internally,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [61]:
data.to_csv(os.path.join("..", "data", "processed", "feature_select.csv"), header=True)